### ISSUE TITLE
Custom resources in a non-default namespace not being resolved

### ISSUE THREAD

**Issue by smithago** [Azure/vscode-kubernetes-tools#1005]
I recently installed the extension and it is connected to my AKS cluster.

I have a custom resource in a non-default namespace. I do not see the instances of the custom resource being resolved in the viewer.

How do I specify the namespace, or can it auto-figure out the namespace?

![image](https://user-images.githubusercontent.com/6980724/142958535-16e0ec59-db9f-4596-90cf-e1fa5e10f25c.png)

**Comment by smithago** [comment]
![image](https://user-images.githubusercontent.com/6980724/142958644-27275faa-40b8-4852-a452-76e094bf476e.png)

**Comment by lstocchi** [comment]
@smithago if you expand the namespaces node you should see all namespaces available. By right-clicking the namespace you want to use and then click on `Use namespace`, you should see all resources belonging to that namespace (pods, deployment, custom resources...)

**Comment by smithago** [comment]
Worked. Thanks.
