### ISSUE TITLE
Fail to open dashboard through "open dashboard" in explorer

### ISSUE THREAD

**Issue by kyliel** [Azure/vscode-kubernetes-tools#105]
Right click "open dashboard" and then http://localhost:8001/ui/ is opened in my browser with error message "This website can not be reached". 

If I run below command in TERMINAL, I can successfully open the dashboard.
az aks browse -g xxx -n xxx
http://localhost:8001/ui/

**Comment by kyliel** [comment]
@testforstephen , could you please take a look? Thank you.

**Comment by kyliel** [comment]
@bnookala , could you please take a look this issue? I can open the dashboard through az aks browse.

**Comment by songkaiape** [comment]
Below is the detail when we run the command "Kubernetes: open dashboard"

command "Kubernetes: open dashboard" get the wrong url

![image](https://user-images.githubusercontent.com/4318793/37638177-71517dfe-2c46-11e8-99ec-d8d55bb2e5d6.png)

On unbuntu:
after execute the command , open "http://localhost:8001/ui" will redirect to http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
and get error like below:
![image](https://user-images.githubusercontent.com/4318793/37637851-ef7f5fcc-2c44-11e8-9f1f-3c8010207b64.png)
Actually ,The right url is http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

On mac:
after execute the command open "http://localhost:8001/ui" will redirect to http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/

Actually ,The right url is http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

**Comment by bnookala** [comment]
Taking a look!

**Comment by itowlson** [comment]
Looking at the implementation of `az aks browse` it looks like it locates a dashboard pod and does a port-forward to that.  Would that work generically on k8s clusters, and if so should we do that instead of using `kubectl proxy` or having detection and special handling for AKS?

**Comment by bnookala** [comment]
@itowlson I think there's more going on… I've tried this myself, and the dashboard doesn't completely load when just using a `kubectl port-forward`. It would be ideal to use the underlying behavior of `kubectl proxy`, since then we wouldn't have to simulate the behavior of `az aks browse` within the context of the extension. 

However… even if we did choose to detect AKS clusters and use `az aks browse`, we'd still need to know the name and the resource group of the cluster to invoke the az cli. I don't think this is information that is known to us already since we don't interact with the az cli, so we'd *also* have to gather that from the user to make the dashboard work.

**Comment by itowlson** [comment]
Weird.  `az aks browse` doesn't seem to do much more than getting the pod info and doing a `kubectl port-forward` to that pod; so if that works and the dashboard loads, then I don't see why doing the same thing directly wouldn't work... strange!  Here's the implementation if it's any help...:

https://github.com/Azure/azure-cli/blob/c8edc8b04aa7630da246e5d01cd587c3d836aac5/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L1254

**Comment by bnookala** [comment]
@itowlson I had an another try to see what `kubectl proxy` would do on two clusters, and it appears that the `localhost:8001/ui` redirect is somewhat broken between k8s versions, so maybe I had missed something originally.

AKS 1.8.7: `kubectl proxy` with a load of `localhost:8001/ui` in a browser loads http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/, which promptly fails with this TLS error:

```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.244.0.2:9090/'
```

Though hitting http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default on the same cluster seems to load the dashboard fine. 

ACS-Engine with k8s 1.9.3: `kubectl proxy` with a load of `localhost:8001/ui` in a browser redirects to
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default, which loads fine, but http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ does not.

So… AKS 1.8.7 (latest) will load at http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

ACS-Engine w/ k8s 1.9.3 will load at http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default

As I'm using kubectl 1.9.5, I think this *may* have something to do with that. So perhaps port-forward would be the most straightforward route to get to the dashboard. I tried this with AKS, and it works fine. However, port-forwarding the ACS engine pod doesn't seem to work.

**Comment by squillace** [comment]
holy criminoly, batman.

**Comment by bnookala** [comment]
Ok, after discussion, this will be the course of action:

Detect if the active cluster is AKS, if yes, port-forward to the kube-system dashboard pod, and open a browser to the bound port on localhost. If no: shell out to `kubectl proxy`, and pray.

**Comment by songkaiape** [comment]
OS: Mac&&linux
Build: 4407
`For AKS`:
Now open dashboard works good with AKS. 

`For ACS &&local minikube:`
open dashboard still open the wrong url
1. Right click a cluster and choose "Open Dashboard"
Only some info output in the terminal, browse is not open
![image](https://user-images.githubusercontent.com/4318793/38916796-45f82ebe-431b-11e8-897f-6f9db765ee54.png)
2. click the cluster and choose "Open Dashboard" again. A browse is open and the url is  http://127.0.0.1:8001/ui

3. if the cluster is ACS the url will redirect to 
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard:/proxy/
The page is blank.

   if the cluster is minikube, the url won't redirect. The page shows like below
![image](https://user-images.githubusercontent.com/4318793/38917111-4b7588cc-431c-11e8-8ecb-f7cc70fc5c7a.png)
  local cluster can be open correctly with "minikube dashboard"
