### ISSUE TITLE
[Feature] Kubernetes Manifest Authoring - code snippets 

### ISSUE THREAD

**Issue by kyliel** [Azure/vscode-kubernetes-tools#11]
Code snippets are templates that make it easier to enter repeating code patterns, such as loops or conditional-statements. You could get an example from https://code.visualstudio.com/docs/editor/userdefinedsnippets. 

This feature is to add code snippets for Kubernetes Manifest files. 

API references are here - https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#types-kinds 
More examples are here - https://github.com/kubernetes/kubernetes/tree/master/examples 
HereI list examples for the file of kind:deployment. 
		Refer to https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
		Refer to https://github.com/egamma/todo-app-java-on-azure/blob/egamma/setup/doc/resources/fabric8/deployment.yml

**Comment by kyliel** [comment]
@andxu will work on it.

**Comment by itowlson** [comment]
Feature request on old extension: https://github.com/brendandburns/vs-kubernetes/issues/39

**Comment by andxu** [comment]
https://github.com/Azure/vscode-kubernetes-tools/pull/104#partial-pull-merging

**Comment by andxu** [comment]
Basic code snippets are done. Close this issue.
