### ISSUE TITLE
some provided vm size are not valid on azure portal for azure container cluster

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#113]
![image](https://user-images.githubusercontent.com/4318793/37634044-c500430c-2c2f-11e8-9973-13d38a6d5c03.png)
![image](https://user-images.githubusercontent.com/4318793/37634053-cfba93d8-2c2f-11e8-9137-7df7bdcce7e7.png)

When I create a Azure container service cluster , I select basic0 type vm and the creation failed.
I think it should filter the invalid vm size.

**Comment by itowlson** [comment]
Thanks for reporting this.  It seems like ACS/AKS does have additional restrictions on the permitted agent node SKUs, but there's no API for finding out what they are.  Fortunately acs-engine is open source so we can duplicate the logic and give you a filtered view.  I'll take a look at this.

**Comment by itowlson** [comment]
acs-engine source: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/Get-AzureConstants.py.  Looks like it just strips out Basic SKUs.
