### ISSUE TITLE
command "Helm inpect chart" always show error

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#116]
I have found the usage of "helm inspect " and "helm inspect chart". Below is the sample of the commands.

![image](https://user-images.githubusercontent.com/4318793/37637329-0cab2cd2-2c42-11e8-923d-3c9564e4040d.png)

![image](https://user-images.githubusercontent.com/4318793/37637358-3f0c03f4-2c42-11e8-8790-1d56a0164306.png)

And when I try to run "helm inspect chart" from the plugin, I always got error like below.

![image](https://user-images.githubusercontent.com/4318793/37637383-6016be9a-2c42-11e8-939b-22914b069560.png)

**Comment by itowlson** [comment]
`Helm Inspect Values` can't be run from the Command Palette - only by right-clicking in the VS Code Explorer pane and selecting Helm: Inspect Values.  Is there a better way we can explain this within the constraints of a VS Code error notification?

@testforstephen did you find a way of preventing commands from appearing in the palette when they were only meant to be used from the Explorer?  If so, we could use this here.

**Comment by testforstephen** [comment]
@itowlson , follow the document https://code.visualstudio.com/updates/v1_10#_context-specific-visibility-of-command-palette-menu-items, you could control the visibility through `when` condition at `menus/commandPalette`.

See the Code Snippets:
https://github.com/Azure/vscode-kubernetes-tools/blob/master/package.json#L225
https://github.com/Microsoft/vscode-azurefunctions/blob/master/package.json#L378

**Comment by itowlson** [comment]
Thanks @testforstephen for pointing me at the fix!
