### ISSUE TITLE
command "Kubernetes: open dashboard" get the wrong url

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#117]
On unbuntu:
after execute the command , open "http://localhost:8001/ui" will redirect to http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
and get error like below:
![image](https://user-images.githubusercontent.com/4318793/37637851-ef7f5fcc-2c44-11e8-9f1f-3c8010207b64.png)
Actually ,The right url is http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

On mac:
after execute the command open "http://localhost:8001/ui" will redirect to Actually ,The right url is http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/

Actually ,The right url is http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

**Comment by kyliel** [comment]
Duplicate with #105 . @songkaiape , could you please add details there and close this one? Thank you.

**Comment by songkaiape** [comment]
@kyliel OK, got it
