### ISSUE TITLE
Command "Helm: Create chart" should pop out error when there is no open folder.

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#119]
when there is no open folder, run command "Helm: Create chart", there is no error pop out.
But we can find error log in developer tools. 
![image](https://user-images.githubusercontent.com/4318793/37638847-da9e0964-2c49-11e8-803f-37751cb5d969.png)

Suggest to pop out an error when there is no open folder.

**Comment by sallyur** [comment]
This issue also repro in following two cases：
1. 1)F1 ,excute command Helm: Lint/Helm:dependency update
    2)Pop out a window let choose one from your chart list
    3) Don't choose any one
Pop up error in toggle developer tools:
2. 1)Make sure there is no workspace
    2)F1 ,excute command Kubernetes: Exec/Kubernetes: Terminal
    3)A window will pop out ask "Please provide a command to execute" ,input "env" ,click enter
Pop up error in toggle developer tools:
![image](https://user-images.githubusercontent.com/28860891/38860079-eec3effc-4261-11e8-8cc4-98d12aafb028.png)

**Comment by kyliel** [comment]
@itowlson @bnookala , Could you please see new comment to see whether we should reopen it? This is tested against latest version.

**Comment by itowlson** [comment]
@kyliel I'd suggest raising a new issue for these.
