### ISSUE TITLE
[Feature] Kubernetes Manifest Authoring - Validation

### ISSUE THREAD

**Issue by kyliel** [Azure/vscode-kubernetes-tools#13]
Validate the schema during editing Kubernetes Manifest files

**Comment by kyliel** [comment]
@andyxu will work on it.

**Comment by kyliel** [comment]
@andxu Add correct Andy here.

**Comment by andxu** [comment]
Finshed, see PR https://github.com/Azure/vscode-kubernetes-tools/pull/62
