### ISSUE TITLE
[Linux] "copy name" can't copy resource name from the tree view

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#140]
We test this command on Mac, Windows and Linux. Only work good on Windows and Mac.
On Linux, nothing was copied.

**Comment by kyliel** [comment]
@testforstephen , please take a look on Linux.

**Comment by songkaiape** [comment]
Minikube version :0.25.2
VScode: 1.22.1
OS: Ubuntu 16.04 
build: 3940 https://vscjavaci.cloudapp.net/job/vscode-k8s-tools.vsix/3940/ &&release build 0.17
I have checked this issue with private build 3940. This issue doesn't repro.

**Comment by songkaiape** [comment]
@itowlson Yes, It does't repro.

**Comment by rhysjtevans** [comment]
Looking upstream, for me it was a dependency issue on npm package clipboardy looking for 'xsel' on my ubuntu distro.

[https://github.com/sindresorhus/clipboardy/issues/36](https://github.com/sindresorhus/clipboardy/issues/36)
