### ISSUE TITLE
Intellisense doesn't work at some circumstances in YAML file

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#147]
I only get auto completion at the first line in the same level. 
Below is detailed screenshot

**First line of the level**, we can get auto completion prompt
![image](https://user-images.githubusercontent.com/4318793/38072225-fdeacac8-3357-11e8-9c6c-f4ef0a0a0a9f.png)
**Second line of the level,** we can’t get auto completion prompt
![image](https://user-images.githubusercontent.com/4318793/38072234-0380f30e-3358-11e8-93c5-daa382d83c85.png)

**Comment by kyliel** [comment]
@andxu , could you please take a look? Thanks.
