### ISSUE TITLE
Kubernetes: Launch Debug failed with ErrorImagePull error using AKS

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#148]
Repro step:
following this instruction https://github.com/Azure/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md to set up environment.
We create a private ACR to save image.

1. Download the complete project
2. Launch vscode and install debugger for java
3. Set up the image repository on the VS Code user or workspace settings, using the `vsdocker.imageUser` configuration setting.
4.  Log into your repository using the appropriate tool. For example, to log into Docker Hub, run `docker login`; to log into Azure Container Registry, run `az acr login -n <acrname> `
5. F1，Kubernetes: Launch Debug

Expect: debugger start successfully.
Actual:
![image](https://user-images.githubusercontent.com/4318793/38078845-22edb17e-3370-11e8-90db-921dfad0c954.png)

Also, Deploying service with private ACR to AKS will fail with same error. 
Meanwhile,  Deploying service and launching debug with private ACR to ACS  will succeed using ACS cluster. 

Sample YAML file

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: complete-debug
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: complete-debug
    spec:
      containers:
      - name: complete-debug
        image: complete:latest
        **imagePullPolicy: Never**

**Comment by bnookala** [comment]
@songkaiape I think within the yaml file you provided, the image name is wrong. If you're using a private registry, the image name should be: `sallacr.azurecr.io/complete:latest` - can you try using that in your deployment yaml?

**Comment by songkaiape** [comment]
@bnookala I have tried `sallyacr.azurecr.io/complete:latest` but still failed. And I can pull the image on local machine using `docker pull sallyacr.azurecr.io/complete:latest`. Seems AKS didn't get the credentials for the private registry.

**Comment by songkaiape** [comment]
@kyliel we can use aks with acr now, thanks. Close this issue
