### ISSUE TITLE
Extension fails because of unknown dependency

### ISSUE THREAD

**Issue by radu-matei** [Azure/vscode-kubernetes-tools#153]
If I don't have the Red Hat extension, it will fail with the following message:

```
Extension 'ms-kubernetes-tools.vscode-kubernetes-tools' failed to activate. Reason: unknown dependency 'redhat.vscode-yaml'.
```

Should it prompt me to install it rather than fail?

**Comment by bnookala** [comment]
From conversation with @radu-matei, a developer will run into this issue when running from source, and without the extension/ extension dependencies installed from the marketplace.

**Comment by bnookala** [comment]
@radu-matei I can't confidently find a way to get around this in the build process. i'll try and keep digging for an answer, however.  for now, can you install the redhat.vscode-yaml extension through the extension marketplace?

**Comment by itowlson** [comment]
I don't think we can 'fix' this because it's internal VS Code behaviour, but I've sent a PR to better document the prerequisite.
