### ISSUE TITLE
Debug configurations broken

### ISSUE THREAD

**Issue by evanlouie** [Azure/vscode-kubernetes-tools#157]
The "Launch Extension" and "Launch Tests" configurations are currently broken due to them listing `npm` as a `preLaunchTask`.

The `npm` task is currently configured to run the compile script in package.json which runs with `--watch`; which never terminates, so the `preLaunchTask` is never completed causing it to hang.

vscode: Version 1.21.1 (1.21.1)
vscode-kubernetes-tools: `master`

Steps to reproduce:

- Checkout master
- Open extension in vscode
- `F5` or Debug->"Launch Extension"
- VScode will now build the extension but never launch the new window with the extension loaded

Current workaround:

- Start build task prior to launching debugger (CMD+Shift+B)
- Launch Extension (F5)

Updating launch.json to 0.2.0 and tasks to 2.0.0 schema versions would act as a permanent fix this

**Comment by bnookala** [comment]
Interesting - I just tried myself on v1.21.1 on a fresh repo with the master branch, and didn't encounter this issue. Are you launching the extension via the `Start Debugging` menu?

**Comment by evanlouie** [comment]
I've tried both. `Debug -> Start Debugging` and the 'play' button in the Debug side menu. Both result in same thing.

Bottom notification bars just hang on this:

<img width="600" alt="screen shot 2018-04-03 at 1 23 47 pm" src="https://user-images.githubusercontent.com/2081587/38273995-48566bc4-3742-11e8-9774-381034aef9e5.png">
