### ISSUE TITLE
Could not find task: npm watch

### ISSUE THREAD

**Issue by radu-matei** [Azure/vscode-kubernetes-tools#161]
This seems to be related to #158 

<img width="659" alt="screen shot 2018-04-06 at 12 06 38" src="https://user-images.githubusercontent.com/13103165/38412942-12d29d26-3993-11e8-845c-701d58ef99ab.png">

cc @evanlouie

**Comment by evanlouie** [comment]
Is your package.json on master? #158 added the `npm: watch` script and it is still in master, so there shouldn't be any issues finding it.

**Comment by radu-matei** [comment]
I found this the hard way, but you have to reload the VS Code window once your launch config changes.

So closing this as it's not related to our implementation.

Thanks, @evanlouie!
