### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by feiskyer** [Azure/vscode-kubernetes-tools#17]
Seems it is not published yet to marketplace?

**Comment by bnookala** [comment]
@feiskyer You can package the extension yourself using the vsce tool, which generates a vsix package: https://code.visualstudio.com/docs/extensions/publish-extension#_packaging-extensions.

From there you can install it, by following the instructions here: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by feiskyer** [comment]
@bnookala cool. thanks

**Comment by bnookala** [comment]
@feiskyer Woo: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools

**Comment by feiskyer** [comment]
@bnookala Cool. Will have a try.
