### ISSUE TITLE
Validation doesn't work at some circumstances.

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#175]
validation doesn't work in following case. A space is missing between "name" and "test". But there is no error red line to remind user. 

![image](https://user-images.githubusercontent.com/4318793/38802670-afe2201e-419f-11e8-8cde-752e863afefe.png)

**Comment by bnookala** [comment]
@andxu would you be able to look at this? seems like another yaml parser issue.

**Comment by itowlson** [comment]
@andxu Do you have time to look into these issues?

**Comment by andxu** [comment]
I will look into this issue, it seems a bug in vscode-yaml owned by redhat, it might need some time for the final fix to be available at market place.

**Comment by testforstephen** [comment]
Add a PR to solve the missing validation rule. 
But for the timestamp issue, the schema definition is a string type. Although `kubectl apply` doesn't complain it, i prefer to keep the strict rule to give an error for `null` value.

**Comment by tlycken** [comment]
> Although kubectl apply doesn't complain it, i prefer to keep the strict rule to give an error for null value

`null` _is_ a valid `string`. (Well, you can define a type system where it's not, but it doesn't seem relevant in this case.) The validation output tool is substantially less valuable if

**Comment by testforstephen** [comment]
`null` is an interesting question in json validator. Agree that the validation should be accurate. 

A quick fix on the schema side is changing the type of timestamp to ['string', 'null'], that can pass the validation. The problem here is it looks like a generic problem, and should be fixed at the generic [vscode-yaml](https://github.com/redhat-developer/vscode-yaml) extension side.

**Comment by itowlson** [comment]
@testforstephen @andxu If we think this is a bug in vscode-yaml, can we raise it there with a small repro (smaller than our massive Swagger file anyway!), and link that back to this issue please?  Thanks!

**Comment by testforstephen** [comment]
Created an issue https://github.com/redhat-developer/yaml-language-server/issues/72

**Comment by sallyur** [comment]
Verified, the results as below:

Build: 4626

Scenarios | Windows | Mac | Linux
-- | -- | -- | --
A space is missing, but there is no error red line to remind user. | Not repro | Not repro | Not repro
Yaml validator will report an error for null value when the   schema type is string. | Repro | Repro | Repro

**Comment by testforstephen** [comment]
The latest version `0.0.13` of vscode-yaml extension has fixed the null value validation bug. So close the issue.

**Comment by itowlson** [comment]
@testforstephen VS Code doesn't provide a way to declare a dependency on a particular version of another extension, does it?  So I should possibly add some documentation around this...

**Comment by testforstephen** [comment]
Correct, there's no way to specify the specific dependency version. And every time VS Code is reloaded or restarted, it'll auto check the latest version for all the installed extensions and auto upgrade to latest version by default.

**Comment by andxu** [comment]
@testforstephen there is a setting 'extensions.autoUpdate' in vscode defaults to true, if user chooses to disable it, vscode will not update the extensions automatically, so you'd better to specify the minimal vscode-yaml version, or check this version in our extension.
