### ISSUE TITLE
Eror pop up when user cancel the port forward action

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#176]
1. Right click a pod and choose port forward
2. Type nothing in the box and clicking other areas make the box disappear

![image](https://user-images.githubusercontent.com/4318793/38803200-0b4b10c2-41a1-11e8-9ad8-9ad0b6adbf39.png)

**Comment by bnookala** [comment]
@songkaiape the expected behavior here is that the user provides a port to port forward to. Either a mapping:

`8888:80` or a single port (the target port on the pod) will work: `8888`.
