### ISSUE TITLE
Got connection refused error after launch debug in todo-app project

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#177]
project: https://github.com/Microsoft/todo-app-java-on-azure
Build: 4407
OS: MAC &&Linux
1. download project and setting use local minikube
2. launch debug
3. the debugger can start successfully
4. visit localhost:8080
got error like below:
![image](https://user-images.githubusercontent.com/4318793/38803860-0fdd6250-41a3-11e8-976c-999c82fc886d.png)

**Comment by radu-matei** [comment]
Hi, @songkaiape!
Did you use the debug adapter from #160?

**Comment by songkaiape** [comment]
@radu-matei  I set the wrong port so the port-forward failed. Actually the app port is 80. After change the port to 80. The error doesn't repro.
