### ISSUE TITLE
Support port-forward for multiple pairs of port mapping

### ISSUE THREAD

**Issue by testforstephen** [Azure/vscode-kubernetes-tools#185]
Support `port-forward 8000:8000 8001:8001`

**Comment by radu-matei** [comment]
We should really support this. A nice to have would be https://github.com/Azure/vscode-kubernetes-tools/pull/149#issuecomment-377923348

**Comment by itowlson** [comment]
Any thoughts on a user experience for this?  VS Code doesn't offer us a very rich UI toolkit for doing anything fancy.  I guess we could keep the existing user experience and treat it as 'add a port-forward', but it doesn't feel very pleasant: users would have to select the same pod multiple times - not much fun if listing resources is slow (which it is for me!) - and we'd have to spawn multiple kubectls which the user would have to shut down separately.  I've seen extensions do clever things to simulate multi-select drop downs, which might help if we only cared about ports that we could determine from the pod spec...?

**Comment by bnookala** [comment]
@itowlson we'd have to do something like:

1. From the open pod specification or from all findable pods, select a pod (through a dropdown of multiple pods)
2. Find all containers in the pod
   - Is there only one container?
	- Get container ports for running container + expose in a multi select dropdown
	    * but if I wanted to customize the local bound port for multiple port forwards, how would i do that? a series of input box prompts for each selected remote port?
   - Multiple containers?
       - Show a select box for the container
           -  Once running container is selected + expose in a multi select dropwdown 
               * once again, we run into questions surrounding how to expose multiple port-forwards

At the worst of this, if a user must port forward to a pod w/ multiple containers w/ multiple ports that's currently not described by an open document, they must go through: Select pods (dropdown # 1), Select a container in pod (dropdown # 2), Select multiple ports (dropdown # 3), for each port selected, type out a local bound port (input box # 1... 2... 3... etc.). I can imagine this will get frustrating.

**Comment by testforstephen** [comment]
@bnookala  In current port-forward input box, it limits to only one port mapping pair there. Why not to support space separated port mapping pairs? That keeps consistent with the port-forward cli command's behavior.

**Comment by squillace** [comment]
Can I get a larger feature-centric view of the use case? Yes, I get it that if the user knows they want multiple mappings, but I would like to hear a general description of the most common usage story.
