### ISSUE TITLE
Cannot read property 'matchLabels' of undefined when clicking service "kubernetes" node in Explorer View

### ISSUE THREAD

**Issue by testforstephen** [Azure/vscode-kubernetes-tools#190]
In Explorer, click the "Services -> kubernetes" node under the default namespace, it pops error message `Cannot read property 'matchLabels' of undefined`.

**Comment by itowlson** [comment]
This could affect any service without a selector (https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors).  Fix in progress.
