### ISSUE TITLE
Draft Debug: Enable F5 to work against minikube as well as remote clusters

### ISSUE THREAD

**Issue by squillace** [Azure/vscode-kubernetes-tools#192]
Currently in 0.1.8, F5 support for Draft Debug works fine with remote registries and clusters, but it doesn't check the current docker context and therefore is unable to pick up and use the `eval $(minikube docker-env)` context with F5. 

Per https://github.com/Azure/draft/blob/master/docs/install-minikube.md#configure-docker, this works in Draft on the command line, but not in VS Code. The build gets pushed to the wrong repository, resulting in error image pull. 

Love to respect the docker context of local, as draft does on in the shell.

**Comment by kohv** [comment]
What's the status with this issue? As of now, draft CLI doesn't support `watch`, and the only way to get this functionality is through vscode IDE. But it doesn't work if you want to use minikube docker context.


Maybe this plugin could have something like `"vs-kubernetes.draft-runbefore"` user setting where we can specify the `eval $(minikube docker-env)`
