### ISSUE TITLE
Add 'create cluster' command

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#2]
Initially  support AKS (and probably ACS until AKS is GA), but design to make it easy for other contributors to add GKE, EKS, etc.  Prompt for location and configuration parameters and kick it off.  Option to automatically configure VS Code extension to use the new cluster if that works with the spin-up time.

**Comment by brendandburns** [comment]
Great to see this get started!  Please feel free to @ me into any PRs...

--brendan



________________________________________

**Comment by itowlson** [comment]
Fixed in #6
