### ISSUE TITLE
Cannot edit in read-only editor v0.1.8

### ISSUE THREAD

**Issue by earlcoder** [Azure/vscode-kubernetes-tools#200]
Since the 0.1.8 update I can not edit kubernetes files (configmaps/deployments...) anymore.  "Cannot edit in read-only editor"  pops up as I type. 

Is there a workaround or a fix?

**Comment by itowlson** [comment]
That sounds pretty bad -- thanks for reporting it!  Are these files on the filesystem, or the JSON/YAML shown when you click a resource from the tree view?  Let us know and we'll investigate urgently.

**Comment by earlcoder** [comment]
@itowlson Its when you load in a resource. eg Set Cluster -> Configuration -> ConfigMaps -> Load.
The json loaded in to the editor can not be edited.

**Comment by itowlson** [comment]
@andxu @bnookala Does this relate to #166?  We still need to allow editing even if we want to avoid a save prompt when closing an unedited document.  Is there a workaround in the short term?

**Comment by andxu** [comment]
A not perfect solution is to save it as a json file in temporary directories.

**Comment by andxu** [comment]
Shall we create the file at the system temp folder like this:
![image](https://user-images.githubusercontent.com/17075863/39610320-04419ac8-4f82-11e8-8dee-6b4fe2fa1d4b.png)

**Comment by itowlson** [comment]
I don't think that will give a satisfactory experience if the user edits and saves the document.  They almost certainly want it in the project directory, not in the temp folder.

**Comment by andxu** [comment]
I am concerned about too many temp json files created in current project root folder, every time a click on the node will generate one because the json is updated time to time.

**Comment by andxu** [comment]
I have tested new vscode(1.23.0) on mac/windows/Ubuntu, the save prompt disappears on untitled file, so I will revert my changes to archive your three ideas:

> Close the tab without getting a save prompt (and with no file being created in the project directory).
Immediately save the tab and have it default to the project directory and a sensible file name.
Edit the tab, then save and have it default to the project directory and a sensible file name.

**Comment by andxu** [comment]
Sorry, new vscode will not open save as prompt in development mode, so ignore above message.

**Comment by itowlson** [comment]
The proposed workaround using "Save As..." doesn't work for me.  Save As doesn't bring up a prompt and I still can't edit the document.  This feels like a significant pain point as the 'I want to load this resource in order to work on it' workflow is completely blocked.  If we can't fix it or work around it, then maybe we need to revert this change.  It may be annoying to have to dismiss the save prompt, but I'd rather have an annoyance than a total block.  What are our options here @andxu?

**Comment by itowlson** [comment]
`Kubernetes > Load` command is broken too.

**Comment by andxu** [comment]
@itowlson Sure, I will create the PR soon.

**Comment by bnookala** [comment]
Leaving this issue open as a tracking issue for when we can figure out how to properly solve this. @itowlson's comment above: https://github.com/Azure/vscode-kubernetes-tools/issues/200#issuecomment-386490299 has the necessary action items.

**Comment by itowlson** [comment]
Related discussion / VS Code feature request(s) here: https://github.com/Microsoft/vscode/issues/10547.  Not quite the same, but may be worth mining for possible workarounds.

**Comment by earlcoder** [comment]
Thanks guys, problem solved in v0.1.9

**Comment by itowlson** [comment]
I had a quick play with the VS Code 1.23 `FileSystemProvider` interface to see if we could virtualise these temp documents so they landed as 'clean' and without touching the disk, but could still be edited and saved to the local filesystem.  It looks plausible - probably going to have some warts (he says, having experimented with it for like _a whole half an hour_), but possibly good enough...

**Comment by bnookala** [comment]
@itowlson could we perhaps serve some kind of nonse witht he file that allows us to bypass caches?

**Comment by itowlson** [comment]
@bnookala Oh, this was in the context of VS Code caching the _extension_ when doing an install from VSIX without changing the version number.  It's not a data caching issue, nor a production issue for the extension.  #famouslastwords
