### ISSUE TITLE
Feature request: support multi-container pods

### ISSUE THREAD

**Issue by mhindery** [Azure/vscode-kubernetes-tools#203]
When running multi-container pods, the pod operations don't all work well. Starting a terminal in the pod defaults to one of the containers and happens to work if that's the one you need. Viewing logs doesn't work as it requires specifying a container name. You can repeat the failed command it executed with the container name option added to it, but it's not a great UX.

Multi-container pods are pretty frequently used having sidecars for db connections or things like Envoy. Could the pod have an additional drilldown per container?

**Comment by bnookala** [comment]
We'll need to add a `Container` tree view node under Pods that represent each container. 

- Selecting a container should be a no-op, and should not open a vscode window describing the container, since there's nothing to describe at that level. 
- Operations that should appear on the container context menu:
    1. exec
    2. logs
    3. port-forward
    4. attach

**Comment by itowlson** [comment]
We also need to be able to prompt for a container when someone issues one of these commands from the palette and selects a pod with multiple containers.  Working on this now.

**Comment by itowlson** [comment]
@bnookala Can you confirm if container support is required for port-forward?  `kubectl port-forward --help` doesn't list a container option.

**Comment by bnookala** [comment]
@itowlson ah you're right - port-forward is a pod level command (via https://kubernetes.io/docs/reference/kubectl/overview/#operations)
