### ISSUE TITLE
Extension should also read from KUBERNETES_CONFIG env var

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#205]
See: https://twitter.com/KevinHoffman/status/992032156603084800?s=20

**Comment by itowlson** [comment]
Additional control is in #206, for scenarios where KUBECONFIG is not picked up (the original poster linked in the issue seems to have hit this because he has to launch from the Mac dock and so can't set up a KUBECONFIG in the shell first) or to override KUBECONFIG on a temporary or project basis.

**Comment by bnookala** [comment]
Closing this issue as a duplicate of #69.

**Comment by itowlson** [comment]
Fixed via #206.
