### ISSUE TITLE
Duplicate file contents being loaded into editor v0.1.9

### ISSUE THREAD

**Issue by earlcoder** [Azure/vscode-kubernetes-tools#210]
If you open a cluster and click something like ingress->ingress_file , then click ingress_file again it will load duplicate contents in to the editor for as many times as you click it.
This happens to any editable file.

**Comment by itowlson** [comment]
Fix merged (#211) - will be included in 0.1.10.  Thanks for flagging this!

**Comment by earlcoder** [comment]
Thanks guys
