### ISSUE TITLE
Display object descriptions as yaml instead of json

### ISSUE THREAD

**Issue by mhindery** [Azure/vscode-kubernetes-tools#212]
Can a setting be added to show objects descriptions as yaml instead of json? We're using yaml everywhere, and I'd like to see it here as well for consistency.

**Comment by bnookala** [comment]
Should be fairly simple to do. I'll add a configuration option.

**Comment by itowlson** [comment]
Thinking-out-loud question: I wonder if YAML should be the default?  I suspect Brendan's original extension used JSON because VS Code provides better editing tools for JSON, but YAML seems to be idiomatic for Kubernetes...

**Comment by bnookala** [comment]
@itowlson yeah, I'm considering the same. We do validation against the YAML specs but not the JSON specs, right? Wouldn't be opposed to switching the default here to YAML here either.
