### ISSUE TITLE
Default to yaml when editing resources

### ISSUE THREAD

**Issue by Stono** [Azure/vscode-kubernetes-tools#220]
Hey, 
I might be being really silly, but i can't see how to change this (if at all possible).

The default editor seems to pull in json format, is there a way to get it to allow me to edit the resources in yaml?

Ta
Karl

PS.  Awesome extension

**Comment by itowlson** [comment]
Hi Karl - good news - @bnookala already has your back.  https://github.com/Azure/vscode-kubernetes-tools/pull/213

This will be included in the next release and YAML will become the default with the option to override to JSON via config.  Please let us know if you have any feedback on this feature!
