### ISSUE TITLE
kubeconfig handling

### ISSUE THREAD

**Issue by tlynchpin** [Azure/vscode-kubernetes-tools#221]
KUBECONFIG is set to a list of config files in powershell profile so that it is defined in powershell external to vscode as well as vscode Integrated Powershell Console and vscode regular powershell terminal. `kubectl config get-contexts` in all of those three powershell contexts show the clusters from all of the config files. This is expected behavior. 

The plugin sidebar shows only the clusters defined in ~/.kube/config.

- create cluster1.config and cluster2.config in ~/.kube
- set KUBECONFIG in powershell profile:
%USERPROFILE%\WindowsPowerShell\profile.ps1 :
`$Env:KUBECONFIG=(get-childitem $env:USERPROFILE/.kube/*config) -join ";"`
- observe both clusters in `kubectl config get-contexts` in powershell outside of vscode and vscode Powershell Integrated Console
- observe clusters do not appear in plugin sidebar

**Comment by itowlson** [comment]
Hi Tim - thanks for reporting this.  The extension just launches `kubectl`, so it should pick up KUBECONFIG from its parent environment and the spawned `kubectl` should inherit that.  You describe that you're setting KUBECONFIG in your PowerShell profile: are you launching VS Code from a PowerShell session where that environment variable is set, or are you launching it from Explorer?  If the latter, could you try running `code` from the PowerShell command line?

If launching Code from the PS session doesn't help, could you try dumping the value of KUBECONFIG in the VS Code integrated terminal and let us know if it's what you expect?  Thanks!

**Comment by tlynchpin** [comment]
Ok I see, that makes sense, the environment of code where the extension
runs won't have it set if it is launched from start menu, but the
powershells that code spawns will have it set because they will run the
profile.

I'll check it out.
