### ISSUE TITLE
{{ .Release.* }} and {{ .Values.* }} not validated as correct when template is not in 'templates' directory

### ISSUE THREAD

**Issue by plkokanov** [Azure/vscode-kubernetes-tools#225]
When using a template which is not directly under a directory named "templates" `{{ .Release.* }}` and `{{ .Values.* }}` are not validated as correct.

<img width="236" alt="screen shot 2018-05-30 at 23 09 45" src="https://user-images.githubusercontent.com/35485709/40745191-7c71a5be-645f-11e8-8194-ae06892912bb.png">

<img width="297" alt="screen shot 2018-05-30 at 23 12 17" src="https://user-images.githubusercontent.com/35485709/40745185-76ebf9a0-645f-11e8-9145-ee395b654731.png">

**Comment by itowlson** [comment]
cc @andxu @testforstephen

**Comment by itowlson** [comment]
It looks like the extension defines a 'helm-template' file type.  We can't distinguish this from the 'YAML' file type on file extension or first line alone, so we try to infer it from the `templates` file path.

As a workaround, could you try clicking on the file type 'YAML' on the status bar (towards the right hand end, next to the smiley face icon), and selecting 'helm-template' in the drop down?  Unfortunately this selection doesn't seem to persist, so it's not suitable as a long term fix...

**Comment by itowlson** [comment]
A workaround that persists (but is a bit more effort):

* Open your workspace settings (`Ctrl+,` or `File > Preferences > Settings`)
* In the Workspace Settings tab, add the following entry:

```
    "files.associations": {
        "**/my-template1/*.yaml": "helm"
    }
```

* Save the settings and re-open the template file.

**Comment by plkokanov** [comment]
Thanks @itowlson the workaround fixed my issues.
