### ISSUE TITLE
Error Creating cluster

### ISSUE THREAD

**Issue by josephglaspie** [Azure/vscode-kubernetes-tools#229]
When attempting to create a new cluster I hit the following error and any attempts to create an SSH key seem to be tied to creating a new VM in Azure. I have already authenticated with az login
```
Error creating cluster

An error occurred while creating the cluster.
Details
ERROR: An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you
```
Thanks for the help!!

**Comment by josephglaspie** [comment]
Hey itowlson, thanks for the quick reply. 

- Same issue with both ACS and AKS
- macOS High Sierra v10.13.4
-```ls $HOME/.ssh
known_hosts```

**Comment by itowlson** [comment]
Okay, we should be detecting that you don't have the expected SSH keys and warning about that so you can create them first (or adding `--generate-ssh-keys`, but I'm not sure what happens to the SSH keys in that case).  I'll take a look.  Thanks!

**Comment by itowlson** [comment]
Pfft, when I read the docs properly, `--generate-ssh-keys` only generates new keys if there aren't existing ones, so we should provide that argument unconditionally.  TIL.
