### ISSUE TITLE
Feature Request: Ability to Follow/Tail Logs

### ISSUE THREAD

**Issue by shreyu86** [Azure/vscode-kubernetes-tools#235]
Currently the extension prints all the log entries for selected pod, it would be great to be able to follow/tail logs.

**Comment by bnookala** [comment]
Suggesting `Kubernetes: follow logs` (additional behavior) vs. `Kubernetes show logs` (existing behavior)

**Comment by shreyu86** [comment]
Sounds good. I might attempt to get an PR out for this soon.

-Shreyas

**Comment by shreyu86** [comment]
Oops sorry didn't see it was assigned to @bnookala already.

**Comment by bnookala** [comment]
@shreyu86 all yours now :)

**Comment by veonua** [comment]
the tail log is not implemented. so follow logs downloads dozens of MB of log
