### ISSUE TITLE
kubeconfig.ts does not respect kubeconfig setting or environment variable

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#242]
From `kubeconfig.ts`:

```
export function readKubectlConfig(): Promise<KubeConfig> {
    return new Promise((resolve, reject) => {
        const kubeConfig = shell.combinePath(shell.home(), ".kube/config");
```

If the KUBECONFIG environment variable is set, or the `vs-kubernetes.kubeconfig` configuration setting is present, then we should probably be using that config file instead of the default one.

**Comment by brendandburns** [comment]
This file has been removed and this code now uses the official javascript/typescript client library which respects these variables.
