### ISSUE TITLE
Add Draft apps to cluster tree view

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#246]
Probably with an option to hide it for users of other tools who don't want Draft taking up valuable real estate.

**Comment by bnookala** [comment]
@itowlson should this make use of the extensibility api added by #179?

**Comment by itowlson** [comment]
Draft doesn't provide a list command, but we can do a `helm list` and filter for the presence of `metadata.labels.draft`.  But it looks like this will need to be done client-side as `helm list` doesn't have a selector option.

**Comment by itowlson** [comment]
Thought: rather than having a separate list of Draft apps (since the cluster has no notion of this, could indicate that a Helm release is Draft-managed via icon and tooltip?

**Comment by itowlson** [comment]
Hmm, the Draft metadata label comes from the deployment, not from the Helm list.  This would require multiple tool invocations making multiple network calls which could get quite slow.  So yeah nah.
