### ISSUE TITLE
Add an explorer for Helm chart repos (and Draft pack repos?)

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#247]
These are workspace side not cluster side so not in the cluster tree view,

**Comment by bnookala** [comment]
@itowlson I imagine this could get noisy if there are a lot of helm charts/draft pack repos in the added repository.

**Comment by bacongobbler** [comment]
A helm repository explorer was introduced in #317, and Draft is being removed in #876 I think this can be closed.
