### ISSUE TITLE
Can't diff - the open document is not a Kubernetes resource

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#248]
Build: 4631

Repro steps:

1. F1, open the command palette
2. Executing command "Kubernetes: Apply" or command "Kubernetes: Diff" 

Result:
Pop up an error as below:
![image](https://user-images.githubusercontent.com/28860891/41846923-e36c87f2-78aa-11e8-88c4-98c63bfc8b79.png)

**Comment by bnookala** [comment]
@sallyur would you mind sharing what's the open document contains? There are a number of commands that will only perform their actions if the currently selected/open document contains the resource defined in yaml.

**Comment by itowlson** [comment]
Was there a document open?  Was the open document a Kubernetes resource?

**Comment by bnookala** [comment]
@sallyur sorry... I'm a little bit confused here. Where are you getting Build 4631 from? Is this built from source?

**Comment by itowlson** [comment]
It looks like this occurs because you've deleted the `metadata.namespace` field out of the YAML file.  Can you try restoring the namespace and see if it works again please?

**Comment by sallyur** [comment]
After I adding metadata.namespace field out of the YAML file, it works fine.
