### ISSUE TITLE
Kubernetes Apply fails when Resources are loaded

### ISSUE THREAD

**Issue by kameshsampath** [Azure/vscode-kubernetes-tools#253]
When we click the Kubernetes resource on the Kube Explorer tree, we get a file opened in the editor like `/pod-someid.yaml`, this resource file does not have a filepath as its virtual file. Because of that few of the extension commands fails such as 
- kubernetes Apply https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/extension.ts#L537-L541
- kubernetes diff https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/extension.ts#L1399

I solved the Kubernetes Run via https://github.com/kameshsampath/vscode-kubernetes-tools/blob/istio/src/extension.ts#L547-L566

**Comment by bnookala** [comment]
@kameshsampath I suspect that Ivan's PR: https://github.com/Azure/vscode-kubernetes-tools/pull/236 will fix the issues you noted above.

**Comment by kameshsampath** [comment]
yes @bnookala, checked @itowlson  PR #236, it seem to have fixed that will wait for the update
