### ISSUE TITLE
Kubernetes: set namespace command

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#265]
We currently have a way to change the current namespace from the explorer. We should expose this as a way to change the namespace from the command palette:

`Kubernetes: Set Namespace`

**Comment by itowlson** [comment]
@kameshsampath Thanks for the PR. Regarding formatting, we haven't historically had a standard but are gradually working one in via tslint and editorconfig.  Your formatting changes look good, but having them in the same PR as functional changes muddies the water a bit - would you have the time to send them as a separate PR please?

**Comment by itowlson** [comment]
Fixed via #270.
