### ISSUE TITLE
Pod status icon in tree view always shows stopped

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#272]
I've noticed that in master the pod status always seems to be showing red for me.  If I do a `kubectl get pods` then they show as running but the icon in the tree view is red.  @shreyu86 do you have any idea what might be going on?  Wondering if something when awry when changing the column-based status parsing to JSON-based perhaps?  If you don't have time to look into it then let me know and I'll dig deeper.

**Comment by shreyu86** [comment]
I will check this first thing if it is possible can you share the pod JSON output?

**Comment by bnookala** [comment]
@itowlson to my knowledge, the parsing for the status is still using columns.

**Comment by shreyu86** [comment]
@bnookala +1, if the columns is causing any issues might have some time this week to checkout the JSON route.

**Comment by itowlson** [comment]
@shreyu86 Yes, that's right.  For some reason I convinced myself that the `Workloads > Pods` icons were also red, but trying now I can see I was wrong about that.  Sorry for the misleading bug report and thanks for diagnosing it correctly.  If you can fix the `Nodes` tree that would be great - if #271 would help as a foundation for that then we will hopefully merge that soon.  Thank you!

**Comment by shreyu86** [comment]
@itowlson thanks for confirming. Nodes uses [slightly different logic](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/explorer.ts#L239) than `Workload-> Pods` to list pods and filter them. Thinking about a way in which both could fetch info regarding the running state of the pod. Let me know if you have any pointers on this.

**Comment by bnookala** [comment]
Fixed by #277 and #278.
