### ISSUE TITLE
Draft up watch not working?

### ISSUE THREAD

**Issue by bjornmagnusson** [Azure/vscode-kubernetes-tools#284]
How is the file changes watch for Draft supposed to work?
Can´t get the file watching for the Draft Up to work. Is there any specific config needed?
Using the latest version (0.1.10) of this extension, and the latest released version (0.15.0) of Draft.
Manual draft up in command line and via VSCode works fine.

Language: Same result for both NodeJS and Java.

Expected behaviour: Draft up should re-deploy the application on changes to one of the main application files.

Observed behaviour: nothing happens, must re-deploy by manually re-triggering Draft Up

**Comment by itowlson** [comment]
I think Draft changed its default to non-watching.  The extension doesn't pass the `watch` flag so it inherits that default.  At the moment you need to put `watch = true` into the `draft.toml` file to enable watching behaviour.

VS Code doesn't provide great UI for command options, so if we want to support watching we will probably have to add a new "Draft: Up with Watch" command for it (great naming Ivan, you'll go far).

**Comment by bjornmagnusson** [comment]
Fully aware of that Draft team has dropped this and the existing watch flag. However, from my understanding from the core maintainers in Draft, the responsibility of watch for file changing and reploying will be in the IDE and its plugin (like this one). I was under the impression that it was solved in this one (maybe not?)
I do believe that the `watch` functionality is crucial for the developer experience.
Personally I don´t want a "special" draft up for watch, this should be included as default behaviour.

From the README.... `Draft: Up - Runs Draft to watch the current folder and keep the cluster in sync with it`

Perhaps @bacongobbler  or @michelleN could fill in information regarding the `watch` feature, what the direction really is.

**Comment by bnookala** [comment]
@bjornmagnusson I should note that the README is a bit out of date... there's an open issue to fast forward it back to our current reality.

**Comment by bjornmagnusson** [comment]
Up-to-date README definitely help :)

**Comment by radu-matei** [comment]
As @itowlson mentioned, the `watch` functionality in the Draft CLI is not working at the moment, so watching is left to the IDE/code editor.

The issue right now (to be fully described in a new issue) is with the way the debugging session is currently implemented in this extension, often messing with the native VS Code file watcher, resulting in inconsistencies.

We are aware of this issue and hope to fix it ASAP - thanks for flagging it again, @bjornmagnusson!

**Comment by bjornmagnusson** [comment]
Thanks for the update, looking forward to seeing it in action.

**Comment by daneroo** [comment]
Any updates on this? Last comment is more than 6 months old.
Perhaps moving to [skaffold](https://github.com/GoogleContainerTools/skaffold) would be a better plan for **watching**, since this issue seems to have gone stale.

**Comment by squillace** [comment]
Sorry @daneroo -- it sucks having a great project and having not enough devs. I use this feature all the time, so I'll figure out how to fix it.

**Comment by daneroo** [comment]
@squillace  Thanks for looking into it. I know what you mean about being short on devs. I really appreciate the work you and all the contributors have done on this project.

**Comment by bacongobbler** [comment]
Given that draft is now an archived project, we should remove it from the extension.

**Comment by squillace** [comment]
Agree. @daneroo we say this with regret. BUT... there may  be something coming for this extension to replace it. #fingerscrossed
