### ISSUE TITLE
Incompatibility with DevOps project-generated Node.js code

### ISSUE THREAD

**Issue by bradygmsft** [Azure/vscode-kubernetes-tools#287]
Node.js code created into the [Azure DevOps project](https://azure.microsoft.com/en-us/features/devops-projects/) sample app includes helm charts, but fails to include the draft files this method seems to require. 

Is it possible the extension could drop these in? Or, is it possible that this issue could be routed to the team who create the Node.js template project for consideration? If they own the files that are dropped, perhaps they could drop in these required draft files, thereby enabling out-of-the-box debugging for devops project-created code. 

https://github.com/Azure/vscode-kubernetes-tools/blob/a63c2c5a17703cc8524ccb88589d9572d5c260b3/src/draft/draft.ts#L111

Thanks for the great extension. Loving finding new features in it that make developing with Kubernetes great.

**Comment by bnookala** [comment]
@bradygmsft can you do a `draft create` in the project?

**Comment by itowlson** [comment]
Running the **Draft: Create** on the project _should_ fill this in pretty accurately, though it's still a manual step.  Unfortunately, I don't think the k8s extension can really recognise an Azure DevOps project and automatically inject the Draft files.  I'll reach out to the owners of the Node.js template in Azure DevOps and see if they're willing/able to add Draft support.  Thanks for flagging this!

**Comment by bradygmsft** [comment]
No problem! I was in a thread with one of the team members and mentioned it today, so I'm pushing from my side. I think all these features are great, and that we should think of a way to pre-wire some of them up so developers can go "new DevOps project, clone, debug in the cluster." Tall order, but with some collaboration I think it's a matter of time.

**Comment by itowlson** [comment]
I heard back from Atul on the DevOps team.  He used Draft to generate the Helm charts but excluded the Draft manifest.  He's tracking it as a bug on the DevOps side and will get it fixed there.  Thanks @bradygmsft for letting them know too - and agree on getting that seamless experience!

**Comment by bradygmsft** [comment]
oh @itowlson that's **fantastic** news. and my pleasure. the experience is so, so important and so, so close, so i feel every little report like this can add to a better experience for our users.

**Comment by squillace** [comment]
Now that I'm back I can follow up with @azooinmyluggage and get it all figured out. It's a point in time thing, as the draft issue https://github.com/Azure/draft/issues/219 will enable you to just look at any compatible code directory with a helm chart and get a new draft.toml file. 

in the very short term, you can make it work by adding one of your own and then ensuring (I believe we ensured this worked properly, but check us!) that the chart is modified per the instructions here: https://github.com/Azure/draft/issues/545. If that doesn't work, let me know.

In the meanwhile, we'll see about synchronizing the getting started DevOps/DevSpaces apps with Draft requirements; we don't want non-Drafters to be confused by draft files, but we also want drafters to work quickly and easily with them.

**Comment by bradygmsft** [comment]
Thanks for the response, @squillace. And to @azooinmyluggage - you have my new favorite GitHub alias. Of all the aliases. Period.
