### ISSUE TITLE
[Win] Chart Preview Failed template call

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#289]
Build:4651

F1, execute command "Helm: preview template"

![image](https://user-images.githubusercontent.com/28860891/42510204-c9ecb7d4-8480-11e8-9c75-5b7792917f49.png)

But actual there is deployment.yaml in the path.

**Comment by itowlson** [comment]
I tried this with the latest Helm stable version (2.9.1) and I get the 'template produced no output' message rather than this error.  Are you in a workspace (as opposed to having a loose file)?  Does it have a single root?

**Comment by sallyur** [comment]
Repro steps:

1. Open a workspace
2. Create a Helm chart under this workspace
3. Open the deployment.yaml under the chart/templates
4. F1, execute command "Helm: preview template"

I run helm template <chart_path> --execute templates\deployment.yaml from the command line will let me open the deployment.yaml file.
My Helm client version is "v2.8+unreleased".

**Comment by sallyur** [comment]
After I installing the helm 2.9.1 also  get the 'template produced no output' message.

**Comment by itowlson** [comment]
Thanks.  I still can't reproduce this (I get 'template produced no output', just as you do with 2.9.1), and a `v2.8+unreleased` version is hard to replicate.  Can you provide a download link for the Helm version you're using please?

**Comment by sallyur** [comment]
Helm v2.8+unreleased zip download link: https://kubernetes-helm.storage.googleapis.com/helm-canary-windows-amd64.zip

**Comment by ejsmith** [comment]
I have the same problem saying 'template produced no output' message. Same templates on OSX work correctly.

**Comment by itowlson** [comment]
@ejsmith 'Template produced no output' (see also #241) is symptomatic of a known Helm for Windows bug which will be fixed by https://github.com/helm/helm/pull/4305.  I've pinged the Helm maintainers to try to get this into a Helm release; unfortunately there's nothing the extension can do to work around it.  I'm sorry about this.

**Comment by brendandburns** [comment]
Closing as obsolete.
