### ISSUE TITLE
Don't have the option "Set as current cluster"

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#290]
Build: 4651

1. Open the Kubernetes: cluster explorer
2. Right click the "minikube" cluster

Don't have the option "Set as current cluster"
![image](https://user-images.githubusercontent.com/28860891/42510573-e546b5f6-8481-11e8-869f-cc25843581c5.png)

But right click other cluster have the option "Set as current cluster"

**Comment by bnookala** [comment]
Seems like a configuration issue with package.json. I'll get a fix for this.
