### ISSUE TITLE
No response when execute command "Kubernetes: Follow Logs" on Mac

### ISSUE THREAD

**Issue by JanusWu** [Azure/vscode-kubernetes-tools#292]
Build: [#4651](https://vscjavaci.cloudapp.net/job/vscode-k8s-tools.vsix/4651/Azure/)

When execute the command "Kubernetes: Follow Logs" on Mac, don't get any response.
![image](https://user-images.githubusercontent.com/17060520/42511121-9a583a22-8483-11e8-8721-3a4c7928c1fd.png)

**Comment by bnookala** [comment]
@JanusWu you should only see log lines if the container is writing logs to stdout
