### ISSUE TITLE
Show starting and stopping minikube progress indicators

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#293]

**Comment by itowlson** [comment]
Can you expand on this a little please?  What are you envisaging and do you feel the Minikube scenario justifies the scarce status bar real estate?

**Comment by sallyur** [comment]
I think should have indicate in states bar telling user the minikube is starting rather than no response.

**Comment by itowlson** [comment]
Oh, sorry, I thought you were wanting start and stop _buttons_ on the status bar.  The word 'process' is a bit overloaded and there was no description.  Thanks for the clarification!
