### ISSUE TITLE
Display additional resource types in tree

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#30]
Original request from @doggy8088: https://github.com/brendandburns/vs-kubernetes/issues/41

    There are 4 types now ( Deployments, Jobs, Pods, Services ). Would you like to add support for ConfigMaps?

We should more broadly review what to put in the tree view, and whether there are specific editing experiences what would be useful for particular resources such as ConfigMaps.

**Comment by kyliel** [comment]
@testforstephen , could we add configmaps in the tree? Thanks.

**Comment by kyliel** [comment]
Config 
 - Config Maps
 - Secrets

**Comment by itowlson** [comment]
Closed via #47.
