### ISSUE TITLE
Add ability to customize minikube start command

### ISSUE THREAD

**Issue by detiber** [Azure/vscode-kubernetes-tools#305]
The minikube start command is currently hardcoded, being able to override it would help in cases where VirtualBox is not installed or users would prefer to customize the minikube installation (such as using an alternative container runtime).

**Comment by itowlson** [comment]
cc @brendandburns

**Comment by detiber** [comment]
I found that this limitation can be worked around using the minikube config, running `minikube config set vm-driver kvm2` allows this extension to be able to create a minikube cluster.

**Comment by itowlson** [comment]
Fixed by #330.
