### ISSUE TITLE
Adding possibility to use KVM driver when starting Minikube

### ISSUE THREAD

**Issue by ppatierno** [Azure/vscode-kubernetes-tools#314]
On my Fedora machine, I prefer to use `minukube` with the KVM driver (with `--vm-driver=kvm` option) and not using VirtualBox.
This extension doesn't provide the possibility to chose a different vm driver.
It could be really useful having that. Maybe a configuration step when Minikube is selected in order to specify VirtualBox or the KVM driver (so that the command shell will be `minukube start --vm-driver=kvm`).

**Comment by itowlson** [comment]
This might be a good one for your "no creation options... yet" page @brendandburns, though we need to clarify how the Minikube Create Cluster wizard and the Start Minikube command on the tree view relate to each other...

**Comment by ppatierno** [comment]
@itowlson @brendandburns that's cool thanks! When will the new release come out with this feature? :-)

**Comment by itowlson** [comment]
I'm thinking of doing a release this week or early next week.  But I should warn you that 'Ivan thinking about a release' has been known to suffer up to 2 weeks' lag before 'Ivan actually managing to get a release out', so please don't rely on it -- but do nag me if nothing is out by this time next week.

**Comment by itowlson** [comment]
New release is out now.  Please let us know if you run into any problems, or if you have suggestions for more enhancements.  Thanks!
