### ISSUE TITLE
Show/Follow Logs Commands Throw JSONPath Parse Error

### ISSUE THREAD

**Issue by runewake2** [Azure/vscode-kubernetes-tools#315]
Attempting to follow or show a pods logs either from the Command Menu or from the Sidebar menu is throwing an exception related to JSON parsing:

```
Failed to get containers in pod: error: error parsing jsonpath {'NAME\tIMAGE\n'}{range .spec.containers[*]}{.name}{'\t'}{.image}{'\n'}{end}, unrecognized character in action: U+0027 '''
```

This prevents all attempts to view logs using this extensions tools. Other commands seem to function properly.

I am encountering this when working with namespaced pods as well as in minikube. I am working with a Kubernetes server on version **1.6** in both instances. Is this to old for this tool? In prior releases of this tool showing logs was functioning as expected and I was able to see my pods logs.

**Comment by itowlson** [comment]
That's nasty -- sorry it's hit you.  Just trying this out and it seems to be working for me.  I'm on 1.7, but I don't see why 1.6 should make a difference, and I don't think this code has changed from previous releases - but I will take a look.

Couple of questions to help us reproduce the problem:

* Are you using the latest release, or building yourself from `master`?
* Are you on Windows, Mac or Linux?

Thanks!

**Comment by itowlson** [comment]
Could you also try, on your command line, running the following command:

`kubectl get pod/` _any-of-your-pods_ `-o jsonpath="{'NAME\tIMAGE\n'}{range .spec.containers[*]}{.name}{'\t'}{.image}{'\n'}{end}"`

and let me know if you get the jsonpath parsing error please?  If you are on Mac or Linux, does it make a difference if you remove the double-quotes around the jsonpath string?  Thanks!

**Comment by runewake2** [comment]
I'm running the latest release from the VS Code Extension hub/library/thing. :)

* Removing the quotes throws an: `error: error parsing jsonpath {NAME\tIMAGE\n}{range, unclosed action`
* That command running on my console throws the same error as my original post.
* I have encountered this error on pods with multiple containers and ones with single containers per pod.
* I am able to follow logs from the terminal using `kubectl logs -f my-pod-name -c my-pods-container` successfully and able to use the kubernetes api to watch using the python, c# and javascript libraries that are available.
* This is running on a mac with `kubectl` client version 1.7

Let me know if you need any other information.

**Comment by itowlson** [comment]
Thanks for the info.  I'll have another crack at a repro.

To be clear, the error _isn't_ in the log retrieval - it's occurring when we try to get the list of containers in the pod, so that we can prompt you if there is more than one.  (And that's why it happens even if there's only one pod, because we don't know that until we've listed out the containers.)

**Comment by runewake2** [comment]
Looks like its an issue with the quotes used. If I switch the use of `'` and `"` to make this:

```bash
kubectl get po [MY-POD-NAME] -o jsonpath='{"NAME\tIMAGE\n"}{range .spec.containers[*]}{.name}{"\t"}{.image}{"\n"}{end}'
```

I get an output of:

```
NAME        IMAGE
container1       some-image-for-container1:some.version
container2       some-image-for-container2:some.version
```

I assume that is the expected output from this? ¯\\\_(ツ)\_/¯


I'm using Bash on a Mac (`3.2.57(1)-release`).

**Comment by itowlson** [comment]
Okay, it looks like the existing quoting is the only form that works on Windows, and the switched quoting is the only form that works on Mac, and both work on Linux!  So we'll keep the existing quoting on Windows, but used the switched quoting elsewhere.  #smdh

Thanks for flagging this.  I don't know why it suddenly changed in the most recent version, but appreciate you taking the time to report it and to track down the problem.  A fix is on the way!
