### ISSUE TITLE
Feature: Context menu for chart explorer

### ISSUE THREAD

**Issue by technosophos** [Azure/vscode-kubernetes-tools#323]
With the new chart repository explorer view, here are a few things that I think would be useful to have in a context menu hanging off of a chart version:

- `install`: Install that chart
- `dependencies`: Run `helm dep list` on the chart
- `inspect`: Run a `helm inspect` (possibly could be a submenu with `helm inspect values` and `helm inspect chart`. NB: Inspecting _values_ is a fairly common task for people during dev. Inspecting chart YAML is less common
- `fetch`: Do a `helm fetch` (into the local project?) and then unpack the chart for editing. I'm thinking of this as a way to start with an existing chart and start writing/forking your own.

**Comment by itowlson** [comment]
For the `install` command, are there any important options to offer the user (bearing in mind that VS Code has limited UI and we want to keep the experience smooth).  I'm specifically thinking of whether users frequently need to override values (the `-f` or `--set` flag) or the name (the `-n` flag).

**Comment by itowlson** [comment]
I'm not sure the `dependencies` command can work as you suggest.  When I run `helm dep list stable/aerospike` (to pick a repo chart at random) I get `Error: GetFileAttributesEx C:\Users\itowlson\stable\aerospike: The system cannot find the path specified.`  Is this a Helm for Windows issue, or do we need to download the chart first?  (The docs imply the latter: "This can take chart archives and chart directories as input" but no mention of chart repo references.)

**Comment by itowlson** [comment]
The `fetch` use case looks like it would be accomplished by `helm fetch <chart_ref> --untar -d <project_dir>`.  This would create a chart directory named for the chart, e.g. `myproject/aerospike`, containing Chart.yaml, the templates, and all the other goodness.
