### ISSUE TITLE
Add `Delete now` entry to Pod context menu

### ISSUE THREAD

**Issue by snobu** [Azure/vscode-kubernetes-tools#326]
Please add a `Delete now` entry to Pod context menu, here &mdash;

![image](https://user-images.githubusercontent.com/6472374/43467037-837b96ac-94e9-11e8-8c47-b11fabaccfa7.png)

Sometimes a pod isn't easily convinced to exit or the grace period is set too high, this comes in handy to convince the pod to give up in an instant (`kubectl delete pod pod_name --now` has grace period = 1).

**Comment by snobu** [comment]
Oh wow, appreciate the blazing speed here! This one time i opened an issue with AWS tooling took nine weeks for someone to add a label! Thanks!!

**Comment by ubikusss** [comment]
No worries! I am sorry to hear about your experience!
