### ISSUE TITLE
Kubernetes explain should work for resources loaded from the cluster

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#329]
As noted by @squillace, the current implementation of the Explain API does not activate when viewing resources loaded from the cluster, and only works when viewing resources loaded from the filesystem.

**Comment by brendandburns** [comment]
I _think_ that this is something wiggy with the tooltip API (or maybe just our implementation of a tooltip provider)

**Comment by brendandburns** [comment]
Closed by #370
