### ISSUE TITLE
[Configure from cluster] Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by testforstephen** [Azure/vscode-kubernetes-tools#33]
Reproduce steps:
1. Use `create cluster` command to create an aks cluster in east-us.
2. Then invoke `configure from cluster` command to configure `kubectl` context. The configure command succeeded, but then call any `kubectl` command would get `Unable to connect to the server: net/http: TLS handshake timeout`.

The reason is that:
1. `create cluster` command doesn't wait for the creating operation to finish. 
2. Even though aks cluster is not fully ready, `configure from cluster` wizard still could list the newly created cluster and execute `az aks get-credentails` operation. But actually `kubectl` command would throw errors.

Current extension doesn't provide any tool to help the user to query if the cluster is fully ready.  The user needs to login to azure portal to view the status.

Expected:  `create cluster` to wait for the completion of the create. Or before executing `az aks get-credentails`, calling `az aks wait` to wait for the cluster to be ready.

**Comment by testforstephen** [comment]
Also found another issue. 

I use `kubectl config delete-xxx` command to delete previous failure credentials generated by `configure from cluster` , and then wait the aks cluster to be fully OK via checking azure portal, after that retry `configure from cluster` command. The credential is still not correct because of the same error `Unable to connect to the server: net/http: TLS handshake timeout`.

This seems like an azure bug.

**Comment by itowlson** [comment]
I don't really want Create Cluster to block on creation, though I guess we could leave the pane up monitoring it and add a "Your cluster is ready. Would you like to configure the extension to use this cluster?" step (which would be optional - they could still close the wizard at the 'started creating' stage).  Nor am I keen on 'configure' doing a wait which could be many minutes.  Agree though that we should detect whether the cluster is ready and not download credentials if it isn't.  I'll take a look - thanks!

**Comment by itowlson** [comment]
Well, joy. I can do an `az a{c|k}s wait --created` and that works fine, _but_ that does _not_ mean the cluster is ready for `az ... get-credentials`.  From heuristic testing at the command line, it takes another 30-60 seconds before `get-credentials` will work.  Fie!  Fortunately I'm not seeing the behaviour you cite where `kubectl` gets lumbered with a malformed credential, but I do feel wary of running `get-credentials` repeatedly in case that does happen... Will pick this up tomorrow...

**Comment by itowlson** [comment]
Grr, well, I have a fix for this, but it seems that _even when the cluster has allowed us to download credentials_, it's not guaranteed to be ready to receive requests using those credentials.  So if you do a create cluster, wait and configure the extension, and then refresh the tree view, you may still get the TLS handshake timeout error.

I don't think I can do much about this on the extension side.  Perhaps the RP shouldn't be reporting the provisioning state as succeeded until the cluster is a bit readier, but I'm not sure how it would tell...

**Comment by testforstephen** [comment]
Can we ask azure cli to do something about this issue?

**Comment by itowlson** [comment]
I'm not optimistic about solving the timing issue in the CLI.  It would require the CLI to retrieve and run `kubectl` which feels like an uncomfortable piece of coupling.  We would need to quantify the timing issue to justify the effort involved.  I suggest for now we just monitor this, and involve RP/CLI if we find ourselves or customers hitting it a lot.  Thoughts?

**Comment by itowlson** [comment]
Hmm, it can definitely take a good long while (a minute or so?).  This feels like a server side issue and not something we should make the CLI's problem...

**Comment by testforstephen** [comment]
This error is really easily reproducible. For me, i got this error for several times when i began to use the extension to create aks. If you were not telling me it's probably timing issue, i have no idea about what's happening and how to resolve it. 

From your findings, looks like we should report this issue to azure aks team and need their support.

**Comment by itowlson** [comment]
Maybe as an interim measure I could add some blurb to the 'credentials downloaded' message for new clusters along the lines of 'but give it a minute before trying to use them'.  **fie**

**Comment by itowlson** [comment]
AKS folks are tracking this issue and it should be fixed soon.  See e.g. https://github.com/Azure/AKS/issues/112.
