### ISSUE TITLE
Linter doesn't work on a multi object file

### ISSUE THREAD

**Issue by dnohales** [Azure/vscode-kubernetes-tools#359]
I was working with my YAML object files and previously I have every single object in a separated file and I recently noticed that for a "Deployment" object file I have the following linting warning:

```
One or more containers do not have resource limits - this could starve other processes
```

Before fixing that issue, I decided to refactor my object definition a bit and define more than one object in a single file if they are related. So now I have the same Deployment as before along with a Volume Claim and a Service, everything in the same file.

But then I noted that the linting warning doesn't show up for the Deployment, but it does show up if I delete the Service and Volume Claim from the file, leaving the Deployment alone.

So I suppose the linting code is not taking into account the possibility of having many objects definition per file.

Thanks!

**Comment by itowlson** [comment]
Thanks for flagging this - I'll take a look!

**Comment by itowlson** [comment]
Latest release should fix this - let me know if you still see problems.

**Comment by msolano00** [comment]
I still see this issue.

**Comment by lstocchi** [comment]
Reopening to investigate more on this. Maybe we broke something in the new releases?

**Comment by mukesh-p** [comment]
is there a way to hide/ignore the warning. It becomes very difficult to modify the file as every time we hover over the parts this warning pops up which makes it difficult to work with.

**Comment by lstocchi** [comment]
@mukesh-p are you referring to the `One or more containers do not have resource limits - this could starve other processes` message? Do you want to disable all linting warnings?

The issue here is different so maybe we can open a new issue. The problem is that this linting warning (and any other i guess) disappear when having multiple objects in the same file.

**Comment by ahoka** [comment]
> 
> 
> @mukesh-p are you referring to the `One or more containers do not have resource limits - this could starve other processes` message? Do you want to disable all linting warnings?
> 
> The issue here is different so maybe we can open a new issue. The problem is that this linting warning (and any other i guess) disappear when having multiple objects in the same file.

That would be great if there was a way to disable this warning. I don't want to enable cpu limits due to their non-intuitive behavior and having my half yaml file underlined in yellow degrades usability.
