### ISSUE TITLE
Helm: Insert Dependency not working on Windows

### ISSUE THREAD

**Issue by nphmuller** [Azure/vscode-kubernetes-tools#363]
I can't get the `Helm: Insert Dependency` command to work.
I've tried to run the command via the commands windows (Ctrl+Shift+P) and via the codelense popup (when applicable) at the following moments:
- No existing requirements.yaml file
- Existing but empty requirements.yaml file
- Existing requirements.yaml file with empty `dependencies:` array.
- Existing requirements.yaml file with other working dependency
- Existing requirements.yaml file with other working dependency and existing requirements.lock file.

All of the above resulted in no output in the output window.

I've also tried the update dependencies command, which worked great and showed output in the output window.

I'm on version 0.1.13 of the extension.

**Comment by itowlson** [comment]
cc @technosophos

**Comment by itowlson** [comment]
@nphmuller What operating system are you on?

**Comment by itowlson** [comment]
This command looks like it works in a slightly odd way (it dates back to the Before Time and may not have been polished) - it inserts the dependency information into the _current document_ like a snippet.  So I _think_ you would need to open `requirements.yaml`, position the cursor where you want to add the dependency, and _then_ issue the command.

_However_, there is also a bug on Windows where it won't work if neither `HOME` nor `HELM_HOME` is defined.  If you're on Windows, you can work around this by setting the `HOME` environment variable to be the same as your `USERPROFILE`.

I've got a fix for the Windows bug, and will work with @technosophos to figure out a smarter and more obvious behaviour in terms of inferring the `requirements.yaml` file etc.  Thanks for flagging this!

**Comment by nphmuller** [comment]
@itowlson Thanks for the quick response!

I'm on Windows, so the problem was indeed what you explained. Setting the HOME env var made the command work.

Although the command certainly could be smarter, I'm more than fine with the current behaviour. What threw me off was that no output was printed to the output window and nothing happened, so I wasn't sure if I was using the command wrong, or if it simply was not working.

Do you want me to keep this issue open? If so, should I change the issue to refer to the Windows bug, or to make the command smarter?

**Comment by itowlson** [comment]
Let's raise a separate issue for the command behaviour (I can do that and bring in the Helm folks to advise on UX), and I'll ship a PR with the Windows fix to close this one - that way we won't delay the fix while noodling on gold-plating the behaviour.  Thanks for being understanding!

**Comment by nphmuller** [comment]
Okay! I've updated the title.

**Comment by itowlson** [comment]
Latest release should fix the Windows issue (but leaves behaviour unchanged) - thanks for reporting it!
