### ISSUE TITLE
Host is not running

### ISSUE THREAD

**Issue by lxhmavis** [Azure/vscode-kubernetes-tools#365]
Build: 4688

Repro steps:
1. Run command 'minikube service list' In the terminal window, 
2. The result as below:
     
![image](https://user-images.githubusercontent.com/41565966/45356997-98ce3300-b5f7-11e8-87a6-4352c9a254d2.png)

The minikube service is running as usual.
![image](https://user-images.githubusercontent.com/41565966/45357235-45a8b000-b5f8-11e8-8387-e1121b1d76e1.png)
I consider that it is about the namespace is not correct, but I didn't change it by any operation, it is confused. How to specify the correct  namespace.

**Comment by itowlson** [comment]
cc @brendandburns

**Comment by sallyur** [comment]
1. This is not the reason for our plugin, this is the reason for the local minikube, our plugin just calls it.
2. I try to open vscode with administrator privileges and run minikube service list in vscode terminal window, it works fine. So I recommend close this bug.
