### ISSUE TITLE
Error getting status SyntaxError: unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#373]
Build: 4694
OS: Windows

Repro steps:

1. F1, open the command palette
2. Select "Kubernetes: Start minikube" or "Kubernetes: Stop minikube" or " Kubernetes: Minikube status"

Result:
Pop up an error window:
![image](https://user-images.githubusercontent.com/28860891/46010298-bd94d100-c0f4-11e8-8a07-b055545d5123.png)
Error in toggle developer tools:
![image](https://user-images.githubusercontent.com/28860891/46010333-d56c5500-c0f4-11e8-8da2-c02994d6c26b.png)

**Comment by itowlson** [comment]
cc @brendandburns

**Comment by brendandburns** [comment]
Closing as obsolete.
