### ISSUE TITLE
Debug attach: org.eclipse.jdi. TimeoutException

### ISSUE THREAD

**Issue by sallyur** [Azure/vscode-kubernetes-tools#375]
Build: 4694
OS: Windows

Repro steps:

1. F1, open the command palette
2. Select "Kubernetes: Debug (Attach)

Result:
![image](https://user-images.githubusercontent.com/28860891/46011516-ae178700-c0f8-11e8-855c-6835283e7ec5.png)

**Comment by itowlson** [comment]
Is this for a Java project?  Can you provide any more specifics?

**Comment by sallyur** [comment]
It is for a java project. I can stable repro yesterday, but can't repro today with same configuration. I guess maybe the reason for the network, closed.
