### ISSUE TITLE
Chart template preview gives Failed template call

### ISSUE THREAD

**Issue by erihanse** [Azure/vscode-kubernetes-tools#387]
Issue Type: <b>Bug</b>

When trying to preview a template, I get a duplicate in the the path. Am I using this feature wrong? I've tried to open different folders in vs code, but it reports the same path. 

> Chart Preview
> 
> Failed template call.Error: could not resolve template path: stat /home/erikah/ok/plattform/helm-charts/monocular/chart/monocular/monocular/templates/ingress.yaml: no such file or directory
> 
This is the hierarchy: 
``` 
➜  helm-charts tree monocular/chart
monocular/chart
└── monocular
    ├── Chart.yaml
    ├── README.md
    ├── requirements.lock
    ├── requirements.yaml
    ├── templates
    │   ├── chartsvc-deployment.yaml
    │   ├── chartsvc-service.yaml
    │   ├── _helpers.tpl
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   ├── prerender-deployment.yaml
    │   ├── prerender-service.yaml
    │   ├── repo-sync-cronjobs.yaml
    │   ├── repo-sync-jobs.yaml
    │   ├── ui-config.yaml
    │   ├── ui-deployment.yaml
    │   ├── ui-service.yaml
    │   └── ui-vhost.yaml
    └── values.yaml
``` 

Extension version: 0.1.14
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.12GB (12.89GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by erihanse** [comment]
Never mind, it seems like the problem disappeared when I disabled another extension, vscode-helm.

**Comment by itowlson** [comment]
Thanks for the update.  The `vscode-kubernetes-tools` extension incorporates `vscode-helm`.  @technosophos can we update `vscode-helm` please -- either hollow it out or at least update the readme.
