### ISSUE TITLE
Something changed in CI and now everything is terrible

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#395]
CI PR builds have been failing for a few days with:

```
ReferenceError: internalBinding is not defined
    at fs.js:25:1
...
The command "gulp tslint" exited with 1.
```

I re-ran the master and that (which previously passed) also failed with the same error.  This suggests something has changed in the CI environment and now no builds are passing.

I hate computers.

**Comment by itowlson** [comment]
The first failure, a few days ago, was different:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Not clear whether the the `internalBinding` error is related to this - you would hope Travis was stateless but that doesn't always seem to be the case.

**Comment by itowlson** [comment]
Looks like Travis is now running Node 11 whereas successful builds were done under Node 10.

cf. https://travis-ci.org/Azure/vscode-kubernetes-tools/jobs/444800374 (succeeded) vs. https://travis-ci.org/Azure/vscode-kubernetes-tools/jobs/446312678 (failed)

**Comment by inwardmovement** [comment]
Same here, with error:

```
gulp[4953]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8daaa0 node::Abort() [gulp]
 2: 0x8dab75  [gulp]
 3: 0x90e2f7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb5e71b  [gulp]
 5: 0xb606b2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0xf8f4e35be1d 
/home/travis/.travis/job_stages: line 104:  4953 Aborted                 (core dumped) gulp
The command "gulp" exited with 134.
```

Nailing down Node version didn't fixed it...

**Comment by itowlson** [comment]
Our CI appears still to be passing - is this for a local build of the extension?
