### ISSUE TITLE
Brigade support

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#4]
Need to scope this, but would be good to support the k8s-facing parts of Brigade (not the scripting itself though?  Presumably that would be handled by VS Code's existing JS support).

**Comment by squillace** [comment]
Brigade is the following things (outside of the service/project installation) that might be relevant:

1. a service in a cluster, so helm chart and all of that.
2. A project yaml file, typically containing the Brigade Project name, some other metdata, and the secrets necessary to do what the project is for.
3. the "app" itself, which is a JS file that is given to the project to run. Typically but not necessarily in the github repo. 
4. The "brig" tool, which can describe the projects in the cluster at which you are pointing.

1, 2, and 3 are all just apps and currently supported by other extensions. 4 could be a tree view of projects. You could have a command >Brigade create project or something that created a scaffold yaml file and brigade.js file. 

More interesting, I think, is that if:
1. docker extension (for the image repo)
2. git extension is logged in
3. kubernetes extension is installed (just sayin')

then you could:
1. with any folder actually open, >Brigade CI/CD project create
2. obtain the github token programmatically (https://github.com/octokit/node-github#authentication) and enter it into the project yaml file properly and set the repo name (or prompt to create one in github and then use that one).
3. template in a brigade.js file that 

a. listened for pushes, PRs on the repo
b. pulled the repo and built the image (assuming it has one; stop project creation if it doesn't)
c. pushed the image to the image repo
d. installed the helm chart for that repo (assuming it has one; ditto above)

instant simple CI/CD brigade project for the code you're in.

Now THAT is a brigade extension. Whatchya think?

**Comment by brendandburns** [comment]
Closing as obsolete.
