### ISSUE TITLE
Add Endpoints to the tree view

### ISSUE THREAD

**Issue by lita** [Azure/vscode-kubernetes-tools#407]
Hello, I just installed the kubernetes extension and I noticed that I am not able to see the Endpoints Resources. I know I can get the same data in the Pod view, but it would be nice to see the Endpoint Resource of a service and get a collection of IP addresses. Maybe it exists and I am not seeing it? But  I still have to use `kubectl get endpoints` in order to get this view.

Thanks!

**Comment by itowlson** [comment]
This sounds like a useful feature for a service.  We're a bit heads down getting ready for Kubecon at the moment but I'll aim to take a look at this when that eases off - do feel free to ping on this if there's no action on it.
