### ISSUE TITLE
Config Lint Rules?

### ISSUE THREAD

**Issue by etsuo** [Azure/vscode-kubernetes-tools#408]
It seems like there is a limited linter built into this plugin and it looks like it reports when a resource limit hasn't been set in a container spec. Is there a way to turn off all linting, or better yet, a specific rule? I end up with big blocks of distracting green squiggles when I'm mid way defining a new deployment and haven't gotten around to thinking about what resource limits I want.

I found [this code](https://github.com/Azure/vscode-kubernetes-tools/blob/c5c14b0872107e9d9e4d46c5a38a386e5c43abdd/src/components/lint/resourcelimits.ts), but I'm not seeing anything that indicates some kind of preferences check (though I'm not really familiar with the implementation of the project, so I likely wouldn't see it if it's there). Thanks.

**Comment by fr-ser** [comment]
Sorry foropening up this old issue, but how exactly does the (JSON) config have to look like to apply this disabling rule?
At least the vs code auto complete is giving me no hints...

**Comment by itowlson** [comment]
@fr-ser Sorry for the delay in getting back to you - I have been away.  The config you want looks like this:

```
"vs-kubernetes": {
  "disable-linters": [
    "resource-limits"
  ]
}
```

**Comment by bh90210** [comment]
A newbie friendly suggestion, consider including the above snippet in the documentation. It will save a lot of people new (lost) to vscode some time :)

## Linters
The extension supports linting Kubernetes YAML files for potential problems or suggestions.
Here are the various linters, you can enable or disable them individually using the `disable-linters` configuration value.
  * `resource-limits`: Warn when a Pod is missing resource limits
  
```json
{
  "vs-kubernetes": {
    "disable-linters": [
      "resource-limits"
    ]
  }
}
```

**Comment by alegmal** [comment]
> @fr-ser Sorry for the delay in getting back to you - I have been away. The config you want looks like this:
> 
> ```
> "vs-kubernetes": {
>   "disable-linters": [
>     "resource-limits"
>   ]
> }
> ```

Thanks for your answer.
Just one question - where do I put this code snippet?

**Comment by alegmal** [comment]
If you're confused like me on where to put this snippet (Mac):

`Code -> preferences -> settings -> extensions -> kubernetes configuration -> Edit in settings.json`

Or open command palette and type:

`preferences: open settings (JSON)`

**Comment by SuperChenSSS** [comment]
Got the solution here, thanks.

**Comment by alex-frx** [comment]
> If you're confused like me on where to put this snippet (Mac):
> 
> `Code -> preferences -> settings -> extensions -> kubernetes configuration -> Edit in settings.json`
> 
> Or open command palette and type:
> 
> `preferences: open settings (JSON)`

you also have to restart viscose ;)
