### ISSUE TITLE
Error when 'Adding Container Support' to existing project

### ISSUE THREAD

**Issue by Ivers07** [Azure/vscode-kubernetes-tools#410]
Hi,

I'm trying the use of AKS for the first time and I am trying to continer support to an existing asp.net MVC solution. I have installed the extension but whenever i right click a project -> Add -> Container Orchestration Support and then select Kubernete/Helm i get the following generic error:

![image](https://user-images.githubusercontent.com/15321552/49504261-3640a800-f871-11e8-9caf-4db2047d9cf3.png)

I dont know whats causing the error or how to troubleshoot it.

Selecting Docker Compose works fine and if i create a new project using the 'Container Application for Kubernetes' template it works fine.

Any help appreciated,
Andy

**Comment by itowlson** [comment]
Kia ora @Ivers07 - I don't think that message is coming from the VS Code Kubernetes extension.  The commands you're describing aren't part of the VS Code Kubernetes extension, and your screenshot looks like 'full' VS rather than VS Code.  Are you in VS Code, or Visual Studio 20xx?

**Comment by itowlson** [comment]
I'm trying to get this routed to the appropriate team within Microsoft.  Bear with us!

**Comment by mthalman-msft** [comment]
@Ivers07 - This issue belongs at https://github.com/Azure/dev-spaces/issues.  Can you please close this one and open a new issue there?  Ping me on the new issue you create as well.  We're working on making this error message more descriptive.  In the mean time, you can get more detailed info about the underlying error by attaching another instance of VS as a debugger and breaking on exceptions.  Just attach at the point where you're about to click the OK button on the dialog to add the orchestrator support.

**Comment by brendandburns** [comment]
Closing this issue, since we found the right home for it.
