### ISSUE TITLE
StatefulSet and DaemonSet missing from workloads in tree view

### ISSUE THREAD

**Issue by GJKrupa** [Azure/vscode-kubernetes-tools#414]
The tree view supports a number of different Kubernetes workload types but StatefulSets and DaemonSets are missing from the list.

Environment:
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

vscode-kubernetes-tools: 0.1.14

Ubuntu 16.04.5 LTS (x86_64)

**Comment by itowlson** [comment]
These are present in the code (added in #377) but has not yet made it into a release.  Sorry for the delay - I'll try to push these up to the marketplace soon.
