### ISSUE TITLE
Run Kubernetes command in "TERMINAL" window in VS Code

### ISSUE THREAD

**Issue by kyliel** [Azure/vscode-kubernetes-tools#43]
Directly show and run that command in “TERMINAL” window. For example, I have a Kubernetes cluster which have 2 pods. I select one pod and click “Get”, the command “kubectl get pod/xxx -o wide” will be executed in “TERMINAL” window. And I also could see the output after this command is executed. Such an experience is also adopted by docker extension, maven extension, Ansible extension and others in VS Code. 

![1](https://user-images.githubusercontent.com/29885760/35552007-e25e894c-05cc-11e8-9077-99100833e608.jpg)

**Comment by kyliel** [comment]
@testforstephen will work on it.

**Comment by testforstephen** [comment]
Migrate @itowlson's comments:

> @itowlson: I feel we need a clearer design philosophy around how this is meant to work. When is a command meant to be run in a terminal? How many terminals do we create? If there are multiple terminals then how does the user tell which is which? We can use issue #43 to discuss possible approaches (and how other extensions do it) if that would help.

@kyliel @squillace  Any opinions about this?

**Comment by testforstephen** [comment]
> When is a command meant to be run in a terminal?

For ui operations, if it is be done by one single kubectl command, then i'd like to run it in terminal. 
The typical cases are `create/get/delete/describe/logs/expose/exec/scale/cluster-info`

Otherwise, hide the detail by using the normal kubectl.invoke.
The typical cases are `run/sync/diff/debug`

> How many terminals do we create? If there are multiple terminals then how does the user tell which is which?

I'd like to share the terminal. Although `vscode-docker` extension always run command in a new terminal, but i feel like the shared terminal is more friendly because k8s extension provides more ui commands (> 20) than docker.

**Comment by kyliel** [comment]
@itowlson, And it is better to get commands in command palette run in terminal tool. For example, if I select "Kubernetes Create", a command "kubectl create -f xxx.yaml" is shown on the terminal and executed on the terminal. Then I know what is happening.

**Comment by itowlson** [comment]
@kyliel Yeah, I think we're all agreed that it's desirable, I just want to align on the _design_ and _behaviour_ so Jinbo doesn't get dragged back and forth through a series of reviews with one person saying "I think it should work like this" and then someone else saying "no, _I_ think it should work like _this_."  My question is about refining the detail, not questioning the broad principle.

**Comment by kyliel** [comment]
@itowlson, Sorry for confusion. So far Jinbo's work is to get commands in the explorer (the tree shown under "Kubernetes" tab in above picture) execute in TERMINAL. What I mentioned is we also should get same behavior for commands in command palette (click ctrl+shift+P, type "Kubernetes: xxx). Below is an example for "Kubernetes: Get" in command palette.

1. click ctrl+shift+P, type "Kubernetes: Get".

2. If any active windows, the output will be shown as "info" (not in the window of OUTPUT or TERMINAL).

**Comment by kyliel** [comment]
![image](https://user-images.githubusercontent.com/29885760/36582272-ca7beb8e-18ab-11e8-9708-a30f686946ab.png)
