### ISSUE TITLE
Checking minikube updates doesn't support space in path to check

### ISSUE THREAD

**Issue by apupier** [Azure/vscode-kubernetes-tools#441]
I got this notification message poping up:

`Error checking for minikube updates: 'C:\Users\Aurelien' is not recognized as an internal or external command, operable program or batch file.`

my username is Aurelien Pupier

**Comment by apupier** [comment]
I think on this line https://github.com/Azure/vscode-kubernetes-tools/blob/d4834fc95bc2f42bb6f70f683595e3d73420ffb0/src/components/clusterprovider/minikube/minikube.ts#L94

double quotes needs to be provided around ${context.binPath}

**Comment by itowlson** [comment]
Fixed via #442.
