### ISSUE TITLE
Intellisense and validation for CRD instance YAML

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#447]
At the moment we have no schemas for CRDs, so we offer no intellisense or validation on CRD instance YAML (and indeed have errors saying in effect 'what the bloody hell is this and how the devil do you expect me to edit it' because VS Code error messages are written in the style of Michael Caine everybody knows that).  Kubernetes 1.13 allows CRDs to contain a `validation` element (or, for multi-version ones, a `schema` element per version because why would you use the same word for the same thing) containing a JSON Schema for the instances.  But apiserver does not merge CRD types and schemas into the Swagger document it serves up.  There was a PR for that (https://github.com/kubernetes/kubernetes/pull/67205) which got merged and then backed out, so Kubernetes is not going to do this for us until 1.14.  Our options are:

1. Resolve the CRD kind ourselves, and get the CRD and pull out the appropriate schema and stuff it into the YAML parser.  And hope this doesn't cause problems if 1.14 does fix this.
2. Wait and hope it doesn't get put off again.

**Comment by tarioch** [comment]
It looks like even with newer kubernetes version this is still not working (1.15), I'm getting the error

`Unable to load schema from 'kubernetes://schema/flux.weave.works/v1beta1@helmrelease': No content.`

and the crd has a validation block: https://github.com/weaveworks/flux/blob/master/deploy-helm/flux-helm-release-crd.yaml

**Comment by itowlson** [comment]
Thanks for the heads up.  We may not yet be loading the schema from the cluster (this is fairly old code).  I'll have a look at how we're loading the schema and, if it doesn't Just Work TM, how k8s is surfacing the CRD schemas.  Thanks again - I had missed that this was now in a Kubernetes release,

**Comment by itowlson** [comment]
@tarioch I had a look at this.  We had a local copy of the k8s schema so it wasn't picking things up from the cluster.  There's now a PR (#583) to address that, though it is somewhat flawed due to issues with the underlying YAML tools - specifically documents that are open when the extension loads will still get the fallback schema and will need to be closed and reopened to get the schema from the cluster.  But hopefully it will improve matters.

I should also fix the error message when the custom resource schema is not available (e.g. because it's an older version of k8s, the feature gate is not on, or the CRD is not installed in the active cluster).  I've raised an issue for this.
