### ISSUE TITLE
Kubernetes extension consumes excessive CPU anytime a YAML file is open.

### ISSUE THREAD

**Issue by robcowart** [Azure/vscode-kubernetes-tools#450]
macOS mojave 10.14.2
vscode 1.30.2
Kubernetes extension 0.1.15

For the following tests, all unnecessary apps were fully closed.

### 1. vscode w/o kubernetes extension, *no* `yml` file open
CPU utilization is almost nothing.

![screenshot 2019-01-24 at 09 29 29](https://user-images.githubusercontent.com/10326954/51665861-f8cce100-1fbc-11e9-97e5-c38482e7760d.png)

### 2. vscode w/o kubernetes extension, `yml` file *open*
Again, CPU utilization is almost nothing.

![screenshot 2019-01-24 at 09 32 15](https://user-images.githubusercontent.com/10326954/51665969-36316e80-1fbd-11e9-871b-5f30eccc07d1.png)

### 3. vscode *with* kubernetes extension, *no* `yml` file open
Minimal additional CPU utilization.

![screenshot 2019-01-24 at 09 33 47](https://user-images.githubusercontent.com/10326954/51666004-53663d00-1fbd-11e9-8030-d38002722aa3.png)

### 4. vscode *with* kubernetes extension, `yml` file *open*
CPU utilization jumps to about 20%, and remains there even after `yml` file is closed. To return to normal CPU utilization vscode must be restarted.

![screenshot 2019-01-24 at 09 35 33](https://user-images.githubusercontent.com/10326954/51666221-ac35d580-1fbd-11e9-8341-491fea43677d.png)

I work with a lot of `yml` files for various applications, so I almost always have at least one open. This additional CPU usage has a significant impact on my battery life, so that I am forced to uninstall this extension.

**Comment by jnummelin** [comment]
I have similarly feeling issue. Looking at the process monitor (open from Help --> Open Process Explorer) there seemed to be 2 `while true` loops running `kubectl version -o json`. I really do not  access my Kuberenetes clusters through VS Code, I merely want the editor to be k8s friendly so I wanted to disable the kubectl loops. I didn't really find out how to do that, but I found a really super ugly way to do it. On the user settings, do something like this:
```
"vs-kubernetes": {
        "vs-kubernetes.kubectl-path": "/usr/bin/true"
    }
```

Yes, super ugly but seems to make the kubectl looping go away. :D  and now my battery lasts a while longer.

**Comment by itowlson** [comment]
@robcowart Just a quick note to say thanks heaps for taking the time to put this into an issue, and thanks @jnummelin for the pointer as to what might be going on.  We'll take a look at this as a high priority, and I hope make it usable for you Rob.

**Comment by itowlson** [comment]
It looks like we would call `kubectl version -o json` if another `kubectl` call failed (to determine if the failure might be down to client-server version mismatch).  Not sure why we would be calling `kubectl` in a loop as soon as the first YAML file gets loaded.  But it means one quick fix might be to not re-check on every failure.  Though that might still leave the failing call looping, so I still need to look into why that initial call is happening.

**Comment by brendandburns** [comment]
@itowlson as a first quickfix, maybe add a config option to disable retry?

**Comment by itowlson** [comment]
I don't need we need to resort to a config option.  It's easier just to change it to only do the compatibility check a maximum of once.  I'll have the PR out shortly but today has been a bit fraught.

**Comment by itowlson** [comment]
It looks like we can get into this loop if the `kubectl-path` setting (or the kubectl binary on the path) is a valid binary but one which errors when called with `kubectl version -o json`.  I don't see it whomping the CPU (about 1% usage on my machine), but I do see the infinite loop so I can see how it might use up a lot of CPU depending on the host system.

**Comment by itowlson** [comment]
Fix released in 0.1.16 which is up on the Marketplace now.  If folks who were having problems have the time and patience to give it a try then that would be awesome.  Either way, thanks again for taking the time to report the bug!

**Comment by robcowart** [comment]
I can confirm that this has fixed the issue. Below is the a screenshot of the same scenario I mentioned above, and you can easily see the low CPU compared to before.

<img width="1279" alt="screenshot 2019-01-28 at 23 09 49" src="https://user-images.githubusercontent.com/10326954/51869863-2cf42900-2352-11e9-80a6-c1653e03995a.png">

Thanks for the quick turnaround!

**Comment by robcowart** [comment]
BTW, I have updated my initial review in the marketplace.

Thanks again!
