### ISSUE TITLE
Describe command could use an auto refresh option

### ISSUE THREAD

**Issue by cmeyertons** [Azure/vscode-kubernetes-tools#464]
Great work on the new updates, it's been a huge productivity win!

I really like the new describe how it outputs to the editor window vs the terminal.

When I'm troubleshooting container start ups, I find myself re-clicking describe over and over.  It would be great if there was a capability to auto refresh describe on a specified interval (it would stop once the editor window was closed by the user)

Could be accomplished either by:
- User config (`describeAutoRefresh & `describeAutoRefreshInterval`)
- Separate context menu (Describe - auto refresh)

**Comment by itowlson** [comment]
Would an auto refresh checkbox on the describe window do it?  It's a HTML view rather than a plain editor window so we have more than the usual latitude to do wild UI.

cc @brendandburns

**Comment by itowlson** [comment]
Now I have bizarre fantasies of an 'auto diff' view where every time it auto refreshes it shows you the diff from the previous description.  SEND HELP

**Comment by cmeyertons** [comment]
Checkbox in the view is fine, just as long as I have the ability to configure that it defaults to “true”.

Lol at the auto diff view. Might be kind of cool. Maybe instead of a diff, as changes occur there’s some sort of green animation that fades away so it’s noticeable

**Comment by itowlson** [comment]
Hmm, this one might take some pondering.  I worry about using global config for things where I think users will often really want the behaviour to depend on context, but I take your point about configuring the default.  And thinking further about it, I'm not sure we want the clutter of a toolbar-style UI just for a Describe which should have more of an editor window feel.

Yeah, I think briefly highlighting stuff that has changed is more sensible than a diff view.  I just wanted to avoid having to do any work. *grin*

**Comment by brendandburns** [comment]
@itowlson do you mind if I take this one? Have you already started work?

**Comment by itowlson** [comment]
@brendandburns Go for it!  Thanks!
