### ISSUE TITLE
CronJob - add "Run Now" action

### ISSUE THREAD

**Issue by cmeyertons** [Azure/vscode-kubernetes-tools#469]
I typically have a Code task to do this,

```
{
            "label": "cluster: run datapump now",
            "type": "shell",
            "command": "kubectl create job --from=cronjob/datapump-nightly datapump-manual --namespace ${input:environment}",
            "problemMatcher": []
        },
```

which I had to spend some cycles to go look up how to do in the k8s documentation.  I think this would:

1. be of great utility in the context menu
2. further help new people better learn the `kubectl` commands by showing them real world examples as this outputs to the terminal window. (I know this is how I personally have gained a lot of know-how)

I would expect the task to be re-runnable (delete & create or however it can be accomplished)

**Comment by itowlson** [comment]
I like this idea!  Thanks!  To be clear, you envisage this not as a VS Code task, but as a right-click command on CronJob resources?  And that it would prompt for a job name, with a suitable default?  (If the job name already exists we could offer to delete and recreate, would that work?)  Users with particular jobs they wanted to run on demand could set up keybindings to the command bound to a particular cronjob name, or I think create tasks bound to particular names.

How do you envisage closing the feedback loop on this one?  Does it suffice to just let the user know the job has been created, or is it necessary to display information about the created job or something?

**Comment by cmeyertons** [comment]
Sweet!  Yeah, right-click command! (That is also mapped to a VS command palette command like the other commands are)

good idea on prompting for the name -- I think from a complexity standpoint it's probably easier to not automate a delete & recreate.  I was thinking of incrementing the default but thats hard to do too.  What if the default just had a timestamp in it?  That provides some signficance as to when the job was kicked off and is always unique.  

run 1: Run now `mycronjob` -> Prompt `mycronjob-20180213-051206` -> Run above `kubectl create job command`

Could make the prefix `mycronjob-manual`, your call.  It also looks like my timestamp generation is different than how K8s does it (`datapump-nightly-1550026800`), so probably want to keep it consistent

In terms of feedback, a toast notification is probably fine -- I think Cadillac solution that might be overkill is to wait for the job to start and start following logs in the terminal.

My typical process is:
1. Run VS code task to create (and probably have to go in and manual clean up the previous)
2. Kubernetes: Refresh
3. right click new job -> Follow Logs
