### ISSUE TITLE
Always show "Error checking prerequisites" when exec Create Kubernetes Cluster wizard

### ISSUE THREAD

**Issue by testforstephen** [Azure/vscode-kubernetes-tools#475]
```
vscode: 1.31.1
kubernetes extension: 0.1.16
```

When exec "Create Kubernetes Cluster" wizard, it always show the error below even though i installed the azure-cli 2.0.58.

```
null
Error checking prerequisites
The Azure command line failed. See below for the error message. You may need to:

Log into the Azure CLI (run az login in the terminal)
Install the Azure CLI (see the instructions for your operating system)
Configure Kubernetes from the command line using the az acs or az aks command
Details

Azure CLI 2.0 not found - install Azure CLI 2.0 and log in

```

**Comment by itowlson** [comment]
Hmm, I can't reproduce this I'm afraid.  Can you dump your PATH in the VS Code terminal window and verify that the Azure CLI is on it?  If you run `az --version` from the VS Code terminal window, what are the first few lines of the output?

Also, since installing Azure CLI have you closed _all_ instances of VS Code and restarted _from the shell_?  Sometimes VS Code can cling onto old environment variables longer than seems humanly possible...!

**Comment by testforstephen** [comment]
I tried in VS Code terminal, `az` command is there.
![image](https://user-images.githubusercontent.com/14052197/52984670-6a1c7a00-342b-11e9-9a74-328e4fb23950.png)

YES, i closed all VS Code instances, and start again.

**Comment by itowlson** [comment]
Eeyargh, they changed the format of `az --version`.

If you're able to temporarily downgrade to Azure CLI 2.0.57, then that should fix your problem.  Otherwise, I'll aim to get a fix out ASAP.  Thanks for the heads up on this!

**Comment by loshurik** [comment]
Hi there=)
I have the same issue with az cli 2.0.59
![image](https://user-images.githubusercontent.com/1557456/54287447-b8e6ab00-45b6-11e9-8ce4-d775582271fc.png)
Could you have a look, please?

**Comment by itowlson** [comment]
They added a star.  Why did they add a star?  Why?  Why?  _bursts into tears_

Thanks for the heads up @loshurik - I'll take a look.

**Comment by aklintsevich** [comment]
Has this been resolved? I'm hitting this on version 2.0.64

**Comment by itowlson** [comment]
It has been resolved, but it seems that Azure CLI has introduced a new thing that has caused a new bug.  See https://github.com/Azure/vscode-kubernetes-tools/pull/476#issuecomment-501491637 (I have not yet raised the issue for it, will do that now).

The workaround is to use the `vscode-aks-tools` package (https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-aks-tools) which adds your Azure subscriptions to Cloud Explorer and from where you can merge kubeconfigs (you will need to log into the Azure Account extension though, it can't reuse your Azure CLI login).  Or run `az aks get-credentials` from the command line.

**Comment by itowlson** [comment]
Correction, I did raise an issue: https://github.com/Azure/vscode-kubernetes-tools/issues/562
