### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chuckstar76** [Azure/vscode-kubernetes-tools#478]
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.16`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/chope2/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by itowlson** [comment]
@chuckstar76 Is it okay to close this as a duplicate of #479 which has the `cpuprofile` file attached?  Thanks!

**Comment by chuckstar76** [comment]
Hi - yes please close, I realised the attachment was missing and added to [#479](https://github.com/Azure/vscode-kubernetes-tools/issues/479) - as indicated.
