### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chuckstar76** [Azure/vscode-kubernetes-tools#479]
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.16`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/
[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt]
ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt` :warning:

(https://github.com/Azure/vscode-kubernetes-tools/files/2895286/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by itowlson** [comment]
@chuckstar76 Sorry you're hitting this - we fixed one cause of this in 0.1.16 but it looks like something is still going on for you.  Are you able to provide any more info e.g.

* Does CPU load go up as soon as the extension is activated, or only after you take a particular action?
* Did you experience this with previous versions of the extension?
* Are you using a configured path to `kubectl` or is it on your system path?
* What is the output if you run `kubectl version`?  (If you have a kubectl entry in your config, substitute `the/value/of/the/config/entry version`.)
* What is the output if you run `kubectl cluster-info`?  (Again using your config path if you have one.)

Another thing that would be really helpful would be if you could open VS Code Process Explorer (Help > Process Explorer), do a right-click > Copy All when it has populated, and post the content of that file please?  This provides more information about what VS Code and its child processes are doing than the raw CPU Profile file.  Thanks!

Thanks in advance for helping us to diagnose this - hopefully we can get it fixed for you.

**Comment by itowlson** [comment]
The profiler trace you supplied seems to mostly concern itself with extension loading.  Can you let me know what was happening while the profiler was running e.g. was this extension startup, idle, or you doing something e.g. editing, viewing, browsing tree view?  Thanks!

**Comment by chuckstar76** [comment]
@itowlson 
Since you posted the comments I've started VS Code a number of times.
The problem around CPU load has not repeated itself. 

The initial report came immediately at application start, so I'm presuming as this extension and others were activated something triggered the file an issue on this topic.

Here's the output of the VS Code Process Explorer:
CPU %	Memory (MB)	pid	Name
7	98	94242	code main
0	49	94292	     gpu-process
0	229	94369	     window (test-script.sh)
0	115	94372	         extensionHost
0	82	94389	     shared-process
1	82	94822	     window (Process Explorer)
0	0	94903	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Response to questions:

* Does CPU load go up as soon as the extension is activated, or only after you take a particular action?
>> It was at the initial application load - but since then has not repeated itself
* Did you experience this with previous versions of the extension?
>> Not that I'm aware of - also I've only recently started using VS Code 
* Are you using a configured path to `kubectl` or is it on your system path?
>> system path installed via homebrew on MacOS
* What is the output if you run `kubectl version`?  (If you have a kubectl entry in your config, substitute `the/value/of/the/config/entry version`.)
>> 1.13.3
* What is the output if you run `kubectl cluster-info`?  (Again using your config path if you have one.)
>> Presently none configured

When I open VS Code to see this issue, I was only opening a local file to edit, it wasn't for use with K8s anyway.  
I think this may well be a non-issue now.  I've done some tidying of the user home directory which included adding a .gitignore and populating it - so that the git extensions didn't go nuts on application load either. 

If you're happy to have this closed - that's fine by me.

**Comment by itowlson** [comment]
Thanks @chuckstar76 for taking the time to post all this info, and I'm glad it's looking like a one-off.  I'll keep an eye on startup performance, but as we have no repro for this particular incident I'll close this one.  Thanks again!
