### ISSUE TITLE
Suppress minikube upgrade available message

### ISSUE THREAD

**Issue by meeech** [Azure/vscode-kubernetes-tools#481]
Hi

Would a PR that allows a config to supress Minikube upgrade message be welcomed? 
I use an older version of minikube, and the constant messaging is getting annoying. 

thanks

**Comment by itowlson** [comment]
It sure would!  Thanks!

**Comment by meeech** [comment]
👍 i'll tackle this

**Comment by itowlson** [comment]
Thanks!  Let me know if you need any pointers.

**Comment by itowlson** [comment]
Fixed via #488.
