### ISSUE TITLE
When will 0.1.17 be available?

### ISSUE THREAD

**Issue by yehiyam** [Azure/vscode-kubernetes-tools#487]
Hi
is there a time frame for the next version? I'm looking forward to use the nodejs debug feature

**Comment by itowlson** [comment]
Hopefully this week, but I'm not promising to hit that.  We are definitely due, but there are a few pull requests outstanding that I'd like to land.  If 1.17 isn't out by the weekend, please follow up on this issue for an update.

**Comment by itowlson** [comment]
I don't think I'm going to get this over the line this week I'm afraid.  Will aim for early next week.  Sorry.

**Comment by itowlson** [comment]
Released went out yesterday - enjoy!  (And please report any bugs!)
