### ISSUE TITLE
Kubernetes extension tree shows helm release templates with secrets in plaintext

### ISSUE THREAD

**Issue by derekyle** [Azure/vscode-kubernetes-tools#492]
When I click a deployed chart under helm releases, it opens a file helmrelease-{chart-name}.txt file. This file shows all the templates with variables expanded thus exposing any secrets like passwords.

I am not able to figure out where the helmrelease-*.txt content is coming from. Are they being pulled from the cluster or just saved locally from when the chart was published or dynamically generated? Is there an equivalent helm cli command to get data like this?

I am just trying to figure out for security reasons where this data is being stored and if helm (or just this extension) is storing these expanded templates in plaintext somewhere.

**Comment by itowlson** [comment]
This looks like it's coming from the `helm get <release_name>` CLI command.  Could you try running that and see if that gives the same output?  The output is not stored; the `.txt` document is purely virtual.  There are no `.txt` files on disk unless the user opts to save one of these 'virtual' documents.

cc @technosophos

**Comment by maver1ck** [comment]
@technosophos 
Can we change extension of this info to .yaml ?

**Comment by technosophos** [comment]
It is not guaranteed to be YAML in Helm 2

**Comment by itowlson** [comment]
Proposing to close, as this is the underlying `helm get` behaviour.  If folks want to keep this open then sing out!
