### ISSUE TITLE
Add executable flag to the kubectl infer versioning method downloader

### ISSUE THREAD

**Issue by Petrox** [Azure/vscode-kubernetes-tools#493]
Using ubuntu 16.04 

Vscode
````
Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
````

With infer kubectl versioning: 

> vs-kubernetes.kubectlVersioning - By default, the extension uses the kubectl binary you provide on the system PATH or in the vs-kubernetes.kubectl-path configuration setting. If you set this setting to infer, then for each cluster the extension will attempt to identify the cluster version and download a compatible kubectl binary. This improves compatibility if you have multiple Kubernetes versions in play, but may be slower. IMPORTANT: Even if this setting is infer, you need a 'bootstrap' copy of kubectl on your PATH or at the vs-kubernetes.kubectl-path location - we need this to find out the server version so we know which version of kubectl to download! Also note that this setting is checked only when the extension loads; if you change it, you must reload the extension.

When connecting to a kubernetes cluster, the "downloading ..." popup appeared. Went fine.

Then I've received an error:
````
/bin/sh: 1: /home/username/.vs-kubernetes/tools/kubectl/autoversion/v1.13.4/linux-amd64/kubectl: Permission denied
````

The reason is that the downloaded executable is not executable:
````
$ ls -l ~/.vs-kubernetes/tools/kubectl/autoversion/v1.13.4/linux-amd64/kubectl
-rw-rw-r-- 1 user user 39251424 Mar 12 00:24 ~/.vs-kubernetes/tools/kubectl/autoversion/v1.13.4/linux-amd64/kubectl
````

So a chmod +x would be a nice addition to the download process.

**Comment by itowlson** [comment]
Aargh!  Thanks for reporting this... this is what I get for living almost entirely on Windows.  I'll get this fixed pronto - thanks for your patience and for taking the time to let me know.

**Comment by itowlson** [comment]
Thanks again for the bug report, @Petrox - a fix should land in the marketplace in the next half an hour or so.  And apologies for the inconvenience.
