### ISSUE TITLE
Error creating cluster when no default SSH key under .ssh

### ISSUE THREAD

**Issue by kyliel** [Azure/vscode-kubernetes-tools#50]
Error: An RSA key file or key value must be supplied to SSH key Value. You can use --gnerate-ssh-keys to let CLI generate one for you.

**Comment by itowlson** [comment]
Hmm, this happens if there isn't a default SSH key (`id_rsa`), but that should be caught by the prerequisites check.  Can you have a look in your `.ssh` directory and let me know what files you have in there please?

**Comment by kyliel** [comment]
No, I don't have id_rsa there. It is better I could get the hint that I should have ssh key ready before I navigate to next step. Or give me the option to add additional parameter "--generate-ssh-keys" when I move to next step.

**Comment by itowlson** [comment]
Yeah, it's meant to complain if you don't have the SSH key.  I'll check out why that isn't happening.

Was this AKS or ACS?

**Comment by itowlson** [comment]
Can you check if you have both `id_rsa` and `id_rsa.pub`?  I think I've seen this error if you have the private key but not the public key.

**Comment by kyliel** [comment]
Sorry for late response. It is AKS. 
When there is no default SSH key under .ssh, could the extension create one instead of reporting errors? It will be more friendly. 
I am using VS Code on Windows. The folder .ssh is under c:\user\<my user name>\.

**Comment by bnookala** [comment]
@itowlson @kyliel Looks like we can use this beta feature in make use of `ssh-keygen` for key generation! https://blogs.msdn.microsoft.com/commandline/2018/01/22/openssh-in-windows-10/

**Comment by itowlson** [comment]
Oh I think I already fixed this?  https://github.com/Azure/vscode-kubernetes-tools/pull/230

**Comment by bnookala** [comment]
@itowlson yes this looks like you did do the thing
