### ISSUE TITLE
Build process: bundle extension 

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#500]
When packaging the extension, we get this lovely notification about the number of files we package:

```
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-kubernetes-tools@0.1.18 vscode:prepublish /Users/bhargav/code/vscode-kubernetes-tools
> npm run compile


> vscode-kubernetes-tools@0.1.18 compile /Users/bhargav/code/vscode-kubernetes-tools
> tsc -p ./

This extension consists of 7770 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension
 DONE  Packaged: /Users/bhargav/code/vscode-kubernetes-tools/vscode-kubernetes-tools-0.1.18.vsix (7770 files, 13.47MB)
```

The aka link points to here: https://code.visualstudio.com/api/working-with-extensions/bundling-extension

We should consider utilizing webpack for extension bundling.

**Comment by itowlson** [comment]
We have been seeing reports of high CPU load on initial load, and it has felt to me like loading has been getting slower again; perhaps this is why.

**Comment by itowlson** [comment]
See e.g. #501 where we get high load on the first run, though I'd expect this issue to us on unpack and/or on every activation, not specifically on first activation.

**Comment by itowlson** [comment]
I tried webpack-ing it and it was a bit of a disaster.  `vsce package` keeled over with a totally opaque error message; `npm run compile` (which called `webpack --mode none`) produced a big pile of warnings, two errors about unresolvable `require` expressions in some deeply indirect thing called `got`, and a version conflict for the Node.JS types between `@types/node` and `@types/shelljs`.  In conclusion, America is a land of contrasts.

**Comment by bnookala** [comment]
oh hey, this is done! https://github.com/Azure/vscode-kubernetes-tools/pull/586
