### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by benmed00** [Azure/vscode-kubernetes-tools#501]
[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/3008244/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.18`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\mbenyakoub\ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by itowlson** [comment]
Thanks @benmed00 - could you let us know, does this happen on activation (e.g. when you first load the tree view, or issue a command) or while the extension is running?  Does it happen frequently or was this a one-off?  Thanks!

**Comment by benmed00** [comment]
the error is produced in the First Run of the extension

**Comment by lstocchi** [comment]
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue. Thanks!!
