### ISSUE TITLE
Please stop writing "WARNING: No active editor during save. Nothing saved." to the Helm output channel

### ISSUE THREAD

**Issue by eamodio** [Azure/vscode-kubernetes-tools#51]
Currently when ANY document is saved and there is no active editor, the extension logs `WARNING: No active editor during save. Nothing saved.` to the `Helm` output channel (and forces the output channel to show itself 😢)

This is causing issues with [GitLens'](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) new settings editor (since it is a previewHtml -- not an editor) and it saves settings which seems to cause vscode to fire an `onDidSaveTextDocument` event.

Here is the offending line:
https://github.com/Azure/vscode-kubernetes-tools/blob/43210bbc8edac9cb075a63f26fd51fb11ba3285f/src/extension.ts#L162

Also here is where it is forcing the output panel to show each time something is logged -- I hope this can be removed too.
https://github.com/Azure/vscode-kubernetes-tools/blob/43210bbc8edac9cb075a63f26fd51fb11ba3285f/src/logger.ts#L20

**Comment by itowlson** [comment]
Thanks for flagging this.  I've noticed that some of the Helm bits can be a bit over-enthusiastic.  I'll figure out why it wants to warn about this and get it fixed so it errs on the side of non-noisiness.

**Comment by itowlson** [comment]
@eamodio If you want to test with the proposed fix in the PR, please grab it from my fork and let me know if it still gives you grief!  Thanks again for flagging this.

**Comment by eamodio** [comment]
Awesome -- thank you for the quick fix! A few people thought GitLens was broken because of it, so will be wonderful to have it fixed.

**Comment by itowlson** [comment]
@eamodio To close the loop - this update is now published in the gallery (as 0.1.5), so your users can now take the fix.  Sorry for the delay (travelling!).
