### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cspencerjr** [Azure/vscode-kubernetes-tools#519]
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.18`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
'ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by brendandburns** [comment]
Closign this one, since there is no profile actually attached....
