### ISSUE TITLE
Do not activate on the general onDebug activation event

### ISSUE THREAD

**Issue by isidorn** [Azure/vscode-kubernetes-tools#521]
Related https://github.com/Microsoft/vscode/issues/72123

Hello VSCode dev here,

Why is the kubernetes extension activating on the `onDebug` activation event.
Is the kubernetes extension interested in a specific debug type or in all types? Because we have more fine grained event.

With the current approach kubernets is slowing down the first debug of an unrealted debug session like java (as seen in the attached issue)

fyi @testforstephen

Thanks 
isidor

**Comment by itowlson** [comment]
@radu-matei @testforstephen You folks know more about the debug features than I do - any insight on this?

**Comment by itowlson** [comment]
@isidorn Is your recommendation that we activate on specific `onDebugResolve:...` events?

**Comment by testforstephen** [comment]
@itowlson The `onDebug` activationEvent is added by Draft Debug feature. Given the [draftConfigurationProvider](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/draft/draftConfigurationProvider.ts#L11) implementation, changing the activationEvent to `onDebugResolve:draft` is enough.

**Comment by isidorn** [comment]
Great. So my recommendation is to change this to `onDebugResolve:draft` as @testforstephen is saying.
