### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by wolverian** [Azure/vscode-kubernetes-tools#538]
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.18`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.33.1`

[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/3158181/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)

**Comment by lstocchi** [comment]
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue. Thanks!!
