### ISSUE TITLE
Fix slow initial load

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#542]
We have a number of autogenerated reports of high CPU load during the first run of the extension; anecdotally it is feeling slow to load/unpack again.  This is a tracking issue for that problem.  See also #500.

**Comment by radu-matei** [comment]
FWIW, I can also confirm the initial load time of the extension when VS Code starts has significantly increased.

**Comment by itowlson** [comment]
The good news: Webpack does make this _hugely_ faster.

The bad news: Webpack is currently blocked by the `jsonpath` dependency (via `@kubernetes/client-node`): https://github.com/webpack/webpack/issues/9367
