### ISSUE TITLE
Workloads pods not visible

### ISSUE THREAD

**Issue by TristanFAURE** [Azure/vscode-kubernetes-tools#550]
Thanks for this extension (and thank you for the presentation at KubeCon 2019)

I succeed to run the extension but I can't see my workloads this is what I see :

- cluster name 
  - namespaces 
     - namespace1
     - namespace2
  - nodes : OK
  - workloads
     - Pods : nothing :(

Is it normal that i don't see my pods ?

My environment :
- kubectl
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean",
BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean",
BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- vscode : 1.34.0
- kubernetes extension version : 1.0.0
- kubernetes : rancher 2.1.3

**Comment by brendandburns** [comment]
By default the extension uses the `default` namespace. You may need to right-click on a namespace and activate that namespace as the selected namespace. If that still doesn't work, please let us know.

**Comment by bnookala** [comment]
Hi @TristanFAURE - were you able to resolve your issue by right clicking the namespace you'd like to view pods in?

**Comment by TristanFAURE** [comment]
Hello
Thank you for your answers !
I have no possibility to test before 11th June. But as soon as I have the connection back I'll let you know

**Comment by TristanFAURE** [comment]
You were right it is working ! You can close the ticket

**Comment by bnookala** [comment]
Thanks!
