### ISSUE TITLE
Extension causing issue with Git integration of VS Code

### ISSUE THREAD

**Issue by levrik** [Azure/vscode-kubernetes-tools#558]
See microsoft/vscode#69334 for details.
There was some bug on VS Code which was fixed but the same bug as described over there still occurs when the Kubernetes extension is active. As soon as I disable it and reload VS Code the issue is gone.
Here's a video of demonstrating this issue: https://youtu.be/-ZTeocap3uw

**Comment by itowlson** [comment]
How weird.  We don't do anything with SCM _or_ with images so I don't know why a deleted image in Git would cause us to blow up.  I'll take a look - thanks for letting us know!

**Comment by levrik** [comment]
@itowlson Yep. Of course I disabled all SCM related extensions first and was surprised when disabling this extension, fixed the problem.
Let me know if you can reproduce.

**Comment by itowlson** [comment]
Yes, it's reproducing for me (on Windows).  THIS IS SO WEIRD.

But it gets weirder.  The hang happens EVEN IF THE EXTENSION DOESN'T ACTIVATE.

I don't know how this is even possible.

^^ reassuring maintainer comments

**Comment by itowlson** [comment]
Found it, and I'm afraid it's a VS Code bug, which I will raise on their repo.

**Comment by itowlson** [comment]
@levrik Is it okay if I close this on the k8s extension side please?

**Comment by levrik** [comment]
@itowlson Sure.

**Comment by levrik** [comment]
@itowlson This issue was fixed on VS Code's side in the latest 1.36.0 insiders version (https://github.com/microsoft/vscode/commit/7bc29bf67c17608b11e23a8497c8f1de5a0922cf, 2019-06-11T08:29:28.099Z)

**Comment by itowlson** [comment]
That's great @levrik - thanks for the followup and for your help in identifying this.
