### ISSUE TITLE
Spurious failure to run Azure CLI if update check fails

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#562]
In https://github.com/Azure/vscode-kubernetes-tools/pull/476, @jvermast reports that the `az --version` check spuriously fails in his environment because the Azure CLI prints a message _WARNING: Unable to check if your CLI is up-to-date. Check your internet connection._ to stderr.  Although the CLI returns 0 and has displayed the version, we see the stderr and incorrectly treat this as a failure.

I believe we check stderr because in the past we have seen Azure CLI return 0 on failure when running a 'service' command.  That's not an issue for `az --version` though.  We should remove the stderr check.

**Comment by rdalkire** [comment]
This still happens as of 2.16.0

**Comment by idusortus** [comment]
Version 2.22.1 still happens in Admin powershell as well as Git Bash.
