### ISSUE TITLE
Can no longer see all pods in a node

### ISSUE THREAD

**Issue by derekyle** [Azure/vscode-kubernetes-tools#565]
Previously, I could click on a node and get a listing of all pods on that node. However, it seems that after upgrading to somewhere around gke's k8s version 1.12+ I no longer have this capability. I am still able to list pods using my local k8s which is running v 1.10.

Obviously, this is due to some change with K8s. Is this a known issue with newer versions of Kubernetes?

**Comment by itowlson** [comment]
Hmm, no, I haven't seen this.  Which version of kubectl are you running with your 1.12 cluster?  Could you run `kubectl get pods -o wide --all-namespaces` and paste in the first few lines of the output please?  (And would you mind doing the same for your 1.10 local cluster please, just for comparison?)  (Feel free to anonymise anything sensitive of course.)

**Comment by derekyle** [comment]
Hopefully images are ok. Line wrapping makes a mess otherwise. The first image is from 1.13.6-gke.6 and the second is from my local v1.10.  Kubectl version, while connected to the gke cluster shows this:

`Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:28:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}`

![image](https://user-images.githubusercontent.com/2208099/59477124-a7f14400-8e08-11e9-9f03-86351f4c60a7.png)

![image](https://user-images.githubusercontent.com/2208099/59477227-1930f700-8e09-11e9-9254-8aa7778e81ce.png)

**Comment by itowlson** [comment]
Yes, the extension parses the kubectl output.  I'm wondering if something is confusing it - I notice that the new output has spaces in column headers which might be causing us problems.  Just taking a look now.

**Comment by itowlson** [comment]
Forgot to say thanks!

**Comment by derekyle** [comment]
No, thank you for taking a look!

**Comment by itowlson** [comment]
We're mishandling the `NOMINATED NODE` column.  We incorrectly treat it as two column headers, `NOMINATED` and `NODE`, and this spurious `NODE` column (which picks up the values in the `READINESS GATES` column) effectively overwrites the real `NODE` column with a nonsense value... and so we don't match the pods up with the node names.

I can get this fixed pretty quickly but probably won't push out a bug fix release until after the weekend (it's Friday afternoon here).  Is that okay?  In the meantime you can probably work around it for now by setting the `vs-kubernetes` -> `vs-kubernetes.kubectl-path` config setting to point to an older version of `kubectl` (looks like 1.10.x would work).

**Comment by derekyle** [comment]
Sure, not a problem. I've been dealing with it for a few weeks now. It's just a nice-to-have when I need to quickly see which pods are having trouble at a glance. I appreciate the extension.

**Comment by itowlson** [comment]
Gah.  Using `kubectl get -o custom-columns=...` gives us control over the output format... but the `STATUS` field in the default output is NOT a server field, it's a composite of pod `.status.phase` and the container status(es), and so cannot be mapped this way as far as I can tell.

**Comment by itowlson** [comment]
And there used to be a convention that 'Column titles and values should not contain spaces in order to facilitate commands that break lines into fields: cut, awk, etc.'  https://github.com/kubernetes/kubernetes/pull/12515/files  But it seems to have been removed when they rewrote the docs: https://github.com/kubernetes/website/blob/master/content/en/docs/reference/kubectl/conventions.md

**Comment by itowlson** [comment]
`kubectl` output tables always provide at least 3 characters of padding between fields:

https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/tabwriter.go#L28

https://github.com/liggitt/tabwriter/blob/master/tabwriter.go#L209

This is sufficiently buried in the implementation that I probably shouldn't rely on it long term, but I'll take it for now.

**Comment by itowlson** [comment]
@derekyle Fix should be live in the Marketplace now - if the problem persists after the update, please reopen the issue and we'll investigate further!
