### ISSUE TITLE
[Helm] `{{` Autocomplete adds extra `-}}` when `-` is typed

### ISSUE THREAD

**Issue by ahmadalli** [Azure/vscode-kubernetes-tools#571]
If I type `{{` code automatically adds `}}` and everything is fine. but if I write `-`, then code automatically adds `-}}` and I'll end up with `{{--}}}}` which is not fine.

**Comment by ahmadalli** [comment]
![vid](https://user-images.githubusercontent.com/2167301/59691731-ba002780-91f8-11e9-9eb0-885912936299.gif)

**Comment by an-excellent-choice** [comment]
Autocomplete also results in extra brackets on both sides.

After the initial `{{--}}}}` shown in capture, if I then attempt an `if`, I end up with:

`{{- {{- if condition -}}`
`{{- end -}}-}}}}`

**Comment by ahmadalli** [comment]
I think there shouldn't be any autocomplete for `-` since `{{- ... }}` is used in many cases too

**Comment by sbibow** [comment]
I could disable it when disabling the linters. I don't know which linter is responsible for this so for a quick fix I just set the following setting in my `settings.json`:

```json
"vs-kubernetes": {
  "disable-lint": true
}
```

**Comment by alexkreidler** [comment]
I have the same issue. I love this extension, but this is a dealbreaker for me. Please fix!

**Comment by zackijack** [comment]
Hi @itowlson still happening on me, but in my case, every time  I type `{{` auto closed with triple bracket `}}}` instead of double `}}`

**Comment by ahmadalli** [comment]
same here
