### ISSUE TITLE
Show current context on status bar

### ISSUE THREAD

**Issue by robsonpeixoto** [Azure/vscode-kubernetes-tools#577]
Show the current context on status bar is very useful if the user go to the terminal to execute some commands

**Comment by itowlson** [comment]
That's a good thought.  We don't want to over-clutter the status bar so we might want to explore alternative approaches to this - e.g. keeping each terminal associated with a specific context (by injecting a KUBECONFIG environment variable) and opening a new one if the user changes context, and showing the context in the terminal name.  But that wouldn't help with the default terminal of course.

**Comment by robsonpeixoto** [comment]
Or the status bar be an optional feature where the user need to activate.
