### ISSUE TITLE
Unable to connect to the server: proxyconnect tcp: dial tcp 127.0.0.1:3128: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by dariuszbz** [Azure/vscode-kubernetes-tools#582]
since yesterday it wont work :(
firewall is off

**Comment by itowlson** [comment]
Are you able to connect with `kubectl`?

What are your client and server versions?

Does this happen with all operations or only specific operations?

Which cloud is your cluster in, if any?

**Comment by dariuszbz** [comment]
Hello,

Thank you for your response.

It's AKS. Clusters around the word.
I can connect, but not from VS Code Kubernetes extension.

It looks like minikube problem .

What server version do you mean? It's AKS windows.
My client it's windows 10 with docker desktop and visual studio code.

**Comment by dariuszbz** [comment]
just after I started VSCode and click kubernetes icon in the right pane, the error message comes in the left bottom corner:

Error checking for minikube updates: 
X Unable to fetch latest version info: Error getting json from minikube version url: error with http GET for endpoint https://storage.googleapis.com/minikube/releases.json: Get https://storage.googleapis.com/minikube/releases.json: proxyconnect tcp: dial tcp 127.0.0.1:3128: connectex: No connection could be made because the target machine actively refused it.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by squillace** [comment]
Error checking for Minikube updates. OK, so the extension checks https://storage.googleapis.com/minikube/releases.json, which currently works but didn't at this moment. It seems to be trying to dial through localhost, however.... @itowlson, what do you think? It appears to be trying to connect outbound to localhost and is stunned when it's rejected. Do I interpret this correctly?

**Comment by itowlson** [comment]
I believe this error is coming from Minikube.  My guess is that the `proxyconnect tcp: dial tcp...` stuff is Minikube error spew related to implementation details of how Minikube looks for the latest version (which as you rightly say is actually hosted on Google storage).  We've got PRs in flight around this and I will try to tidy up once those land.

@dariuszbz, are you still experiencing the error?  Also, is it preventing you from working with your AKS clusters, or is it a 'mere' annoyance?

**Comment by dariuszbz** [comment]
I install new VM, Vs code, extension, and it works. If you want I will not
delete the old one where the error occurred, and we can carry on with this
case.
Up to you gents.

**Comment by itowlson** [comment]
If recreating the Minikube VM fixed the problem, then don't worry about keeping the old one around for diagnostics.  I've had numerous problems with borked Minikube VMs but these are Minikube issues not VS Code extension issues; unfortunately there isn't anything we can do about this on the VS Code side.

Is it okay if we close this issue now that you have a working Minikube?

**Comment by dariuszbz** [comment]
I was not able to recreate minikube. I just shutdown the VM and create new
one 😄 since than never started the broken one.

**Comment by bnookala** [comment]
@dariuszbz I'll close this issue for now, but if it is still causing trouble, please let us know :)
