### ISSUE TITLE
Right click scale functionality for deployments and stateful-sets

### ISSUE THREAD

**Issue by kapodes** [Azure/vscode-kubernetes-tools#587]
It would be nice if I could scale my deployments and stateful-sets right from UI. 
I propose adding "right-click" menu item that would say `scale` and after clicking it and entering a number a scale for that resource would trigger.

We have a lot of similar stuff for PODs like port-forward and terminal but no scaling :(

**Comment by itowlson** [comment]
Good point.  We have the Scale command on the command palette, but it dates from before the explorer, and never got added to the right-click.  Sorry for overlooking that and thanks for flagging it!
