### ISSUE TITLE
Follow logs webview not autoscrolling

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#593]
Per https://github.com/Azure/vscode-kubernetes-tools/issues/460#issuecomment-516176958, the Follow Logs webview is not autoscrolling as new logs arrive.

cc @brendandburns - I am happy to tackle this if you want though

**Comment by itowlson** [comment]
@finsterdexter I'm looking at this issue now and would value thoughts on the desired behaviour.  Presumably if you have found an interesting log and scrolled to it, you do _not_ want the next log message in Follow mode to cause the view to scroll back to the bottom?  So should the rule be (in Follow mode):

1. If the user has not scrolled up, keep the view tracking the most recent log messages.
2. If the user has scrolled up, do not scroll automatically - continue to append logs but leave the scroll position where it is.
3...? (maybe) If the user has scrolled up but has since scrolled back to the end, resume tracking?

Thoughts?

**Comment by finsterdexter** [comment]
For my use case, what you outline there is exactly what happens in iterm and the vscode terminal, so that makes sense to me.

**Comment by bfitzpat** [comment]
May I propose this simple solution we came up with locally? It may not be the cleanest solution but may offer a route for you to explore. https://github.com/Azure/vscode-kubernetes-tools/pull/704

**Comment by theoharr** [comment]
Any update on this one? The follow logs function isn't really usable without the autoscrolling.

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/704 was merged and it is now part of the new version 1.2.1. Feel free to reopen this if you still face any problem with the autoscrolling :)
