### ISSUE TITLE
Unable to load schema from 'kubernetes://schema/monitoring.coreos.com/v1@prometheusrule': No content.

### ISSUE THREAD

**Issue by branttaylor** [Azure/vscode-kubernetes-tools#596]
Issue Type: <b>Bug</b>

Opened a .yaml file and I'm getting this error at the top of the file, and the file path is red:

Unable to load schema from 'kubernetes://schema/monitoring.coreos.com/v1@prometheusrule': No content.

Extension version: 1.0.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by itowlson** [comment]
Thanks for reporting this.  Does the `.yaml` file include a line of the form `kind: <something>`?  Is the `<something>` a custom resource name?  We have a known bug (#584) around this I'm afraid...

**Comment by branttaylor** [comment]
Yes, the beginning of the file looks like this:
```
---
  apiVersion: "monitoring.coreos.com/v1"
  kind: "PrometheusRule"
  metadata: 
```
Thanks for the quick response!

**Comment by itowlson** [comment]
If the CRD includes a structural schema, _and_ the cluster publishes CRD schemas in its Swagger (which currently requires the `CustomResourcePublishOpenAPI` feature flag), then this should work as of 1.0.3.  If not, let me know and we can discuss other ways for users to bring in CRD schemas.

In any event, I still need to bugfix the message when we can't retrieve the schema.  Apologies for the delay on this.

**Comment by branttaylor** [comment]
I updated to 1.0.3 and it looks to be resolved now. Thanks!
