### ISSUE TITLE
NOTES.txt preview produce no output

### ISSUE THREAD

**Issue by moebius87** [Azure/vscode-kubernetes-tools#597]
If you try to launch the preview of the _NOTES.txt_ file nothing is shown.
This is exactly what happens when you run the command: `helm template -x templates/NOTES.txt myChart`
Instead, for this particular file, the expected behavior is what you would get by launching the command: `helm template -x templates/NOTES.txt myChart --notes`

**Comment by itowlson** [comment]
Thanks for spotting this!
