### ISSUE TITLE
Restore "old" follow logs (in a terminal)

### ISSUE THREAD

**Issue by coding2012** [Azure/vscode-kubernetes-tools#599]
Just a thought since there is a lot more power in using the cmd line for this action (even if it's just a kubectl command line - VSCode's integration made it easy to know what that cmd line is). Perhaps if the new web view is staying, maybe make the terminal method an option?

**Comment by itowlson** [comment]
Semi-related: #593 (this is a note to myself, not a comment to you @coding2012 - thanks for the feedback!).

**Comment by bnookala** [comment]
Fixed in master - next release will have this feature :)
