### ISSUE TITLE
Lint on maxUnavailable in rollingUpdate showing on correct numbers

### ISSUE THREAD

**Issue by shacharSilbert** [Azure/vscode-kubernetes-tools#618]
Issue Type: <b>Bug</b>

Looking at a deployed Deployment YAML file on Kubernetes, with:
maxSurge: 25%
maxUnavailable: 0

I get a lint error on the 0 in maxUnavailable although there shouldn't be:
Incorrect type. Expected "string".

Extension version: 1.0.4
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by itowlson** [comment]
Thanks for reporting this.  This looks like a mismatch between the OpenAPI schema reported by the cluster and what RedHat YAML is willing to treat as a string.  I'll investigate further and raise it upstream if necessary.

**Comment by itowlson** [comment]
@shacharSilbert I believe this is due to incorrect handling of the k8s `IntOrString` type by the Red Hat YAML extension.  I can try to patch this while we request an upstream fix, but at the moment I can't reproduce it in my dev environment.  Can you let me know what OS you're on and the version of the YAML extension you have installed, please?  I'm trying to isolate a repro scenario so I can verify a fix.  Thanks!

**Comment by shacharSilbert** [comment]
@itowlson I'm using MAC with latest

Extension data:
Name: YAML
Id: redhat.vscode-yaml
Description: YAML Language Support by Red Hat, with built-in Kubernetes and Kedge syntax support
Version: 0.5.3
Publisher: Red Hat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

VSC data:
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by itowlson** [comment]
Fix on its way (#636) - thanks for your patience!
