### ISSUE TITLE
Extension adds one additional curly brace in helm-related files

### ISSUE THREAD

**Issue by rtim75** [Azure/vscode-kubernetes-tools#620]
**vs-code-kubernets version: 1.0.4**
**vs-code version: 1.38.1**

When the extension is enabled hitting '{' key once creates '{}' as it should do. But, if I hit  '{' two times I get '{{}}}' which brakes every helm template and forces to manually remove that curly brace.

**Comment by xarek1986** [comment]
I found that with vscode v1.37.1 it works as it has to, but with vscode v1.38.1 it adds additional brace

**Comment by itowlson** [comment]
Sorry for the delay in replying to this - I've been away.  @xarek1986 thanks for the version info - this may be a regression (or the fix of a bug we inadvertently relied on!) in VS Code so I may need to flag it upstream to them.  Thanks all for reporting it!

**Comment by itowlson** [comment]
@rtim75 @xarek1986 Would you mind giving this a go with #623 and let me know if that fixes this issue as well as the one it cites, please?

**Comment by itowlson** [comment]
I believe #623 fixes this.

**Comment by xarek1986** [comment]
@itowlson Yes, it works, thank you, I guess this issue can be closed
