### ISSUE TITLE
[UI] "Cannot read property 'forEach' of undefined" when click "Refresh" button

### ISSUE THREAD

**Issue by dacapoday** [Azure/vscode-kubernetes-tools#627]
I click the kubernetes clusters view "Refresh" button. 
vscode show notic: "Cannot read property 'forEach' of undefined" when the cluster has been restart(means resource has been released) but old resource tree item not closed.

**Comment by itowlson** [comment]
Just to be clear - the issue arises when the cluster is offline (restarting) when you press Refresh - is that correct?

* Is the cluster expanded at this point?  Or does the error happen even if the cluster explorer is completely collapsed?
* Do you have any Kubernetes YAML documents open at this point?
* Once the cluster is back up again, does it work okay?

**Comment by dacapoday** [comment]
> Just to be clear - the issue arises when the cluster is offline (restarting) when you press Refresh - is that correct?

A:  the issue arises when the cluster is online (restart completed).

> * Is the cluster expanded at this point?  Or does the error happen even if the cluster explorer is completely collapsed?

    A: yes, the cluster expanded. and collapsed will not happen.

> * Do you have any Kubernetes YAML documents open at this point?

    A: no

> * Once the cluster is back up again, does it work okay?
    A: no

**Comment by dacapoday** [comment]
when pod is stop but click the refresh button.
![bug](https://user-images.githubusercontent.com/9378047/66549129-325a7200-eb75-11e9-8d19-56b35fb6a758.png)

**Comment by lstocchi** [comment]
I tried to reproduce it with different clusters without any success. @dacapoday are you able to replicate it with the new extension? Maybe it was solved somehow. Thanks

**Comment by dacapoday** [comment]
> I tried to reproduce it with different clusters without any success. @dacapoday are you able to replicate it with the new extension? Maybe it was solved somehow. Thanks

Problem has been solved

**Comment by lstocchi** [comment]
@dacapoday Thanks for having verified it.
