### ISSUE TITLE
Tool throws an error saying that the command isn't recognized when User Name has spaces in path

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/vscode-kubernetes-tools#637]
if you have a space in your user name like "c:\users\some body" the extension doesn't work correctly.

**Comment by itowlson** [comment]
Yikes, sorry about that!  I thought we had handled this everywhere but evidently not.  Does this happen everywhere or only on specific commands?  Is `kubectl` on your path, or did you install it using Install Dependencies or the infer versioning option?  Is the file/folder you're working on under your user profile (i.e. spaces in the path to the folder) or somewhere else without spaces?  Thanks!

**Comment by JohnGalt1717** [comment]
Just clicking on the icon on the left bar throws the error. Then hitting refresh on clusters also throws it. Help repros refresh doesn't seem to throw it.

**Comment by itowlson** [comment]
Thanks.  I'll get a user account set up and try to reproduce this.

**Comment by itowlson** [comment]
What's the location of:

* your `kubectl` binary
* your `kubeconfig` file

please?  There may actually be a bug in `kubectl` here (`kubectl config view` is showing an empty config when my config is under a directory with spaces in it) though it may be different from what you're running into...

**Comment by JohnGalt1717** [comment]
where kubectl returns nothing.  But it executes fine. It was installed with chocolaty.

there's also a copy in <userpath>/.azure-kubectl (which isn't on the path)

There also a copy of kubectl.exe in <userpath>/.vs-kubernetes\tools\kubectl (draft, helm, kubectl, and minikube are in there)

<userpath/.kube has a file named "config" in it that appears to be the kubeconfig file. There's also a config.vscode-k8s-tools-backup file in there.

None of these locations are on the path.

Also, the k8s extension in vs code prompted to install helm, k8s etc. and failed with this same error.

**Comment by itowlson** [comment]
Gotcha.  It sounds like the extension may be using the `kubectl` in `/.vs-kubernetes\tools\kubectl`, but just to confirm that, could you look in your VS Code settings (`Preferences: Open Settings (JSON)` command) and verify that the `vs-kubernetes.kubectl-path` setting points there?  Thanks!

**Comment by itowlson** [comment]
Is the specific error message of the form `'c:\users\some' is not recognized as an internal or external command, operable program or batch file.`, please?  I'm seeing that but want to check it's the same thing you're hitting.  Thanks!

**Comment by JohnGalt1717** [comment]
Yes, that's the error message.

Here's the paths:

    "vs-kubernetes": {
        "vs-kubernetes.helm-path": "<user dir>\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vs-kubernetes.minikube-path": "<user dir>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vs-kubernetes.kubectl-path": "<user dir>\\.vs-kubernetes\\tools\\kubectl\\kubectl.exe",
        "vs-kubernetes.draft-path": "<user dir>\\.vs-kubernetes\\tools\\draft\\windows-amd64\\draft.exe"
    },

Thanks!

**Comment by itowlson** [comment]
Thanks for reporting this - should be fixed by #638 which will hopefully go into a release in the next couple of days.

In the meantime you can work around this by moving `kubectl.exe` to a directory without a space, and changing the path appropriately in your VS Code settings.

**Comment by JohnGalt1717** [comment]
Awesome! Thanks!

**Comment by fedorzh** [comment]
I am getting exactly the same error with the path which contains an opening and closing bracket..

**Comment by Mabion** [comment]
@fedorzh I had the same problem - and found this thread looking for the solution.
Eventually resolved this by changing the complete settings.json for vs-kubernetes (in VS Code with Ctrl+, and then extensions Kubernetes).

Intially it looked like this:
```
{
    "vs-kubernetes": {        
        "vscode-kubernetes.kubectl-path.linux": "/home/mibo/.vs-kubernetes/tools/kubectl/kubectl",
        "vscode-kubernetes.minikube-path.linux": "/home/mibo/.vs-kubernetes/tools/minikube/linux-amd64/minikube",
        "vscode-kubernetes.helm-path.linux": "/home/mibo/.vs-kubernetes/tools/helm/linux-amd64/helm",
        "vscode-kubernetes.helm-path.windows": "C:\\Users\\<user dir>\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vscode-kubernetes.kubectl-path-windows": "C:\\Users\\<user dir>\\.vs-kubernetes\\tools\\kubectl\\kubectl.exe",
        "vscode-kubernetes.helm-path-windows": "C:\\Users\\<user dir>\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vscode-kubernetes.minikube-path-windows": "C:\\Users\\<user dir>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vs-kubernetes.knownKubeconfigs": [
            "C:\\Users\\<user dir>\\.kube\\config"
        ],
        "vs-kubernetes.kubeconfig": "C:\\Users\\<user dir>\\.kube\\config"
    },
    "terminal.integrated.defaultProfile.linux": "bash",
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "redhat.telemetry.enabled": false,
    "files.autoSave": "afterDelay"
}
``` 

and changed this to:

```
{
    "security.workspace.trust.untrustedFiles": "open",
    "vs-kubernetes": {
        "vs-kubernetes.namespace": "",
        "vs-kubernetes.kubectl-path": "",
        "vs-kubernetes.helm-path": "",
        "vs-kubernetes.minikube-path": "",
        "vs-kubernetes.kubectlVersioning": "user-provided",
        "vs-kubernetes.outputFormat": "yaml",
        "vs-kubernetes.kubeconfig": "",
        "vs-kubernetes.knownKubeconfigs": [],
        "vs-kubernetes.autoCleanupOnDebugTerminate": false,
        "vs-kubernetes.nodejs-autodetect-remote-root": true,
        "vs-kubernetes.nodejs-remote-root": "",
        "vs-kubernetes.nodejs-debug-port": 9229,
        "vs-kubernetes.dotnet-vsdbg-path": "~/vsdbg/vsdbg",
        "vs-kubernetes.local-tunnel-debug-provider": "",
        "checkForMinikubeUpgrade": true,
        "imageBuildTool": "Docker"
    }
}
``` 

**NOTE**: That using the "Set Kubeconfig" via the UI is not working anymore now
