### ISSUE TITLE
Kubernetes Config Linter Mistake

### ISSUE THREAD

**Issue by shreyu86** [Azure/vscode-kubernetes-tools#641]
Similar to #621 found that the linter used with this extension highlights (using latest version `1.0.6`)
```
spec:
  finalizers:
  - kubernetes
``` 
as mistake 
![image](https://user-images.githubusercontent.com/311217/67347370-b65a1580-f4f6-11e9-969c-7d1488bf7a20.png)
![image](https://user-images.githubusercontent.com/311217/67347391-c07c1400-f4f6-11e9-863d-06aaa2c22cfa.png)

Platform information:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

Kubernetes Config to Repro:

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-10-16T17:46:39Z"
  name: default
  resourceVersion: "154"
  selfLink: /api/v1/namespaces/default
  uid: e5bf187d-0718-412c-b763-d02fbd82ce92
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by itowlson** [comment]
Ugh, this might be another upstream problem.  I'll check the Swagger and see what it prescribes and how we can work around it.  Thanks for letting me know!

**Comment by shreyu86** [comment]
@itowlson Thanks for looking into this.

**Comment by itowlson** [comment]
The reason it is validating it at all is because it the k8s Go code declares it in a way that we understand to indicate an enum:

```
type FinalizerName string

const (
	FinalizerKubernetes FinalizerName = "kubernetes"
)

type NamespaceSpec struct {
	Finalizers []FinalizerName
}
```

I don't yet understand why it is objecting to what appears to be a perfectly legal _value_ of the enum!

**Comment by itowlson** [comment]
Possible error in the way we merge the enum values derived from Go into the k8s Swagger definitions:

```
  "io.k8s.api.core.v1.namespacespec": {
    "name": "io.k8s.api.core.v1.NamespaceSpec",
    "description": "NamespaceSpec describes the attributes on a Namespace.",
    "type": "object",
    "properties": {
      "finalizers": {
        "description": "Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/",
        "type": "array",
        "items": {
          "type": "string"
        },
        "enum": [
          "kubernetes",
          "foo"
        ]
      }
    }
  },
```

Pretty sure that `enum` needs to be within the `items` attribute (modifying `type: string`) rather than at the top level (modifying `type: array`)...

**Comment by itowlson** [comment]
cc @andxu

**Comment by itowlson** [comment]
Found it and fixed it - thanks for the report!
