### ISSUE TITLE
Install kubectl when not installed

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#67]
We should re-examine the user experience of the extension when a user does not have `kubectl` on their path. Currently, we raise an error and exit, but we should prompt the user if they'd like for us to install the CLI on behalf of them.

We can fetch the binary from https://storage.googleapis.com/kubernetes-release/

cc @squillace and @itowlson for any design considerations.

**Comment by itowlson** [comment]
I like this in principle, but are there any versioning issues here?  I've had weird results when the kubectl version is out of sync with the cluster.

We'd need to consider the download location.  We can either download it to some 'global' location (e.g. Program Files on Windows), or a user location.  The former would require admin/sudo, which pushes us towards under the user profile.  That's not a dealbreaker, but it may look a bit odd.

Another issue is pathing.  Suppose we add the kubectl directory to the system path.  Then the current instance of VS Code won't be able to find it.  But if we add the kubectl binary to the VS workspace settings, can we do that in a way that works for all projects?  (That should just be a matter of testing that putting it in the user settings works; I've only tested in the project settings.)

I think installing the latest version under the user profile directory and adding the path to the user settings would probably suit - does that sound like a good plan, or does it have its own undesirable consequences?

**Comment by itowlson** [comment]
Superseded by #118, will be addressed by #136 (which admittedly ignores versioning issues in the name of expediency).
