### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vic-marroquin** [Azure/vscode-kubernetes-tools#671]
[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/3948905/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.0.9`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by itowlson** [comment]
Thanks (and sorry for the slow reply - I've been on holiday).  We need to run a packing/pruning tool on the extension to reduce the startup load, but this is proving difficult - I have it 90% working but it's still a bit shonky.  Hope to make more progress on this now I'm back.

**Comment by lstocchi** [comment]
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue. Thanks!!
