### ISSUE TITLE
Is it posible to delete namespace in the context menu?

### ISSUE THREAD

**Issue by lamLeX** [Azure/vscode-kubernetes-tools#672]
Current there is no option to delete namspace from the context menu
![image](https://user-images.githubusercontent.com/4281894/70742865-61a37180-1cd3-11ea-8ce9-cf7a5518f34a.png)

Is it missing because of technical limitation?

**Comment by itowlson** [comment]
No, it's just that we didn't think to do it!  Seems like it would be consistent, though blowing away a whole namespace is higher impact than our normal resource deletion commands - I'll have to have a think about the user experience...

**Comment by itowlson** [comment]
Fixed via #700.
