### ISSUE TITLE
Intellisense needs updates

### ISSUE THREAD

**Issue by harshthakur9030** [Azure/vscode-kubernetes-tools#675]
I'm running a k8s cluster of version 1.17.0 in which the resource Deployment is no longer in extensions/v1beta1 , instead it lies in apps/v1 which the Intellisense didn't know about. It's not just the version but also extra fields like "selector" which were made mandatory to be added.

**Comment by itowlson** [comment]
Sorry for the slow reply on this - I've been on holiday.  This is a tricky one because some users will still be on older k8s versions, but I think `apps/v1` has been permitted long enough that it's safe to change!  I see @amirschw has already sent a PR for this - I will review and merge asap.

**Comment by amirschw** [comment]
Thanks @itowlson. Deployment's API was promoted to `apps/v1` in kubernetes version 1.9 so I figured it's safe to change :)

**Comment by harshthakur9030** [comment]
To solve the versioning issue , I think it would be better if we relied on the API to give out the fields required. What I mean is: when we do a kubectl explain RESOURCE , we know which fields are required. Would like to know your thoughts on this
