### ISSUE TITLE
Move Ingress and Secret snippets from Helm language to regular K8s as well

### ISSUE THREAD

**Issue by alexkreidler** [Azure/vscode-kubernetes-tools#677]
Right now the extension contributes both the `Ingress` and `Secret` snippets in the `helm` language, but they are not in the regular k8s YAML snippets. This is frustrating b/c when I'm switching between environments I expect the same snippets to be available, just modified to work for Helm or not.

https://github.com/Azure/vscode-kubernetes-tools/blob/127ec070c8dabd56901ce13ff81bd6f561e4f087/snippets/helm.json#L60-L66

We should move those snippets so the snippets this extension provides are more unified. 

I'd be happy to do this soon if I get a go-ahead from a maintainer.

Otherwise, awesome extension! Thanks to all!

**Comment by itowlson** [comment]
This sounds like a great point and we'd be delighted if you could send a PR for it.  Thanks!  (And sorry for the slow reply - I've been away.)

**Comment by lstocchi** [comment]
Closing it as we added more snippets (included secret and ingress) with https://github.com/Azure/vscode-kubernetes-tools/pull/825. Feel free to re-open this issue if that does not fully solve your request. Thanks!!
