### ISSUE TITLE
Follow Logs with a Match Expression receives updates that do not match

### ISSUE THREAD

**Issue by mipnw** [Azure/vscode-kubernetes-tools#683]
- In VSCode Kubernetes extension, click on a Pod and select "Follow Logs"
- A VS code tab opens with the selected log
- Set Show logs: "that don't match" 
- Set Match Expression "an expression"
- At that point note the tab is redrawn to match the "does not match an expression". So far so good.
- Do something on your pod that would log "an expression"
- Witness that new log entry appears in followed log tab.

**Comment by itowlson** [comment]
Thanks for flagging this - we'll take a look.

cc @brendandburns

**Comment by theoharr** [comment]
I can confirm this is still an issue in the current version

```
ms-kubernetes-tools.vscode-kubernetes-tools@1.1.1
```

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/727 was merged. Feel free to reopen it if you still face this issue once this fix will be published. Thanks
