### ISSUE TITLE
"Unable to list helm repos" -- enhancement request

### ISSUE THREAD

**Issue by DaveWK** [Azure/vscode-kubernetes-tools#684]
When using the kubernetes extension in vscode I get the message:

"Unable to list helm repos"

I do have helm repos on my cluster, which is displayed.

This doesn't really tell me why it can't display them, or provide me with a "call to action" of how to fix it.

VSCode is a tool for developers and I think most devs would rather just see a raw error message than a vague statement, or at least a way to click and display the message.

**Comment by itowlson** [comment]
There should be a hover message if you hover over the "Unable to list Helm repos" tree item.  If there isn't, that's a bug - let me know and I'll investigate.

I'd love thoughts on how to make this more discoverable, though I don't want to clog the tree display with a full error message.  Right-click > `Show Error Details` or something like that maybe?

**Comment by DaveWK** [comment]
Ah ok, I think I see what my issue was -- so I (out of habit) usually click on the message when I see it, or am using tab and end up using the keyboard to nav to that frame. When the message is highlighted/clicked it does not display that pop-up.  Right-click > Show Error Details would be good, as well as possibly when the message has the cursor hover it should also underline the text, and when clicked display the pop-up with an "x" to close it out?

**Comment by jcowhigjr** [comment]
the brew package of helm 3.1 on a mac installs the repo preferences with the repo locations $HOME/Library/Preferences/helm 
also there is no helm init command as the hover message indicates

**Comment by lstocchi** [comment]
@jcowhigjr sorry for the late response. Not sure if you solved this but the hover message is printed by heml itself. If you see that error message it is likely that the helm you are using is older than v3 (from v3 tiller is not used anymore and the init command has been removed so you should see a different message like `No repositories to show`).
To make the extension use your new heml 3.1 you have to change the path in the settings `vs-kubernetes.helm-path`

**Comment by lstocchi** [comment]
@itowlson I can work on this but i need to know what is the plan here. I think the options are: 
1. Right-click > Show Error Details -> open a MessageBox with details
2. Allow to click on the item and open a MessageBox with details
3. Both 1 and 2
4. ???

I have no preference. My initial idea was to add an icon to the right of the item with a `!` so user would be forced to hover that but i don't think it is possible so ..... if i should vote i would go on 2.

**Comment by itowlson** [comment]
@lstocchi Thanks! Either 1 or 2 is fine, so if you prefer 2 then go for that.  Maybe in that case put 'Click for details' in the hover message too?
