### ISSUE TITLE
Make kubeconfig configurable for extension

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#69]
If supplied, we should use the location of a kubeconfig supplied by the user for extension commands and cluster configuration.

The library we use for invoking `kubectl` commands, shelljs, allows one to inject custom environment variables. Here, we can set `KUBECONFIG` to whatever the user supplies in their extension configuration: https://github.com/shelljs/shelljs#envvar_name

This may also solve #63. 

cc @itowlson, @squillace for technical considerations.

**Comment by itowlson** [comment]
One niggly detail with this is that if a user were to set a kubeconfig file, then Add Existing Cluster should add it to that kubeconfig file, not to the default one.  Looking at the Azure CLI, this may require specific handling for each cluster provider - it doesn't look like `az aks get-credentials` respects `KUBECONFIG` though I haven't tested it...

**Comment by itowlson** [comment]
See #206.

**Comment by itowlson** [comment]
Fixed via #206.
