### ISSUE TITLE
Bootstrap auto versioning

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#690]
If `kubectl-versioning` is `infer`, the Install Dependencies command assumes that `kubectl` will be available when needed, and so thinks it doesn't need to install it.  This is a false assumption, because we need a `kubectl` to work out the server version in order to download the right `kubectl`.

Install Dependencies should install a bootstrap version of `kubectl`, or auto versioning should handle not having a bootstrap version and, er. bootstrap it.

**Comment by bnookala** [comment]
@itowlson I love circular dependencies!!
