### ISSUE TITLE
Extension causes high CPU load

### ISSUE THREAD

**Issue by uc-msft** [Azure/vscode-kubernetes-tools#693]
[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/4169257/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)

Issue Type: Performance
Extension Name: vscode-kubernetes-tools
Extension Version: 1.09
OS Version: Windows_NT x64 10.0.19559
VSCode version: 1.42.0 (user setup)

**Comment by lstocchi** [comment]
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue.
