### ISSUE TITLE
add "delete namespace"

### ISSUE THREAD

**Issue by bradygaster** [Azure/vscode-kubernetes-tools#696]
I mentioned this to @squillace, who advised I create an issue. The one thing I'd like to see added to the extension (which is **amazingly awesome**, btw), is right-click-delete support for namespaces. Ideally, it would bark when the user tried it on a non-empty namespace, advising them to clear out said namespace prior to deletion. But for dev/test it'd be rad to have the delete namespace capability so customers who are rapidly testing out environmental configuration and deployment could blow away their unused namespaces once they're empty. 

Love the extension - literally makes K8S development with .NET a breeze. I wish more people knew about it!

**Comment by itowlson** [comment]
Yes, this omission feels artificial.  I'll take a look - thanks!
