### ISSUE TITLE
Reduce or hide panels

### ISSUE THREAD

**Issue by LeNouveau** [Azure/vscode-kubernetes-tools#703]
Hi, 

With the plugin, I'm only using the panel "Clusters". 
Every time I start a new instance, I have to reduce "Helm Repos" and "Clouds", because I have a lot of configured namespaces. 
This is not much, but it would be useful to hide/reduce those tabs, once for all. 

I looked for an option in the config file, but I found nothing. 

Is there any trick ? 

PS : In my case, I'm only using the plugin to browse our environments. I don't generate/update applications. That why I'm not using the other tabs.

**Comment by itowlson** [comment]
If you right-click the title bar and choose `Hide`, or uncheck the panel you don't want to see, VS Code appears to remember this across sessions.  Give this a go, and let me know if it doesn't work for you and I will do some more digging!

![image](https://user-images.githubusercontent.com/865538/74618051-09866100-5195-11ea-8092-76caa1781dec.png)

**Comment by LeNouveau** [comment]
You're right, looks like what I'm looking for. 
I did not try to use "right click" on panels. 

Thank your for the information ! :)
