### ISSUE TITLE
Extension causes high CPU load

### ISSUE THREAD

**Issue by a-h-abid** [Azure/vscode-kubernetes-tools#706]
[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/4248159/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)

Issue Type: Performance
Extension Name: vscode-kubernetes-tools
Extension Version: 1.09
OS Version: Windows 10 Enterprice x64 Build 1909
VSCode version: 1.42.1 (user setup)

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
