### ISSUE TITLE
Kubernetes denying permission

### ISSUE THREAD

**Issue by lslavkov** [Azure/vscode-kubernetes-tools#713]
I have permission to one OpenShift project but I am unable to interact with the project in VSCode. I get an error: 

`Error from server (Forbidden): namespaces is forbidden: User cannot list namespaces at the cluster scope: no RBAC policy matched`

I do not care about listing all namespaces. I only want to work with one namespace where I do have permissions.

Is this expected error?

**Comment by jiridanek** [comment]
@lslavkov Can you comment here if the OpenShift Connector extension worked for you?

**Comment by lslavkov** [comment]
@jiridanek I just checked if does this have dependency. Since I got on my machine Openshift 3.X version I need either [minishift](https://github.com/minishift/minishift) or [cdk](https://developers.redhat.com/products/cdk/download).

**Comment by jiridanek** [comment]
That sounds wrong. You should be able to connect it to existing deployed cluster somehow. Same as the Kubernetes for vscode one.

**Comment by gorkem** [comment]
OpenShift Connector should work with **any** OpenShift cluster 3.x, 4.x. If it does not it is a bug report it on https://github.com/redhat-developer/vscode-openshift-tools

**Comment by jiridanek** [comment]
@lslavkov Can you ready to close this issue please, since you are ok with the resolution?
