### ISSUE TITLE
Cloud Explorer > Merge to Kubeconfig should handle if kubeconfig doesn't exist

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#715]
In this case it should:

* Create a kubeconfig file at the default location
* Merge the cluster config into the empty file
* Make the cluster active

before refreshing the Cluster Explorer.

cc @bradygaster

**Comment by bradygaster** [comment]
Will try this out!

**Comment by bradygaster** [comment]
Worked like a champ. I went from a GitHub repo to having the extension lit-up-and-ready in 30 seconds. Within two minutes I was successfully executing `apply` commands on an AKS cluster using the tools. Fantastic.
