### ISSUE TITLE
Extension is not working with the Latest Version of Azure CLI - 2.2.0 or later

### ISSUE THREAD

**Issue by Evilazaro** [Azure/vscode-kubernetes-tools#718]
When I try to add a new cluster in the Kubernetes tools window, I got the error below:

![image](https://user-images.githubusercontent.com/20006379/77353655-99707b00-6cfe-11ea-8425-60e8689d4431.png)

I'm using Windows and I did not find a way to install a specific version of the Azure CLI, just the latest one.

**Comment by itowlson** [comment]
Hmm, that seems to be a warning coming from the Azure CLI `interactive` extension, which we are incorrectly treating as an error.  If you are not using the `interactive` extension to the CLI, could you try uninstalling it using `az extension remove` please, and see if the problem goes away?  Thanks!

**Comment by Evilazaro** [comment]
I've removed the interactive extension and now it is working, thanks.

**Comment by itowlson** [comment]
Closing as this was an Azure CLI issue where the error message was misleading, and is now resolved, but this may imply we are being oversensitive to errors-that-are-actually-warnings...
