### ISSUE TITLE
Kubernetes: Debug (Attach) prompts to install for c#

### ISSUE THREAD

**Issue by trhumphries** [Azure/vscode-kubernetes-tools#719]
It prompts to install C# for Visual Studio Code even when its already installed. And won't attach to a Dotnet process

**Comment by itowlson** [comment]
I think this might be because the C# extension changed its ID.  If so, this is fixed in #710 but it hasn't been shipped yet.  I will prioritise doing a new release to address this.

**Comment by trhumphries** [comment]
Any estimated ETA on the new release?

**Comment by itowlson** [comment]
Oops, sorry, should have posted.  A release went out yesterday that includes @devlead's change.  Check if you have 1.1.1; if you still have the problem with that version then let us know and we will investigate.

**Comment by lstocchi** [comment]
@trhumphries is this issue solved?

**Comment by trhumphries** [comment]
Yes it is
