### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#728]
Currently the release process for the extension is:

* I go "what ho, I think I'll do a release"
* I create a publish-x.x.x branch to update the version and the changelog (and any other docs etc. that didn't get updated in the course of the feature work)
* I build a VSIX locally and do some smoke testing
* I create a PR and merge the publish branch
* I pull upstream/master, build a VSIX locally and do another smoke test
* I create a release using the GitHub UI and drag the VSIX onto the release form
* I run `vsce publish` to push the VSIX to the marketplace

Yeah, I know.  Don't judge me.

This is, to say the least, highly manual and highly dependent on me not borking my local environment.  It would be good if we could automate this to something like:

* "What ho"
* Create publish-x.x.x branch, test locally, create PR [still manual]
* Possibly GH runs a few additional sanity checks e.g. making sure that `package.json` and `changelog.md` are updated **[automated]**
* Merge pull request [still manual]
* GitHub builds the VSIX **[automated]**
* GitHub creates a release using the version number from `package.json` **[automated]**
* GitHub pushes VSIX to marketplace **[automated]**

Longer term we should figure out how to smoke test as part of the automated checks on PRs, but this will be tough given the amount of interactivity and dependencies...

**Comment by dcermak** [comment]
>     * "What ho"

Not sure if this can be automated :wink:

> 
>     * Create publish-x.x.x branch, test locally, create PR [still manual]
> 
>     * Possibly GH runs a few additional sanity checks e.g. making sure that `package.json` and `changelog.md` are updated **[automated]**
> 
>     * Merge pull request [still manual]
> 
>     * GitHub builds the VSIX **[automated]**

A standard github action should be able to do this.

> 
>     * GitHub creates a release using the version number from `package.json` **[automated]**

This could be automated via https://github.com/actions/create-release and https://github.com/actions/upload-release-asset

> 
>     * GitHub pushes VSIX to marketplace **[automated]**

This can be achieved using this github action: https://github.com/HaaLeo/publish-vscode-extension

**Comment by lstocchi** [comment]
Closing it as we have already automated the release process.
