### ISSUE TITLE
kubectl plugin doesn't work for k8s.extension.kubectl.v1

### ISSUE THREAD

**Issue by raushan2016** [Azure/vscode-kubernetes-tools#730]
I am trying to use the kubectl plugin [kubectl-tree](https://github.com/ahmetb/kubectl-tree)
```
const obj = await kubectl.api.invokeCommand(`tree -A ${treeNode.resourceKind.manifestKind} ${treeNode.name}`);
```
But it keeps complaining 
```
Error: unknown command "tree" for "kubectl"
Run 'kubectl --help' for usage.
unknown command "tree" for "kubectl"
```

**Comment by itowlson** [comment]
Very strange.  I'm trying the same sort of thing (albeit just calling `tree --help`) and it seems to be working okay for me...

```javascript
        const sr = await k.api.invokeCommand('tree --help');
        if (!sr || sr.code !== 0) {
            vscode.window.showErrorMessage(sr ? sr.stderr : 'oof');
            return;
        }
        vscode.window.showInformationMessage(sr.stdout);
```

**Comment by itowlson** [comment]
Hi @raushan2016, thanks for being willing to help diagnose this.  Could you make the following changes to the `vscode-kubernetes-tools` `extension.ts` file please:

**Immediately above the `activate` function (around line 120-130):**

* Add the line `let APIB: APIBroker | null = null;`

**At the end of the `activate` function (around line 390):**

* Replace the `return` statement with:

```
    APIB = apiBroker(clusterProviderRegistry, kubectl, portForwardStatusBarManager, treeProvider, cloudExplorer);
    return APIB;
```
**In the `getKubernetes` function (around line 780):**

* Mark the function `async`
* Replace the function body with:

```
    const k = APIB!.get('kubectl', 'v1') as API<KubectlV1>;
    if (!k.available) {
        vscode.window.showErrorMessage('wtf');
        return;
    }

    const sr = await k.api.invokeCommand('tree --help');
    if (!sr || sr.code !== 0) {
        vscode.window.showErrorMessage(sr ? sr.stderr : 'oof');
        return;
    }
    vscode.window.showInformationMessage(sr.stdout);
```

* Apply all necessary quick fixes to resolve missing imports

Then place a breakpoint on the `invokeCommand` call and trace it inward to the `execCore` function in `shell.ts`.  Hopefully something in there (maybe the PATH environment variable in the `opts` argument?) will look fishy...  Thanks!

**Comment by itowlson** [comment]
Umm, forgot to say, run `Kubernetes: Get` from the command palette to trigger the hacky debugging code!

**Comment by itowlson** [comment]
Looks like this may be an OS-dependent issue - it seems to happen on Linux but not Windows.

**Comment by raushan2016** [comment]
Somehow the plugin was not available in PATH. Did bunch of restart and reload and its working now. We can close the issue.

**Comment by itowlson** [comment]
Thanks for the update and for closing this off!
