### ISSUE TITLE
resolveCommandTarget doesn't populated all the fields like metadata, resourceKind.apiName

### ISSUE THREAD

**Issue by raushan2016** [Azure/vscode-kubernetes-tools#731]
I have a resourceFolder defined like below. When my trigger my command for well known resource like `deployment` everything is populated. But when the same command is triggered for resource in the defined resourceFolder, it has **metadata** as `undefined` and **resourceKind.apiName** also as `undefined`

```
	clusterExplorer.api.registerNodeContributor(
		clusterExplorer.api.nodeSources.groupingFolder("foo", undefined,
			clusterExplorer.api.nodeSources.resourceFolder("bar", "Bars", "Bae", "bars", ))).at(undefined));  

let disposable = vscode.commands.registerCommand('vscode-k8s-foo.show',(resource)=>{
const treeNode = clusterExplorer.api.resolveCommandTarget(resource);
var metadata = treeNode.metadata;
var apiName = treeNode.resourceKind.apiName;
});
```

**Comment by itowlson** [comment]
`apiName` should be fixed in the Cluster Explorer 1.1 API (merged but not yet published.  Working on ensuring `metadata` is always defined.
