### ISSUE TITLE
Kubernetes: Start minikube fails

### ISSUE THREAD

**Issue by adriantorrie** [Azure/vscode-kubernetes-tools#732]
Error that pops up on VS Code:
`Command 'Kubernetes: Start minikube' resulted in an error (Cannot read property 'toLowerCase' of undefined)`

Within my `settings.json` I have the following (`<user>` is just a placeholder for this code snippet):
```json
    "vs-kubernetes": {
        "vs-kubernetes.minikube-path.windows": "C:\\Users\\<user>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vs-kubernetes.helm-path.windows": "C:\\Users\\<user>\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vs-kubernetes.draft-path.windows": "C:\\Users\\<user>\\.vs-kubernetes\\tools\\draft\\windows-amd64\\draft.exe"
    },
```
But if I call `minikube start` from terminal it works, using the path found in `settings.json`:
```sh
$ C:\\Users\\<user>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe start
😄  minikube v1.9.2 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
✨  Automatically selected the docker driver
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=8100MB (12236MB available) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

❗  C:\Program Files\Docker\Docker\resources\bin\kubectl.exe is v1.15.5, which may be incompatible with Kubernetes v1.18.0.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version
```

![image](https://user-images.githubusercontent.com/3909039/79285754-cf6ddd00-7f01-11ea-8de7-8068db6169cf.png)

**Comment by itowlson** [comment]
Thanks - will take a look!

**Comment by itowlson** [comment]
What is the output if you run `C:\\Users\\<user>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe status`?  Looks like the error you see could happen when we try to parse the result of that...

**Comment by Keksparade** [comment]
Same for me running on Linux: I (more or less) get the same error message for start, stop and status:
Error running command extension.vsMinikubeStop: Cannot read property 'toLowerCase' of undefined. This is likely caused by the extension that contributes extension.vsMinikubeStop.

Output of `minikube status`

```
m01
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped
```

My version of VS Code:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic
```

**Comment by lstocchi** [comment]
I'm able to replicate it on Linux... I never noticed it as i always start minikube from the terminal but it fails here 
`const hostStatus = result.stdout.split('\n')[0].split(': ')[1].toLowerCase();`
The first line is m01 so it fails when trying to get the first item after the second split.

**Comment by adriantorrie** [comment]
> What is the output if you run `C:\\Users\\<user>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe status`? Looks like the error you see could happen when we try to parse the result of that...

Pre manual start via terminal:

```sh
$ C:\\Users\\<user>\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe status
m01
host: Stopped      
kubelet: Stopped   
apiserver: Stopped 
kubeconfig: Stopped
```

Post manual start via terminal:

```sh
$ C:\\Users\\adria\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe status
m01
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```
