### ISSUE TITLE
Cannot set kubeconfig file in Cluster.

### ISSUE THREAD

**Issue by abishD** [Azure/vscode-kubernetes-tools#741]
Issue Type: <b>Bug</b>

With the latest update in VS Code to 1.44.2, I cannot set the kubeconfig file. This was not an issue in VS Code 1.44.0/1

Steps to reproduce,
1) In the Kubernetes extension, open the cluster tray.
2) Hover on the left side of the cluster bar, click on the three hortizontal icons
3) Select the 'Set Kubeconfig' option, No options arises to actually set the file.

This is only reproducible on a Windows Machine, Did not face it on Mac OS.

Extension version: 1.1.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by raushan2016** [comment]
Looks like when we click on `Set Kubeconfig`, in the vscode settings `vs-kubernetes.kubeconfig` gets a json value rather than a string.
```
    "vs-kubernetes": {
        "vs-kubernetes.kubeconfig": {
            "isTrusted": true
        }
    }
```

@abishD I mitigated it by manually removing this and manually adding the kubeconfig file path in the settings.json.

![vscodeissue](https://user-images.githubusercontent.com/44377286/80050750-05b0eb00-8506-11ea-9822-a090ebfd1e37.gif)

**Comment by itowlson** [comment]
This is super weird.  Looks like VS Code is invoking the command handler with an object of the form `{ isTrusted: true }` when previously it passed nothing.  Why would it suddenly start doing that?  So strange!

**Comment by itowlson** [comment]
Looks like an unintended change in VS Code (though other people report it in 1.44.0 as well).  @abishD  I don't know when/if the Code folks will fix it - I will add a patch but for now please use @raushan2016's workaround.  https://github.com/microsoft/vscode/issues/94872

**Comment by abishD** [comment]
Thank you @raushan2016, that was a good catch. I was able to set the kubeconfig manually via the settings.json as you mentioned.

Thank you @itowlson for linking & reporting it. This works for me so that's alright.
