### ISSUE TITLE
Extension causes high CPU load

### ISSUE THREAD

**Issue by TBBle** [Azure/vscode-kubernetes-tools#743]
Issue Type: <b>Performance Issue</b>

Just on startup

Extension version: 1.1.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.42GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	  5640	code main
    7	   149	  5488	   gpu-process
    3	    61	  7088	   window (Issue Reporter)
    0	    25	 12804	   utility
    0	    14	 13100	   electron-crash-reporter
    0	   203	 22136	   window (kepler-cluster.eksctl.yaml - AWSPerfect - Visual Studio Code)
    0	    14	 14472	     watcherService 
    0	    11	 17332	       console-window-host (Windows internal process)
    0	   267	 20020	     extensionHost
    0	    33	 17908	       electron_node server.js 
    0	    36	 20244	       electron_node server.js 
    0	    30	 21008	       electron_node server.js 
    0	    35	 20508	     searchService
   28	    77	 22276	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (kepler-cluster.eksctl.yaml - AWSPerfect - Visual Studio Code)
|    Folder (AWSPerfect): 3514 files
|      File types: py(1385) pyc(1381) pyd(52) txt(32) exe(23) html(13) htm(13)
|                  gif(9) yaml(7) dll(7)
|      Conf files: settings.json(1);
```

</details>

[ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt](https://github.com/Azure/vscode-kubernetes-tools/files/4521108/ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt)

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
