### ISSUE TITLE
Can't Use 'Preview Template' with Helm 3 / "Failed template call Error: unknown flag: --execute"

### ISSUE THREAD

**Issue by tedohayer** [Azure/vscode-kubernetes-tools#747]
I'm unable to use 'Preview Template' in Helm 3.2.0. According to [this issue](https://github.com/helm/helm/issues/5887) the `--execute` flag was removed in Helm 3 and replaced with `--show-only`. 

The normal 'Helm Template' option works, I just prefer the preview window.

**Comment by itowlson** [comment]
Hmm, when I asked the Helm folks about this, they told me that `execute` had been removed, not just renamed.  Maybe they brought it back later in the dev cycle under the `--show-only` name.  @bacongobbler can you shed any light please?

**Comment by bacongobbler** [comment]
The latter :) it was re-introduced as `--show-only`. The internals were refactored, but the input and output remains the same.

To further clarify, -execute would render only the specified template. This caused design issues when other template files defined helper templates. -show-only now renders the entire chart, but only displays the specified rendered templates as output. The net result is the same I/O, but it fixed a few edge cases with the -execute flag.
