### ISSUE TITLE
Fake error message "Error creating cluster"

### ISSUE THREAD

**Issue by akaroml** [Azure/vscode-kubernetes-tools#75]
When I tried to create a k8s cluster using the wizard:
![image](https://user-images.githubusercontent.com/16755094/37131548-c95b2edc-22c3-11e8-8183-6548676ee1c1.png)

I got the following error at the end:
![image](https://user-images.githubusercontent.com/16755094/37131451-6e25d882-22c3-11e8-9ff1-31ab1df9007c.png)

But later I tried to see whether the new cluster is created using:
![image](https://user-images.githubusercontent.com/16755094/37131572-e6267d82-22c3-11e8-8825-3c9a21dc0683.png)

I successfully configured the cluster to my local registry. And I can operate on the nodes:
![image](https://user-images.githubusercontent.com/16755094/37131594-045d25e4-22c4-11e8-9374-f9ebef5e4554.png)

Not sure what the error message was about but seems like it should not be there.

**Comment by itowlson** [comment]
That's weird.  It's like we're picking up a progress message as an error message.  Not sure how to reproduce this one - does it happen consistently for you?

**Comment by akaroml** [comment]
Yes, tried to create another cluster and the error persists:
<img width="378" alt="screen shot 2018-03-09 at 11 13 36 am" src="https://user-images.githubusercontent.com/16755094/37188631-23ba77bc-238b-11e8-848e-ae13482367d1.png">

But later the cluster can be configured successfully:
<img width="373" alt="screen shot 2018-03-09 at 11 15 29 am" src="https://user-images.githubusercontent.com/16755094/37188654-3e5eb57e-238b-11e8-8c8f-5fca32992c0d.png">

**Comment by akaroml** [comment]
Ok, here is some further info:
Region: Central US
Node type: Standard D2 v2
Node count: 2
Kubernetes version: 1.7.9
Azure CLI Version: 2.0.28

I also noticed some errors in activity log:
```json
{
    "authorization": {
        "action": "Microsoft.ContainerService/managedClusters/write",
        "scope": "/subscriptions/ffa52f27-be12-4cad-b1ea-c2c241b6cceb/resourceGroups/romlk8s/providers/Microsoft.ContainerService/managedClusters/romlk8s"
    },
    "caller": "roml@microsoft.com",
    "channels": "Operation",
    "claims": {...
    },
    "correlationId": "2d988027-b82f-41de-98cb-33427f94cb26",
    "eventDataId": "c2914a36-5dd7-4bc9-885e-bcbf84350a75",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2018-03-08T03:14:46.6334217Z",
    "id": "/subscriptions/ffa52f27-be12-4cad-b1ea-c2c241b6cceb/resourceGroups/romlk8s/providers/Microsoft.ContainerService/managedClusters/romlk8s/events/c2914a36-5dd7-4bc9-885e-bcbf84350a75/ticks/636560756866334217",
    "level": "Error",
    "operationId": "2d988027-b82f-41de-98cb-33427f94cb26",
    "operationName": {
        "value": "Microsoft.ContainerService/managedClusters/write",
        "localizedValue": "Microsoft.ContainerService/managedClusters/write"
    },
    "resourceGroupName": "romlk8s",
    "resourceProviderName": {
        "value": "Microsoft.ContainerService",
        "localizedValue": "Microsoft.ContainerService"
    },
    "resourceType": {
        "value": "Microsoft.ContainerService/managedClusters",
        "localizedValue": "Microsoft.ContainerService/managedClusters"
    },
    "resourceId": "/subscriptions/ffa52f27-be12-4cad-b1ea-c2c241b6cceb/resourceGroups/romlk8s/providers/Microsoft.ContainerService/managedClusters/romlk8s",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },
    "submissionTimestamp": "2018-03-08T03:15:00.1113487Z",
    "subscriptionId": "ffa52f27-be12-4cad-b1ea-c2c241b6cceb",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": "96dd9cbd-8096-4f68-b242-a6b7be91adc8",
        "statusMessage": "{\"code\":\"ServicePrincipalNotFound\",\"message\":\"Service principal clientID: f50c07ad-0178-4670-a523-deecf6fbaaad not found in Active Directory tenant 72f988bf-86f1-41af-91ab-2d7cd011db47, Please see https://aka.ms/acs-sp-help for more details.\"}"
    },
    "relatedEvents": []
}
```

**Comment by itowlson** [comment]
I wonder if the Azure CLI must be writing to standard error even when it succeeds.  (We rely on checking stderr because the exit code is not reliable.)  I've seen this very intermittently on Windows; perhaps it happens more frequently on Mac.  Or perhaps the CLI is prematurely reporting an error but the operation has already been successfully kicked off in ARM.

If you do the corresponding `az aks create` from the command line, what do you see?

**Comment by itowlson** [comment]
I've noticed I often see "Retrying role assignment creation" during some of these operations on the CLI.  I wonder if that's being printed to stderr and that's throwing us off (because although it had to retry, the retry eventually succeeded).  That would be consistent with the SP-related message you see, where perhaps this is trying to overwrite the retry with a progress message... _waves hands handwavily_

**Comment by kyliel** [comment]
I also met this issue. And no such a problem when creating an AKS cluster in Azure CLI.
