### ISSUE TITLE
Kubernetes command failed

### ISSUE THREAD

**Issue by gildas** [Azure/vscode-kubernetes-tools#770]
I use kubectl on my Linux Mint box via snap.
I run microk8s (still via snap) locally as well as using remote k8s clusters (Azure, Docker for Mac remotely, etc).
I run helm also via snap.
So, my snap list looks like (snippet):
```console
Name                   Version                     Rev   Tracking       Publisher              Notes
code                   a5d1cc28                    34    latest/stable  vscode✓                classic
core                   16-2.45                     9289  latest/stable  canonical✓             core
docker                 19.03.11                    471   latest/stable  canonical✓             -
helm                   3.2.3                       244   latest/stable  snapcrafters           classic
kubectl                1.18.3                      1534  latest/stable  canonical✓             classic
microk8s               v1.18.3                     1443  latest/stable  canonical✓             classic
```
Note that I have a `~/.kube/config` with several clusters, all work fine from the shell.

I decided to give `vscode-kubernetes-tools` a spin.
After installation when you click on the extension logo in the Activity Bar, the list of clusters, helm repos, and clouds stay empty (I saw the little progress bar running for each for a few seconds); a toaster popped up saying only: `Kubectl command failed:` without any explanation whatsover.

I looked at the `Output` view in the `Log (Extension Host)` and nothing either.

Not sure where to look for information and reasons why the extension believes it cannot run `kubectl`

**Comment by lstocchi** [comment]
Thanks for opening this issue @gildas. We received other issues similar to this and it seems that VSCode installed with snap comes with some permissions problem. I wasn't able to replicate it before but i never tried with Linux Mint. I'll let you know if i find a solution to this.

**Comment by lstocchi** [comment]
@gildas I was able to replicate it and i think i have a fix (#771) . Would you please try it and see if it works for you?

You can install the extension by using a vsix file.
I created it (download link: https://github.com/lstocchi/vscode-kubernetes-tools/raw/master/vscode-kubernetes-tools-1.2.1.vsix ) or you can build it by yourself (you can use this branch https://github.com/lstocchi/vscode-kubernetes-tools/tree/i770 ).

Once installed you should keep seeing the error as before `Kubectl command failed:`. Now if you go in the settings page and set "vs-kubernetes.enable-snap-flag" to true the extension should start working normally (CMD/CTRL + SHIFT + P -> search for `Open Setting` -> click on `Preferences: Open Settings (JSON)` -> add `"vs-kubernetes.enable-snap-flag": true` and save).

![image](https://user-images.githubusercontent.com/49404737/85011583-03fc5000-b162-11ea-9776-042e9d93017f.png)

 If you can confirm it works it would be really helpful for us. 
Thank you!!!

**Comment by gildas** [comment]
@lstocchi I installed the extension from the download link you gave me.

And I still get the `Kubectl command failed: ` even after setting the flag:  
```
    "vs-kubernetes": {
        "vs-kubernetes.enable-snap-flag": true
    }
```
I restarted vscode entirely after setting it, just to be sure.

**Comment by lstocchi** [comment]
Thanks heaps for the test @gildas . Before to give up on this solution, could you please close vscode before to install k8s tools again? It happened to me that it cached the old extension (the one i was deleting) and even if i installed a new version the old code got executed.

So doing something like, open vscode (better if you have only one window of this) -> delete k8s tools (it may ask to reload, do it) -> close vscode completely (all windows) -> open vscode again (make sure k8s tools is not installed) -> install my vsix. What is the outcome? You still see the error message.

If so, could you please check inside the developer tools console? Click on Help -> Toggle Developer tools -> it will open a window, check the console tab. Do you see any error message there?

**Comment by gildas** [comment]
ok, it is working.
I had to kill the code instances that stay around when you install the vsix (I thought code would actually quit after installing it, but no).
Then I restarted and I can see all my k8s clusters.
So, I think it is working now.

**Comment by lstocchi** [comment]
Yeah i know, it's very annoying that one needs to kill all code instances. 
I'm glad it's working now :) Please let us know if you find some other bug. We don't have much experience with snap so I don't know if there are other limitations by using it. 
Thank you again for your help.

**Comment by itowlson** [comment]
For future reference... Revving the version on a test drop sometimes makes VS Code better about not using its cached copy.

Sometimes.

![](https://ih1.redbubble.net/image.12221539.0293/sticker,375x360.png)

Anyway glad this is working for you and thanks heaps @lstocchi for figuring this out!

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/771 was merged

**Comment by nhoss2** [comment]
Since this was the first result on google for the "kubectl command failed" error, I fixed this by removing kubectl from the snap installation and installing kubectl from apt (https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)

**Comment by Mostafa-wael** [comment]
> @lstocchi I installed the extension from the download link you gave me.
> 
> And I still get the `Kubectl command failed: ` even after setting the flag:
> 
> ```
>     "vs-kubernetes": {
>         "vs-kubernetes.enable-snap-flag": true
>     }
> ```
> 
> I restarted vscode entirely after setting it, just to be sure.
This solution didn't work with me, I tried killing code and nothing changes

**Comment by yulunwu123** [comment]
I'm still having the issue after editing the setting file. My k8s extension panel is just completely empty with nothing in it, and every time I hit the refresh button it tells me "Kubectl command failed: unable to run kubectl". Anyone know how to fix this? Any help is appreciated!!

**Comment by lstocchi** [comment]
@yulunwu123 this issue is related to installing vscode with snap. Is it your case?
If you execute a kubectl command in the vscode terminal does it work? If yes, have you set the path of kubectl in the settings?
Which os are you on? Vscode version?

**Comment by Mostafa-wael** [comment]
> > @lstocchi I installed the extension from the download link you gave me.
> > And I still get the `Kubectl command failed: ` even after setting the flag:
> > ```
> >     "vs-kubernetes": {
> >         "vs-kubernetes.enable-snap-flag": true
> >     }
> > ```
> 
> I restarted vs code entirely after setting it, just to be sure. This solution didn't work for me, I tried killing code, and nothing changes

For future use, it worked when I removed the prefix and made it like this:
```json
"vs-kubernetes": {
        "enable-snap-flag": true,
        "helm-path": "/snap/bin/helm",
        "kubectl-path": "/snap/bin/kubectl"
    },
```
