### ISSUE TITLE
Showing active namespace in status bar.

### ISSUE THREAD

**Issue by sudhirverma** [Azure/vscode-kubernetes-tools#777]
It would be good to show active namespace in the status bar as it is a root extension for `vscode-tekton`
and showing active namespace in the status bar will help us to know if we switch the namespace and current namespace which we are using.

for more detail Link: https://github.com/redhat-developer/vscode-tekton/pull/320#issuecomment-647353738

cc: @gorkem @evidolob @lstocchi @siamaksade

**Comment by gorkem** [comment]
Looks like it has been done already https://marketplace.visualstudio.com/items?itemName=okteto.kubernetes-context

**Comment by lstocchi** [comment]
Still a good idea for me as that `kubernetes-context` extension is not in sync with this one.
