### ISSUE TITLE
Prompt to save document is annoying

### ISSUE THREAD

**Issue by akaroml** [Azure/vscode-kubernetes-tools#79]
Each time I click on a resource node in the explorer, a json file is opened automatically. When I try to close the document, I'm always asked to save to document or not. This is pretty annoying. I actually didn't make any changes to the document. Suggest using ContentProvider to show such documents without asking users to save when closing.

<img width="458" alt="screen shot 2018-03-09 at 11 32 50 am" src="https://user-images.githubusercontent.com/16755094/37189188-f8c0ba0a-238d-11e8-9af9-1f5f2c719e37.png">

**Comment by itowlson** [comment]
This doesn't repro for me.  When I click on a node, it displays the JSON document, and when I close the JSON document, it closes without a prompt.  I wonder if this is a difference between VS Code on Windows and Mac?  Do you have a Windows machine to test it on?

**Comment by itowlson** [comment]
@testforstephen assigning this to you in the first instance because @kyliel said your team had experience of this technique - feel free to assign elsewhere or bounce it back

**Comment by testforstephen** [comment]
@andxu could you help fix it?

**Comment by squillace** [comment]
this does repro for me, mostly everywhere. I wonder.

**Comment by andxu** [comment]
Is the snapshot the expectation?
![image](https://user-images.githubusercontent.com/17075863/38124340-86de703a-3413-11e8-8f89-3c176a31766c.png)

**Comment by bnookala** [comment]
One more observation: if one chooses to save the file when it prompts you, it gets saved into the current directory and the extension is unable to show the resource definition until the file gets removed.

**Comment by bnookala** [comment]
I've got a workaround in mind here… create a content provider exclusively for rendering the content from the `get` operation. seems like the save prompt is triggered by the untitled uri scheme - using a custom content provider would allow us to register a seperate read-only uri scheme that can render the content. from the docs:

```
untitled-scheme: A new file that should be saved on disk, e.g. untitled:c:\frodo\new.js. The language will be derived from the file name.```

**Comment by bnookala** [comment]
@andxu aha didn't realize you had done just what I was suggested!!! Do you have a PR open for this/can you open one?

**Comment by andxu** [comment]
Yes, I will submit the pr today

**Comment by andxu** [comment]
https://github.com/Azure/vscode-kubernetes-tools/pull/166

**Comment by bnookala** [comment]
Should be fixed now w/ @andxu's recent changes.
