### ISSUE TITLE
loading slow-Extension issue

### ISSUE THREAD

**Issue by yadavalli1** [Azure/vscode-kubernetes-tools#790]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lstocchi** [comment]
I guess this should be fixed once we merge https://github.com/Azure/vscode-kubernetes-tools/pull/586

**Comment by itowlson** [comment]
Should now be fixed
