### ISSUE TITLE
"describe" window is unsearchable

### ISSUE THREAD

**Issue by pbnj** [Azure/vscode-kubernetes-tools#792]
`>Kubernetes: Describe` command opens results in a window that is unsearchable.

This experience is specially problematic when the current implementation of `>Kubernetes: Describe` prompts users to specify a resource (e.g. `deployment`, `pod`, ...etc) and the results will include all objects under that resource, possibly displaying a lot of information that users would have to scroll through manually, looking for a specific piece of info.

**Comment by lstocchi** [comment]
Thanks for opening this @pbnj. I agree with you, it's quite useless when dealing with many many resources. I'll give it a look.
