### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dminca** [Azure/vscode-kubernetes-tools#794]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.47.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 24504,
		"activateCallTime": 339,
		"activateResolvedTime": 134,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-kubernetes-tools.vscode-kubernetes-tools",
				"_lower": "ms-kubernetes-tools.vscode-kubernetes-tools"
			},
			"activationEvent": "onLanguage:yaml"
		}
	},
	"runtimeErrors": []
}
```

**Comment by lstocchi** [comment]
Thanks for reporting this @dminca, could you give me more info about your issue? I can see it fails to start when activated using yaml cmd. What are you doing exactly? Can you see something in the tree? If you run kubectl at the command line are you able to execute anything?

**Comment by dminca** [comment]
this is redundant now as more versions were released that fixed this problem, closing
