### ISSUE TITLE
Logs output is not in color when using webview

### ISSUE THREAD

**Issue by mojo2012** [Azure/vscode-kubernetes-tools#798]
Hi guys,

awesome extension!

One thing that bugs me though, is that the log output does not interpret the ANSI color codes correctly when using the webview. In the terminal it works of course.

It would be awesome if you would add that feature, because using the webview/editor window is way more comfortable than the terminal.

Cheers

**Comment by lstocchi** [comment]
Thanks for opening this @mojo2012 . We are in the process to refactor the log view https://github.com/Azure/vscode-kubernetes-tools/pull/773 so we will surely keep this into consideration. Thanks again for the suggestion.

**Comment by lstocchi** [comment]
Closing it as new log viewer has been merged and released. Please open new issues if you face any problem or have some ideas how to enhance it. Thank you!!
