### ISSUE TITLE
Update and disable failed!

### ISSUE THREAD

**Issue by marcosg29** [Azure/vscode-kubernetes-tools#803]
Issue Type: <b>Bug</b>

I cant seem to get the update for this extension, everytime I open VS code I get the alert to update the extension but it doesn't update anytime, I've tried to disable it but I can't either....

Extension version: 1.2.1
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lstocchi** [comment]
Hi @marcosg29, so you have the version 1.2.1 installed? That's the latest one. Which message do you get in vscode? Can you make a screenshot?

Next time, if you have any issues with updating it, just go in the extensions tab.
You should see something like
![image](https://user-images.githubusercontent.com/49404737/88394514-db4e2280-cdbf-11ea-8140-c85fa942b985.png)

Click on the setting wheel icon and then `Install another version`
![image](https://user-images.githubusercontent.com/49404737/88394693-28ca8f80-cdc0-11ea-81b3-bc31c568847d.png)

You should get a list of all possible versions and select the latest one. This way it should work.
![image](https://user-images.githubusercontent.com/49404737/88394772-439d0400-cdc0-11ea-8301-a2cecf5a61b3.png)

**Comment by marcosg29** [comment]
> Hi @marcosg29, so you have the version 1.2.1 installed? That's the latest one. Which message do you get in vscode? Can you make a screenshot?
> 
> 
> 
> Next time, if you have any issues with updating it, just go in the extensions tab.
> 
> You should see something like
> 
> ![image](https://user-images.githubusercontent.com/49404737/88394514-db4e2280-cdbf-11ea-8140-c85fa942b985.png)
> 
> 
> 
> Click on the setting wheel icon and then `Install another version`
> 
> ![image](https://user-images.githubusercontent.com/49404737/88394693-28ca8f80-cdc0-11ea-81b3-bc31c568847d.png)
> 
> 
> 
> You should get a list of all possible versions and select the latest one. This way it should work.
> 
> ![image](https://user-images.githubusercontent.com/49404737/88394772-439d0400-cdc0-11ea-8301-a2cecf5a61b3.png)
> 
> 

Already worked around it, I uninstalled all the extensions that depended on this one and installed them again, might have one of those dependencies broken somewhere, anyways thanks for the help!

**Comment by lstocchi** [comment]
@marcosg29 glad you solved it :) I'm closing it, feel free to open a new issue if you face any other error. Thanks!!
