### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by GauravSquareOps** [Azure/vscode-kubernetes-tools#809]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Linux x64 5.4.0-7642-generic`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 16245,
		"activateCallTime": 191,
		"activateResolvedTime": 140,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-kubernetes-tools.vscode-kubernetes-tools",
				"_lower": "ms-kubernetes-tools.vscode-kubernetes-tools"
			},
			"activationEvent": "onLanguage:helm"
		}
	},
	"runtimeErrors": []
}
```

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
