### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Krrishdhaneja** [Azure/vscode-kubernetes-tools#811]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bnookala** [comment]
Hi @Krrishdhaneja, do you have any more details for this issue? Seems like there's context we're missing here!
