### ISSUE TITLE
Follow Logs does not work with update to 1.2.1

### ISSUE THREAD

**Issue by abishD** [Azure/vscode-kubernetes-tools#812]
Updated to the latest versions of both VS Code and Kubernetes extension (1.2.1) and I can no longer follow logs.

It keeps giving me 
"Loading...
The connection to the server XX.XX.X.XXX:XXXX was refused - did you specify the right host or port."

Note: Downgraded to Version 1.1.1 and follow logs works. Show logs is not affected.

VS Code Details
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by lstocchi** [comment]
@abishD I tried but it's working for me. Can you replicate it with any pods or it only happens with some of them?

**Comment by abishD** [comment]
Thank you lstocchi , I uninstalled and deleted the local settings from the .vscode folder and reinstalled that fixed the issue.

Will close this.
