### ISSUE TITLE
Extension Issue - Unable to auto create template for Kind Job

### ISSUE THREAD

**Issue by cskalyan** [Azure/vscode-kubernetes-tools#816]
I tried to create a template for Kind "Job" similar to Pod and extension does not auto fill. Where as it auto creates for Pod and other resources.

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/825 was merged. Now you should see the template for Job resources. Feel free to reopen it if this does not satisfy your expectations. Thanks!!
