### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ghost** [Azure/vscode-kubernetes-tools#817]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bnookala** [comment]
Hi @ruffelo, do you have any more details for this issue? Seems like there's context we're missing here!

**Comment by bnookala** [comment]
Closing as the user account has been deleted.
