### ISSUE TITLE
Debug: properly expose secrets to applications

### ISSUE THREAD

**Issue by akaroml** [Azure/vscode-kubernetes-tools#82]
Applications consume secretes differently. Here are two common ways:
- Secrets as mounted files
- Secrets as environment variables

The current debugging mechanism won't work for any of the scenarios above because the secrets are not exposed at all. When debugging, there should be a step to allow users to specify the way they want their secrets to be exposed to an application without modifying their app code/dockerfile. This includes:
- Specify whether to use mounted files or environment variables
- Specify the mapping between secret data entries and files/environment variables

And the settings should be persisted.

**Comment by testforstephen** [comment]
When Kubernetes pulls an image from a Private Registry, it also needs create a secret for that.

**Comment by testforstephen** [comment]
This issue applies to `Kubernetes: Run` and `Kubernetes: Debug (Launch)` commands.

**Comment by itowlson** [comment]
The registry secrets thing sounds like it needs to slot into the broader question around the experience of using registries other than Docker Hub...

**Comment by testforstephen** [comment]
Yeah, it's worth to rethink about the user experience for secret/registry/environment variable things. 

When creating Kubernetes resource via yaml file, it's very easy to specify them on the spec field. But in the one-click commands the extension provides, how to make user to customize the running context (e.g. environment variables, secrets)?  VSCode User Settings? Any thoughts?

**Comment by testforstephen** [comment]
To support secret or configMap reference, my initial proposal is to add a new user settings `vs-kubernetes.containerEnv` to inject extra environment variables to Kubernetes container when running the command `Kubernetes: Run` or `Kubernetes: Debug (Launch)`.

And this user settings format is like the following:
```
"vs-kubernetes.containerEnv": {
        "DOCUMENTDB_URI": "${configMapKeyRef.todoapp-db.dburi}", // a configMap reference
        "DOCUMENTDB_KEY": "${secretKeyRef.todoapp-db.dbkey}", // a secret reference
        "DOCUMENTDB_DBNAME": "jinbwan_todoapp-db" // a plaintext value
 }
```

The value could be a plaintext or configMap/secret reference. For reference variable, its format looks like `${configMapKeyRef|secretKeyRef.<name>.<key>}`.

cc: @akaroml @itowlson

**Comment by itowlson** [comment]
This doesn't really feel like it should be a user setting, but I'm not sure what a good alternative would be.  Can we store them in the debug configuration, or is the schema insufficiently flexible?  How would a user normally inject these values?  Via the kubectl command line?

**Comment by testforstephen** [comment]
Through `kubectl run xxx --overrides=<json schema>`, we can inject any k8s schema accepted info to kubectl command.

In our one-click commands (Run or Debug), we don't generate launch.json file or provide any user interface for such kind of configuration. If storing the env mapping in debug configuration or yaml file, it seems we still need invent some kind of format.

**Comment by squillace** [comment]
I'd like @radu-matei and @michelleN to review what's going on here as well, given their work on draft and debug scenarios. We want to expose this as a general debug solution for kubernetes -- of course -- but we also want the best environment UX as well across more than simply one usage. If we have TWO ways to enable debug -- say, either different dockerfiles OR different launch.json stuff -- that's fine, too, but it should be coherent and documented. Ultimately, I'd expect us to help users map F5/Debug in VS code to the method that suits their workflow. Also @bnookala and @bacongobbler . Why not 27 eyes here? It is an important thought.

**Comment by bacongobbler** [comment]
I agree with @itowlson. This doesn't seem like it should be a user setting. Other debug scenarios all ask for this kind of configuration in a launch.json, such as the example [on debugging Go applications in VSCode](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code).

If we don't generate a launch.json, we probably should for configuration like this.

Draft handles injecting environment variables into the container's environment through [a configuration file in the application's root directory called draft.toml](https://github.com/Azure/draft/blob/master/docs/reference/dep-006.md). Users can inject variables into their helm chart by adding new fields into the `set` field, eventually translating to `helm install --set` which uses these values to render a set of templates into kubernetes manifests. A common pattern to inject environment variable secrets in Helm is to add an `env` field into the templates, such as seen here in the chartmuseum chart:

https://github.com/kubernetes/charts/blob/978daf58216241ea5094d7b5dd91e7badfc66dd9/incubator/chartmuseum/templates/deployment.yaml#L28-L33

And the values.yaml can be seen here:

https://github.com/kubernetes/charts/blob/978daf58216241ea5094d7b5dd91e7badfc66dd9/incubator/chartmuseum/values.yaml#L10-L67

Just wanted to pre-seed the conversation before the call later today :)

**Comment by testforstephen** [comment]
@squillace Any more comments from the call meeting?

**Comment by squillace** [comment]
@testforstephen result was that we believed that secrets should stay out of the kubernetes extension for now. Result is, no work.

**Comment by brendandburns** [comment]
Closing as obsolete.
