### ISSUE TITLE
Kubernetes slowing CPU processes and increasing CPU load

### ISSUE THREAD

**Issue by olu2001segun** [Azure/vscode-kubernetes-tools#820]
this tool needs to be re-configured to enable the extension not to slow other extensions to be activated and to reduce the load on CPU.

**Comment by itowlson** [comment]
We had very high CPU load on startup, but that should be fixed as of 1,2.3.  I'm not aware of slowness once the extension was loaded - if you were seeing that, do you have any more details please?  Thanks!

**Comment by lstocchi** [comment]
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue. Thanks!!
