### ISSUE TITLE
Kubernetes Auto generation yaml files

### ISSUE THREAD

**Issue by cskalyan** [Azure/vscode-kubernetes-tools#821]
I am using Visual Studio Code to write or update yaml files, how ever auto generation of yaml files for kubernetes using VScode supports only Pod, Deployment, Service, ReplicationController. To Create other yaml files like ingress, network, PV, PVclaims; auto generation is not working. Can you please add the feature to generate yml templates for other resources as well.

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/825 was merged. Now you should see templates for Ingress, Job, PV, PVC, Secret and StatefulSet resources. Feel free to reopen it if this does not satisfy your expectations. Thanks!!
