### ISSUE TITLE
empty list for secrets child tree

### ISSUE THREAD

**Issue by cforce** [Azure/vscode-kubernetes-tools#823]
Using v 1.2.1 and vscode 1.49.2

Visual Cluster Code Tree View does not list any secrets when opening child tree for secrets.
Problem persists even after reload..
Of course when i right click "Get" kubectl get secret  -o wide" does show all the secrets on cmd windows as expected while tree view still stays empty.

**Comment by lstocchi** [comment]
Thanks for opening this @cforce, i'm giving a look :+1:

**Comment by lstocchi** [comment]
@cforce sorry for late response. I tried and it is working for me. Do you still face this issue? Can you give us more info about your cluster? What are you using? Version?

The call we make to retrieve the secret nodes is `get secret -o json --namespace=thenameofyournamespace`. Just to be sure, does it work or it fails somehow?
Thank you

**Comment by cforce** [comment]
Both running in vscode terminal..
* ```kubectl get secret  -o wide``` - > works /started from ctx menu
* ``` kubectl get secret -o json --namespace=dev``` 
** started manually from pshell console  start to printout base64 and other secrets until vs code freezes can message pops up that windows is not reacting - i click keep waiting and after some minute it recovers and i can see the print out
** if i start the same cmd from windows for unix shell it juts print out, no freeze.,

**Comment by lstocchi** [comment]
@cforce i see, yes maybe you found the issue ... what number are we talking about? I'll try to replicate it

**Comment by cforce** [comment]
$kubectl get secrets | wc
214

$kubectl get secrets -o json | awk '{ print length; }' > test.txt
$ awk '{s+=$1} END {print s}' test.txt
40444802

**Comment by mfmayer** [comment]
I'm observing the same issue.

**Comment by itowlson** [comment]
@lstocchi Did you get the chance to follow up on this?  If not, I can ask someone here if they would like to take a crack at it.

**Comment by lstocchi** [comment]
No @itowlson sorry. I have been busy on other things. If you have someone who can tackle this it would be great.

**Comment by itowlson** [comment]
@lstocchi I know the feeling.  @bacongobbler would you be interested in picking this up?

**Comment by bacongobbler** [comment]
I can take a closer look at this.

**Comment by bacongobbler** [comment]
Basic example to reproduce the issue:

```
><> helm repo add mirantis https://charts.mirantis.com
"mirantis" has been added to your repositories
><> for i in {1..200}; do helm upgrade --install nginx mirantis/nginx; done
```

You'll end up with 200 secrets in the default namespace (201 will be displayed to include the table headings).

```
><> kubectl get secrets | wc -l
```

Go take a coffee break while you wait for all 200 releases to be deployed...

**Comment by bacongobbler** [comment]
:headsmack: don't forget to export `HELM_HISTORY_MAX=200` before you invoke that... Forgot Helm only stores the last 10 releases per app.

**Comment by bacongobbler** [comment]
I was unable to reproduce the issue. Both leaf nodes loaded within ~1s by the time I opened the leaf.

![image](https://user-images.githubusercontent.com/1360539/106502605-70218f00-6479-11eb-90d1-e024e1d3e156.png)

![image](https://user-images.githubusercontent.com/1360539/106502646-79aaf700-6479-11eb-9886-a6603e92fcde.png)

**Comment by cforce** [comment]
It works- hureria .. tx so much :-)

**Comment by mfmayer** [comment]
> @mfmayer Is this working for you now too? If not, do please reopen with any additional info you can provide us with - thanks!

@itowlson I also can‘t observe the issue anymore. Many thanks 
for your effort!

**Comment by teamtitangithub** [comment]
The issue is back since i updated to 
![image](https://user-images.githubusercontent.com/80030984/124671874-6f70a700-deb6-11eb-98ed-09a9603e6ac3.png)
