### ISSUE TITLE
kubectl command failed on ubuntu 18

### ISSUE THREAD

**Issue by Relaxe111** [Azure/vscode-kubernetes-tools#829]
Hello I installed yesterday kubernetes extension in my vs code and it worked properly it connected to my azure k8s cluster showed nodes and everything. Today it throws me Kubectl command failed:.
When i try to `Add Existing Cluster` I get 
![image](https://user-images.githubusercontent.com/40892030/96554691-2ab8c780-12b7-11eb-95aa-3df5698593d5.png)
which is very strange because i have az installed v. 2: 
![image](https://user-images.githubusercontent.com/40892030/96554758-40c68800-12b7-11eb-9372-c11b1277d24c.png)
I can connect to k8s from cli and it works as expected. 
But I can't figure out what is the reason the vs code k8s extension can't mange to work. 
I also installed azure extension and it connects and show all my subscriptions as I expect.

**Comment by bacongobbler** [comment]
Looking at the code, it would appear that the extension attempts to execute the command `az --version` directly.

https://github.com/Azure/vscode-kubernetes-tools/blob/e134027df60019718c2a45e9b3df59d660a08fdb/src/components/clusterprovider/azure/azure.ts#L84

Can you try running the same command from within a terminal and see if it returns successful? From past experiences, this can sometimes occur if the command is not in your $PATH.

**Comment by Relaxe111** [comment]
I solved problem by reinstall kubectl

**Comment by ch4dwick** [comment]
> Looking at the code, it would appear that the extension attempts to execute the command `az --version` directly.
> 
> https://github.com/Azure/vscode-kubernetes-tools/blob/e134027df60019718c2a45e9b3df59d660a08fdb/src/components/clusterprovider/azure/azure.ts#L84
> 
> Can you try running the same command from within a terminal and see if it returns successful? From past experiences, this can sometimes occur if the command is not in your $PATH.

Thanks for this suggestion. After trying out different solutions, I tested running vscode from a shell with kubectl in the path and it worked for me. 

From the shell:
> export PATH=$PATH:<path to kubectl>
> code <path to project>

This instance of code had the extension working correctly.
