### ISSUE TITLE
Java debug to support exec form entrypoint

### ISSUE THREAD

**Issue by akaroml** [Azure/vscode-kubernetes-tools#83]
The current Java debugging injects additional JVM parameters through $JAVA_OPTS env var. Environment variables won't be evaluated when users dockerfile is using the exec from ENTRYPOINT statement. Here are the two form s of ENTRYPOINT:
- ENTRYPOINT ["executable", "param1", "param2"] (exec form, preferred)
- ENTRYPOINT command param1 param2 (shell form)

Please support both. CMD statement can be used to specify extra parameters to ENTRYPOINT.

**Comment by testforstephen** [comment]
1. In `exec form`, the variable will not be substituted, use the global JVM environment variable `JAVA_TOOL_OPTIONS` to enable debug options.
2. In `shell form`, use `$JAVA_OPTS` or the global JVM environment variable `JAVA_TOOL_OPTIONS` to enable debug options.

**Comment by testforstephen** [comment]
Closed with PR https://github.com/Azure/vscode-kubernetes-tools/pull/89
