### ISSUE TITLE
Add option for showing timestamps in logs

### ISSUE THREAD

**Issue by arsnyder16** [Azure/vscode-kubernetes-tools#831]
kubectl logs --timestamps

**Comment by itowlson** [comment]
This shouldn't be too hard at the code level but we need to consider the user experience,  I think we now have a webview for logs?  So a possible UX could be a checkbox on the webview to show/hide timestamps, with a an option to configure the default.

Or we could just always provide timestamps - what do people think?

**Comment by lstocchi** [comment]
Closing it. New log webview offers this.
