### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PraveenADPP** [Azure/vscode-kubernetes-tools#832]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
