### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KYZITEMELOS93** [Azure/vscode-kubernetes-tools#837]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.51.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
