### ISSUE TITLE
Helm files incorrectly formatted with language mode 'helm-template'

### ISSUE THREAD

**Issue by thernstig** [Azure/vscode-kubernetes-tools#838]
VS Code version: 1.51.0
Kubernetes extension version: 1.2.1

Save the following in a charts/test/templates/service.yaml file:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: test
  annotations:
    {{- include "test.test" . | nindent 4 }}
spec:
  type: {{ .Values.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: test
      protocol: TCP
      name: test
  selector:
    app.kubernetes.io/name: {{ include "test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```

Make sure that the file is interpreted as the language mode `helm-template`. Save the file and it ends up looking like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: test
  annotations: { { - include "test.test" . | nindent 4 } }
spec:
  type: { { .Values.type } }
  ports:
    - port: { { .Values.port } }
      targetPort: test
      protocol: TCP
      name: test
  selector:
    app.kubernetes.io/name: { { include "test.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
```

**Additional info**
I've also installed the latest version of the VS Code "Prettier" extension, if that is of importance.

**Comment by bacongobbler** [comment]
Hmm... I tried to reproduce the same environment with the latest version of this extension along with extension "esbenp.prettier-vscode" (Prettier).

1. `helm create test-838`
2. Open a new window for templates/service.yaml
3. Edit the file to the content shown above
4. Set Language Mode to `helm-template`
5. Hit CTRL+S

No modifications of the file were observed.

**Comment by thernstig** [comment]
@bacongobbler Thank you very much for trying to reproduce. I just tested again. Using version `v1.2.3` of this tool and `v5.8.0` of the Prettier VS Code extension.

What happens if you press `shift+alt+F` in the file which should format it?

Have you also set this in the VS Code config?

```
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

The `annotations` part is what changes as the line after jumps up onto the same line as `annotations` (and with spacing added at places).

**Comment by JackPott** [comment]
I've hit this too, using the default `helm create`, but I notice it only affects `service.yaml`: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: { { include "hellokube.fullname" . } }
  labels: { { - include "hellokube.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "hellokube.selectorLabels" . | nindent 4 } }
```

Alt+Shift+F formats it incorrectly too. 

All the other template yaml files, like `deployment.yaml`, `ingress.yaml` etc are not affected. Is there something odd in this file? If you save without formatting helm accepts it as valid and deploys it. 

Looking at the Prettier output log, it definitely seems Prettier is looking at both examples, however where as the log completes without incident on the incorrect `service.yaml`, on all other files like `deployment.yaml` and `ingress.yaml` there are errors in the console
deployment.yaml: 
```
["ERROR" - 2:02:58 PM] All collection items must start at the same column (1:1)
>  1 | apiVersion: apps/v1
     | ^^^^^^^^^^^^^^^^^^^
>  2 | kind: Deployment
....
	at e (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/parser-yaml.js:1:316)
	at Object.parse (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/parser-yaml.js:15:142638)
	at Object.parse (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:13625:19)
	at coreFormat (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:14899:14)
	at format (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:15131:14)
	at /home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:57542:12
	at Object.format (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:57562:12)
	at t.default.<anonymous> (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/dist/extension.js:1:17537)
	at Generator.next (<anonymous>)
	at s (/home/chrisaustin/.vscode-server/extensions/esbenp.prettier-vscode-5.8.0/dist/extension.js:1:11535)
["INFO" - 2:19:57 PM] Formatting completed in 22.0443ms.
```

Could it be it only appears to work because most helm YAML's are coincidently causing errors?

**Comment by bacongobbler** [comment]
Since these appear to be issues with the Prettier extension, would it be more prudent to open a ticket with them? They may know how to resolve this issue.

I’ve never used this extension so I haven’t the foggiest idea how to proceed here.

**Comment by thernstig** [comment]
@bacongobbler Sure, do you think it is a problem with that extension? I can open a ticket there then.

**Comment by thernstig** [comment]
Closed, because as you so correctly pointed out this is a Prettier issue and there is already an existing issue here https://github.com/prettier/prettier/issues/6517

**Comment by digitalstudium** [comment]
Just wrote formatter for helm templates: https://github.com/digitalstudium/helmfmt

To use it with VSCode, add this to settings after installing `helmfmt`:

```
  "advancedLocalFormatters.formatters": [
    {
      "command": ["helmfmt", "--files", "$absoluteFilePath", "--stdout"],
      "languages": ["helm"]
    }
  ],
  "[helm]": {
    "editor.defaultFormatter": "webfreak.advanced-local-formatters"
  }
```

In addition this extension must be installed https://github.com/WebFreak001/vscode-advanced-local-formatters (and sure vscode-kubernetes-tools extension itself)
