### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kobiecrowder** [Azure/vscode-kubernetes-tools#840]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 473,
		"activateCallTime": 111,
		"activateResolvedTime": 1106,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "mtxr.sqltools-driver-sqlite",
				"_lower": "mtxr.sqltools-driver-sqlite"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by itowlson** [comment]
Looking at the `activate` timings in the message, I think this is down to slow loading, which should be resolved in 1.2.3.  However I'm a bit puzzled by the mention of the SQLite Tools extension; I wonder if there is some interaction between the two.  We'll keep an eye on this - thanks!

**Comment by bacongobbler** [comment]
Hey @kobiecrowder - v1.2.3 has been released as of last week. Can you try giving that a shot and report back?

**Comment by bacongobbler** [comment]
ping

**Comment by lstocchi** [comment]
Closing it as this should have been solved in latest releases. Please feel free to reopen it if you face this error again. Thanks!!
