### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bariscankurtkaya** [Azure/vscode-kubernetes-tools#844]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11636,
		"activateCallTime": 25,
		"activateResolvedTime": 163,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "mindaro.mindaro",
				"_lower": "mindaro.mindaro"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by itowlson** [comment]
Should be fixed in 1.2.3 - please reopen if not
