### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Adesoji1** [Azure/vscode-kubernetes-tools#846]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.52.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7288,
		"activateCallTime": 68,
		"activateResolvedTime": 193,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "mindaro.mindaro",
				"_lower": "mindaro.mindaro"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by itowlson** [comment]
My guess is that this is a slow load issue, which should be resolved in 1.2.3, though I'm not 100% sure from the timings.  Please let us know if you still get it after 1.2.3 installs.  Thanks!
