### ISSUE TITLE
Follow logs not work, wrong kubeapi url

### ISSUE THREAD

**Issue by CRASH-Tech** [Azure/vscode-kubernetes-tools#848]
I'm using multiple kubernetes clusters with not standart kubeconfig path.
All working, except "follow logs", it's trying to connect to wrong kube-api url:
"Loading...The connection to the server localhost:8080 was refused - did you specify the right host or port?"

**Comment by CRASH-Tech** [comment]
ADD: All works if path to kubeconfig is default: $HOME/.kube/config
Non stardart path not working

**Comment by itowlson** [comment]
Thanks @CRASH-tech for the report and @karelklic for tracking down the source.  I'll take a look.
