### ISSUE TITLE
X11 forwarding when attached to a running pod

### ISSUE THREAD

**Issue by Phantomape** [Azure/vscode-kubernetes-tools#849]
## Issue
I'm currently using vscode insider in my laptop to attach to a running pod in the remote server, for compilation and testing stuff. However, attaching to such a running pod doesn't gives me X11 forward ability. To launch any GUI inside the running pod I have to first SSH -X into the remote machine, which I'm trying to avoid during the whole development workflow via remote Kubernetes, and get the correct .Xauthority file and DISPLAY env var, and then manually setting them inside my pod.
I was able to launch Intellij IDEA via such tiring & manual approache is there any config that I can set, so that I don't need to login to the remote host machine? Say, attaching to this running pod can gives me the correct DISPLAY env var and .Xauthority file

**Comment by itowlson** [comment]
I'm not sufficiently familiar with the authentication and communication issues involved in X11 forwarding to really comment on this.  If you can detail the exact steps that are needed, and can help us work through development and testing, then we can try to explore how to offer this feature - making it easy to run an IDE inside a pod does sound very powerful.  I can't promise anything though.

**Comment by Phantomape** [comment]
![image](https://user-images.githubusercontent.com/8809221/106113705-bd57e500-6189-11eb-8d56-36f0e69d2282.png)
Sure, I'd love to give a more detailed descriptions to make this feature go a little bit further. But could u tell me the location for "Attach Visual Studio Code" shown in the image above, so that I could dig deeper into the code before jumping to conceptual design. Did a word regex search in the master branch, nothing shows up :( .

**Comment by itowlson** [comment]
Hmm. I don't recognise that command at all!  It could be contributed by another extension though, via our API.  Would you be able to post a list of your installed extensions please (`code --list-extensions`), and I can investigate where it comes from?  Thanks!

**Comment by Phantomape** [comment]
![image](https://user-images.githubusercontent.com/8809221/106236781-8096f700-6238-11eb-85f9-f132bf2db2d4.png)
I found the source for this button: https://github.com/microsoft/vscode-remote-release/issues/12, it is from ```Remote-Containers```

**Comment by bacongobbler** [comment]
Hey! Thanks for the report @Azure/arm-template-deployment-what-if 

Judging from your latest comment in https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-769600513 it does appear that the functionality you're looking for is in another Kubernetes extension. Shall we close this in favour of that ticket instead? I don't think there's any action items we need to take here to address your issue.

**Comment by Phantomape** [comment]
Sure
