### ISSUE TITLE
[Feature Request] Support Golang debugging

### ISSUE THREAD

**Issue by mirogta** [Azure/vscode-kubernetes-tools#852]
**Story**
As a Golang developer
I want to use the vscode-kubernetes-tools add-on to also debug applications written in Golang which are running remotely in kubernetes
So that I can debug them and have a unified experience with using this add-on to debug other apps (written in dotnet, java, node, python)

**Comment by itowlson** [comment]
@bacongobbler You're probably more familiar with the Go toolchain than most of us - would you be interested in tackling this?  It's fiddly but there's a fairly well established pattern.

**Comment by bacongobbler** [comment]
Isn't this something that can be provided by other VSCode extensions? I feel like Go debugging support is something a Go extension should handle rather than Kubernetes.

It's listed as the first feature in the Go extension. https://github.com/golang/vscode-go/blob/master/docs/debugging.md

**Comment by bacongobbler** [comment]
Here's the section on remote debugging: https://github.com/golang/vscode-go/blob/master/docs/debugging.md#remote-debugging

**Comment by itowlson** [comment]
@bacongobbler the point is the integration to locate the right container and set up all the stuff for them.  As with all the other languages we support, the language extension handles the actual debugging, but we smooth the setting up of the remote debug session.

**Comment by bacongobbler** [comment]
Looking into this.

**Comment by mirogta** [comment]
Awesome - thanks @bacongobbler
