### ISSUE TITLE
Disappearing logs after tab deselection

### ISSUE THREAD

**Issue by ahmetgeymen** [Azure/vscode-kubernetes-tools#853]
Issue Type: <b>Bug</b>

Hello,

I'm using vscode on macOS Catalina. I open a new log tab by selecting 'follow logs' on an deployment and it shows and follows the logs. It is working nice until I follow another deployment's log or select another tab on vs code. When I come back to first tab, it clears all the logs and also stops following new logs. Unfortunately I found this issue very tiring and frustrating.

Thanks for creating such a cool extension by the way.

Extension version: 1.2.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 3d710ab0-de50-4be3-9ebf-8057fbfd5392|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ahmetgeymen** [comment]
I've also commented under similar issue [#616](https://github.com/Azure/vscode-kubernetes-tools/issues/616) previously. 😞

**Comment by bacongobbler** [comment]
Hey @ahmetgeymen - thanks for reaching out. Any chance you've been able to determine what might be causing the bug?

**Comment by ahmetgeymen** [comment]
Unfortunately I don't know the exact cause but it might something make it stopping or ceasing the connection when it losing the focus and/or selection of the current tab. I also didn't profile the network of the vs code. (Don't know how to do by the way, may be via whireshark)

**Comment by ahmetgeymen** [comment]
> Hey @ahmetgeymen - thanks for reaching out. Any chance you've been able to determine what might be causing the bug?

I've been dragging up and met some logs like below. SytnaxError is occurred immediately when onscreen logs are disappeared as soon as I reselect the tab.

<img width="686" alt="Screen Shot 2021-02-02 at 22 10 06" src="https://user-images.githubusercontent.com/3007479/106650959-9132ce80-65a4-11eb-9e6c-74218c061707.png">

**Comment by itowlson** [comment]
That _looks_ like the VS Code container for the logs webview is detecting a syntax error on the page,  I wonder if the HTML or JS are getting restored incorrectly when the webview reloads?  I don't know why that would be though!

**Comment by ahmetgeymen** [comment]
It seems this issue has been resolved with release 1.3.1.
https://github.com/Azure/vscode-kubernetes-tools/blob/master/CHANGELOG.md#131

Thanks contributors for their efforts. 👏
https://github.com/Azure/vscode-kubernetes-tools/pull/905
