### ISSUE TITLE
Get command failed: error: there is no need to specify a resource type as a separate argument

### ISSUE THREAD

**Issue by ianjirka** [Azure/vscode-kubernetes-tools#867]
When expanding any pod on a node I get the following error:

```
Get command failed: error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'
```

```
Error loading document: Error: cannot open k8smsx://loadkubernetescore/pod-kube-system%20%20%20%20%20%20%20%20%20%20%20%20coredns-9bc57ddff-vnrft.yaml?ns%3Dall%26value%3Dpod%2Fkube-system%20%20%20%20%20%20%20%20%20%20%20%20coredns-9bc57ddff-vnrft%26_%3D1611860122528. Detail: Unable to read file 'k8smsx://loadkubernetescore/pod-kube-system            coredns-9bc57ddff-vnrft.yaml?ns=all&value=pod/kube-system            coredns-9bc57ddff-vnrft&_=1611860122528' (Get command failed: error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'
)
```

Repro:
- Expand cluster
- Expand Nodes
- Expand a node
- Expand a pod (Ex : coredns)

Expected:
Not sure, first time using this extension

Actual:
UX spins for a while, then creates a sub-node under the pod with the text 'Error' and VSCode pops the above error messages.

Tested with these kubectl/AKS versions:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by itowlson** [comment]
Hmm, I get a different error but yeah something is definitely not right there.  Thanks - taking a look.

Depending on what you want to look at you can also find pods under the Workloads folder, where they are working for me - please let us know if you see errors there as well.  Thanks!

**Comment by itowlson** [comment]
Something has gone wrong with the parsing of the `kubectl` output.  We see something like:

```
NAMESPACE              NAME                                                READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
azureoperator-system   azureoperator-controller-manager-574d8fd47b-slz9f   2/2     Running   0          92d     10.244.0.63   aks-agentpool-23678539-vmss000000   <none>           <none>
```

and interpret it as

```
{
  namespace: "",
  name: "azureoperator-system   azureoperator-controller-manager-574d8fd47b-slz9f",
  ...
}
```

This might have been introduced in #797 where we fixed some other aspects of kubectl output parsing but possibly introduced a regression.  I'll continue investigating.

**Comment by itowlson** [comment]
Okay #797 introduced a bug in `outputUtils.ts > findPositionHeaders` (line 31) where it would get the wrong position for any column whose header was a substring of an earlier header.  This kubectl output has `NAMESPACE` followed by `NAME` so we incorrectly start the `NAME` column at the position of the `NAMESPACE` column and this truncates the `NAMESPACE` column.  This should be an easy fix - fingers crossed.

**Comment by dnegrisolli** [comment]
I´m having this problem too!

**Comment by itowlson** [comment]
Fix is out for review and should be in the next release.  Thanks for the precise and methodical bug report and repro instructions - this really helped to nail it quickly.
