### ISSUE TITLE
Can't switch cluster or namespace on Mac

### ISSUE THREAD

**Issue by shu-ming** [Azure/vscode-kubernetes-tools#870]
Can't switch cluster or namespace on macOS through the Kubernetes Extension.
Right click the cluster name, select "Set as Current Cluster"

Error message is:
_Failed to set 'docker-desktop' as current cluster: Kubectl command failed: error: open .lock: read-only file system_

Right click a not current namespace name, select "Use Namespace"

Error message is:
_Failed to switch the namespace: error: open .lock: read-only file system_

Mac OS 10.15.7
Kubernetes Extension v1.2.3

**Comment by itowlson** [comment]
@bacongobbler Are you on a Mac?  If so would you be able to look into this please?  Thanks!

**Comment by bacongobbler** [comment]
Sorry! I no longer own a Mac.

**Comment by bacongobbler** [comment]
Out of curiosity, can you try rebooting your machine and see if it works? If I'm interpreting the error message correctly, `kubectl` is attempting to open a file lock on the local directory. It's unclear why it would attempt to do that.

You can also try running `kubectl config set-context docker-desktop --namespace foo` to see if you can reproduce the same error.

**Comment by shu-ming** [comment]
@bacongobbler I can switch the cluster and namespace through the `kubectl config`. But it fails through right click menu.

**Comment by shu-ming** [comment]
After installing the Catalina update, this issues is fixed. Perhaps it is fixed by update  or many times restart. Not sure about that. Anyway, it is not there anymore. thank you
