### ISSUE TITLE
Helm History node always loads latest release

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-kubernetes-tools#884]
You can click on a Helm Release node to see the release a la `helm get all`.  If you click on a historical sub-node, though, it still loads the latest release instead of the one you selected.  We can fix this by running `helm get all --revision`.

**Comment by shreyaskarnik** [comment]
@itowlson thanks for opening this. I do have a WIP fix for this bug. Happy to give this a shot if you are not actively working on this, else please ignore my comment.

**Comment by itowlson** [comment]
Oops, sorry, was about to send a PR.  My apologies, I should have self-assigned to let you know.

**Comment by shreyaskarnik** [comment]
All good! Thanks for fixing this.
