### ISSUE TITLE
plugin can't be turned off for User

### ISSUE THREAD

**Issue by Morriz** [Azure/vscode-kubernetes-tools#890]
When it is turned off for scope User, it seems not possible to explicitly enable it in the Workspace settings. I also can't find any "enabled" flag or so.

**Comment by Morriz** [comment]
Hmmmm. I am able to turn it on only for Workspace scope, but that is not reflected in the `.vscode/settings.json` file (as if my vscode install keeps it somewhere else, but why?)  It seems we are now not able to automate this for new developers pulling our repo. So my real question is, how is it possible to turn on this plugin via that file?

**Comment by itowlson** [comment]
As you have noted, enabling at the workspace level seems to be possible via the Extensions UI:

![image](https://user-images.githubusercontent.com/865538/107892108-dfbe7080-6f87-11eb-99a5-e5f4a03acd23.png)

I don't know where this information is stored, though.  I'd suggest contacting the VS Code team about this (via https://github.com/microsoft/vscode/issues) as this is a VS Code-level concern that we have no visibility of or control over.  Please do let us know what you find!

**Comment by Morriz** [comment]
Yes, I saw that. But I would expect the plugin to offer configuration to activate the plugin for `Workspace` level, via the `.vscode/settings.json` approach, which is the default I believe. Maybe it is easy to add this? So that we can automate everything? Otherwise we have to tell our devs to do some manual task to be able to use the plugin.

I am not sure why there wouldn't be a flag for that out of the box. I would expect a `${pluginName}.enabled` flag to come by default, but unfortunately not it seems. Maybe it would be beneficial for you as plugin maker to address that with VScode?

**Comment by bacongobbler** [comment]
As @itowlson mentioned, the VSCode team may know more about how extensions can be installed and enabled at a workspace scope. This is out of our knowledge realm - the mechanism for enabling and disabling extensions at the Workspace/User level is a VSCode concern; an extension cannot determine how it is installed or enabled.

I'd reach out to them first and see if there's a way to do so. Let us know what you find out.

**Comment by Morriz** [comment]
I think it is in scope. I see other extensions following that paradigm. It
is up to you as an extension developer to expose that flag probably. It
might be in adoptions interest to expose it so we as users can automate
enablement from our code repos.

**Comment by bacongobbler** [comment]
Do you have an example handy we can look at?

**Comment by itowlson** [comment]
Issue has been outstanding with the VS Code team for a while now: https://github.com/Microsoft/vscode/issues/40239

**Comment by squillace** [comment]
Yup. That's a global setting. If there's an easy way to do this at an extension level, I'd love to see a few examples of those that have done it without stomping on other extensions usage. That's always the hard part.

**Comment by itowlson** [comment]
I don't understand how a setting that relies on the extension checking it would work to be honest.  If an extension is globally disabled, VS Code would never activate it, so it could never check the config setting to know it should participate in this workspace.  Or am I missing something?

**Comment by Morriz** [comment]
I think it is just an extra option for you to implement in user space: just offer us the flag via your configuration to control this via code. Than we can choose to use your plugin from User or Workspace settings.json.

**Comment by Morriz** [comment]
It would be nicer if VScode provided this as a hard flag that an extension developer can't control: `enabled`. Unfortunately it seems they have not done so, and until that happens it is up to user space to implement such a thing I guess....

**Comment by squillace** [comment]
without a few examples to look at, we'll help you push the general issue above (https://github.com/microsoft/vscode/issues/40239) but this is not yet anything we will work on. **yet**. If we can't find examples with other extensions, I'll close the issue. We can always reopen it if we discover something we can work with.

**Comment by Morriz** [comment]
Do you offer ANY settings to be controlled via vscode settings.json? If so, that is what I refer to. To just expose an `enabled` flag. Example plugins that do this:

- `esbenp.prettier-vscode`: "prettier.enable"
- `signageos.signageos-vscode-sops`: "sops.enabled"

**Comment by squillace** [comment]
Thanks for the examples! We'll have a look.

**Comment by squillace** [comment]
Hmmmmmm. We did a quick look, and the problem here is that prettier can do this because there's no UI and it runs in the background, and the command bar is still populated with commands like "Create Configuration File". But VS Code will still populate the command bar, activity bars, and the UI even if the extension is "disabled". 

We can't, from the extension, prevent/correct whatever Code does at a larger level. More importantly, we are not going to invest time and energy into trying to subvert what Code should do per the mentioned issue. This doesn't mean your desire isn't useful -- it is! But it's not something we will do. You should join the vscode issue and address the underlying problem. It's a good one to fix.

**Comment by Morriz** [comment]
Alright, I will close this then. I agree it should be handled higher up
