### ISSUE TITLE
Error opening dashboard with minikube cluster

### ISSUE THREAD

**Issue by mploquin** [Azure/vscode-kubernetes-tools#897]
On a minikube cluster (1.17.0) i cannot open the dashboard with the "Open Dashboard" menu selection from the Kubernetes Extension for vscode since version 1.2.3 and above. I have this message / error : 

`Something went wrong when ensuring the Kubernetes API Proxy output stream existed`

It work fine with extension version 1.2.2... Any ideas ? 

Thanks

**Comment by lstocchi** [comment]
Hi @mploquin , thanks for opening this. From version 1.2.3 we bundled the extension so i guess this error depends from that. We'll fix it asap.

**Comment by itowlson** [comment]
@lstocchi It looks like we use a file to figure out when the `kubectl proxy` for the dashboard is ready.  The filepath is based on `__dirname`, which might get trampled by webpack.  I am not sure why having the temp file in the wrong place would matter... but I guess it could...?!
