### ISSUE TITLE
Uses space for line:column in status bar

### ISSUE THREAD

**Issue by alexreg** [Azure/vscode-kubernetes-tools#899]
Why does the plugin use the space for the `line:column` number in the status bar? This is obviously highly undesirable.

<img width="101" alt="Screenshot 2021-02-27 at 17 12 00" src="https://user-images.githubusercontent.com/67036/109394439-e8fff380-791e-11eb-930b-f01840afff8e.png">

**Comment by itowlson** [comment]
Where are you seeing this please?  When I install the plugin I still see the line and column display; we would certainly not want to overwrite that.

![image](https://user-images.githubusercontent.com/865538/109438370-96454980-7a8e-11eb-9bf2-bce0d1559eac.png)

(To be honest I didn't know overwriting it was even possible!  Sometimes multiple extensions can push the line/column display out to the left, though - could this be what's happening?  If so we have no control over it I'm afraid...)

![image](https://user-images.githubusercontent.com/865538/109438429-dc9aa880-7a8e-11eb-8c88-49d5c49466f2.png)

**Comment by alexreg** [comment]
Apologies for the alarm; I think I'm actually mistaken. I'd hastily jumped to the conclusion that it was Kubernetes, just because the Kubernetes text appeared in (roughly) the same space that the line:column usually appears in. It is rather probably that line:column is getting pushed off the end by a bunch of status bar items (Kubernetes just one of them).
