### ISSUE TITLE
Support kubectl proxy

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#9]
Would be great to see support for the Kubernetes dashboard via`kubectl proxy`. I think the idealized behavior here would be:

1. Invoke `kubectl proxy`
2. Either open the user's default browser, or do an HTML preview pane with and navigate to the dashboard address: `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/`
3. If we open the preview pane, see if we can hook into a close event on the pane to shut down the proxy after the user is done with it.

Thoughts?

**Comment by testforstephen** [comment]
I would suggest to create a vscode `Terminal` when invoke `kubectl proxy`, then the user could shut down the proxy process like killing the other terminal process.

**Comment by bnookala** [comment]
On further thinking… for AKS clusters, the dashboard is accessed via `az aks browse -n $CLUSTER_NAME -g $RG_NAME`as opposed to just `kubectl proxy` - is this something we should support as well? @itowlson

**Comment by squillace** [comment]
@bnookala it would be best if you added the aks cluster browse command to an azure-specific extension.... we'd like this one to maximize kube/helm usage for as many as possible.
