### ISSUE TITLE
Can't discover cluster with kubernetes v1.19.7

### ISSUE THREAD

**Issue by nicole-chen-fivestars** [Azure/vscode-kubernetes-tools#908]
I recently upgraded my kubernetes to v1.19.7, and the extension can no longer find my cluster. I'm now unable to attach to a container to debug.

<img width="280" alt="Screen Shot 2021-03-15 at 4 31 38 PM" src="https://user-images.githubusercontent.com/54960122/111187933-6cbb1080-85ac-11eb-88bc-c0876863ee24.png">
<img width="373" alt="Screen Shot 2021-03-15 at 4 33 23 PM" src="https://user-images.githubusercontent.com/54960122/111187939-6dec3d80-85ac-11eb-8eed-131461957d1a.png">

```
$ minikube config view
- vm-driver: virtualbox
- cpus: 4
- disk-size: 40000M
- kubernetes-version: v1.19.7
- memory: 8192
```

I feel this error message is related, but I'm not well-versed with k8s to poke at it meaningfully:
```
Kubectl command failed: error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
```

**Comment by bacongobbler** [comment]
Hi @nicole-chen-fivestars.

> I recently upgraded my minikube to v1.19.7

Looking at the releases page I only see v1.18.1 as the latest. I assume you meant Kubernetes 1.19.7 as per your snapshot.

https://github.com/kubernetes/minikube/releases/tag/v1.18.1

It also appears you have kubectl v1.16.6-beta.0 installed. Try upgrading kubectl to a more recent version and see if that will fix the issue for you.

**Comment by nicole-chen-fivestars** [comment]
Hey @bacongobbler, 

Yes, you're correct. I meant Kubernetes 1.19.7 and updated the issue description.

Upgrading my kubectl client version did indeed solve the issue. Thanks so much for your help!
