### ISSUE TITLE
clusters no longer visible in sidebar

### ISSUE THREAD

**Issue by LGNorris** [Azure/vscode-kubernetes-tools#910]
Just out of the blue my clusters have stopped appearing in my toolbar. However, running _Kubectl config view_ returns a kubeconfig with expected clusters and contexts. Anyone had a similar problem?

Clicking on Set Kubeconfig from the sidebar yields not response but running the same command from the command palette gives this error:

![image](https://user-images.githubusercontent.com/42153969/111648663-7f775480-87fb-11eb-8c07-35869b31e230.png)

Below is my Kubernetes settings. Are far as I'm aware this is the default settings?
```
    "vs-kubernetes": {
    
        "vs-kubernetes.namespace": "",
        "vs-kubernetes.kubectl-path": "",
        "vs-kubernetes.helm-path": "",
        "vs-kubernetes.minikube-path": "",
        "vs-kubernetes.kubectlVersioning": "user-provided",
        "vs-kubernetes.outputFormat": "yaml",
        "vs-kubernetes.kubeconfig": "",
        "vs-kubernetes.knownKubeconfigs": [],
        "vs-kubernetes.autoCleanupOnDebugTerminate": false,
        "vs-kubernetes.nodejs-autodetect-remote-root": true,
        "vs-kubernetes.nodejs-remote-root": "",
        "vs-kubernetes.nodejs-debug-port": 9229,
        "checkForMinikubeUpgrade": true,
        "logsDisplay": "webview",
        "imageBuildTool": "Docker"
    }
```
Current versions:
VS Code: v1.50.1
vcode-kubernetes-tools: v1.2.4

**Comment by bacongobbler** [comment]
Hmm... If the command cannot be found I wonder if your vscode environment is out of whack. Have you tried reinstalling the kubernetes extension to see if it is repopulated?

For context, here is where it is declared:

https://github.com/Azure/vscode-kubernetes-tools/blob/cda741dbb442823e4cd87812139d5c7bb6bd4f16/package.json#L57

**Comment by LGNorris** [comment]
Yeah it seems my VS code was out of whack. Did a fresh install to the latest build of VS Code and it seems to of fixed the issue.
