### ISSUE TITLE
Kubernetes:Debug doesn't provide Go debugging

### ISSUE THREAD

**Issue by cfiderer** [Azure/vscode-kubernetes-tools#911]
I have the Kubernetes extension (ms-kubernetes-tools.vscode-kubernetes-tools v1.3.0) and the Go extension (golang.go v0.23.2)
installed in VS Code 1.54.3. I use Go 1.16.2, all tools requested by VS Code are up-to-date. I have configured the `vsdocker.imageUser` setting in my User settings.

But the `Kubernetes: Debug (Launch)` and `Kubernetes: Debug (Launch)` commands do not offer a Go environment (they offer `dotnet`, `java`, `nodejs`, `python`, and `node` as environments).

What do I have to change / configure to get Kubernetes Debugging to run?

**Comment by lstocchi** [comment]
Hi @cfiderer, sorry for the late response. The current kubernetes extension (the one in the marketplace) still doesn't have the go debugger feature. It has been implemented and merged to the master https://github.com/Azure/vscode-kubernetes-tools/pull/875 but we haven't released the new extension yet. We'll ping you when it'll be published. 

In the meantime, if you want, you can manually install the vsix built from the master. You can find the archive containing the vsix here https://github.com/Azure/vscode-kubernetes-tools/actions/runs/681120684

**Comment by timirnich** [comment]
What's the ETA for a release that contains the go debugging feature? I'd like to use this in a training I'm currently building, but if it's coming later than say mid-May I'd have to skip it for now.

**Comment by lstocchi** [comment]
@timirnich it's going to be released soon (hopefully tomorrow) https://github.com/Azure/vscode-kubernetes-tools/pull/931

**Comment by lstocchi** [comment]
Closing it as obsolete
