### ISSUE TITLE
Unable to parse config file .aws/config

### ISSUE THREAD

**Issue by yurigene** [Azure/vscode-kubernetes-tools#914]
We use okta for authentication.
Using latest VSCode and the plugin version.
AWS Toolkit is working fine.
kubectl get pods works fine from terminal.

Kubernetes extension showing the cluster, BUT while trying to open Nodes or other things getting this error:

`Unable to parse config file: /Users/yurib/.aws/config Unable to parse config file: /Users/yurib/.aws/config Unable to parse config file: /Users/yurib/.aws/config Unable to parse config file: /Users/yurib/.aws/config Unable to parse config file: /Users/yurib/.aws/config Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255`

No logs, nothing...

config:

```
[okta]
# Okta Dev APP
#####################
aws_saml_url = home/amazon_aws/0oadubzz5cWgsZdON1t7/272


# Dev is the HUB account
#########################
[profile dev]
# Role to assume - each team will use it’s own role
role_arn = arn:aws:iam::703608045793:role/okta-admin-role
region = us-east-1
# source_profile = dev
session_ttl = 12h


#Spoke Accounts
###################

[profile development]
# Role to assume - each team will use it’s own role
role_arn = arn:aws:iam::703608045793:role/okta-admin-role
region = us-east-1
source_profile = dev
session_ttl = 12h

#Staging
##########

[profile staging]
source_profile = dev
role_arn = arn:aws:iam::238368749987:role/aws-okta-admin-role
region = us-east-1
assume_role_ttl = 1h

#GAS
##########

[profile gas]
source_profile = dev
role_arn = arn:aws:iam::759967409705:role/aws-okta-admin-role
region = us-east-1
assume_role_ttl = 1h


#CRISPR
###########

[profile crispr]
source_profile = dev
role_arn = arn:aws:iam::636792403073:role/aws-okta-admin-role
region = eu-west-1
assume_role_ttl = 1h
```

credentials:
```
[dev]
aws_access_key_id     = XXXXXXXXX
aws_secret_access_key = XXXXXX
aws_session_token     = XXXXXXXXX
aws_security_token    = XXXXXXXXX

[gas]
aws_access_key_id     = XXXXXXXXX
aws_secret_access_key = XXXXXXXXX
aws_session_token     = XXXXXXXXX
aws_security_token    = XXXXXXXXX

[crispr]
aws_access_key_id     = XXXXXXXXX
aws_secret_access_key = XXXXXXXXX
aws_session_token     = XXXXXXXXX
aws_security_token    = XXXXXXXXX
```

The cluster is on CRISPR account.
kubeconfig is ok.

Please assist.

**Comment by itowlson** [comment]
That's very weird - I don't know where that message is coming from or why that file is being parsed.  I wonder if `kubectl` is trying to read it while trying to authenticate to the cluster, but I don't understand why you then wouldn't see the same issue when running `kubectl` from the command line.

The only thing I can suggest is if you are willing to debug into the extension and see where the message is being emitted.  If you are willing to do this I can provide guidance and suggestions on where to start investigating.  Thanks in advance!

**Comment by yurigene** [comment]
I rearranged the config file and it works now. Closing the issue.

Working aws config:

`[okta]
# Okta Dev APP
#####################
aws_saml_url = home/amazon_aws/yyYYhshdYndmd/313


[profile dev]
source_profile = dev
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/okta-admin-role
region = us-east-1
session_ttl = 12h


[profile crispr]
source_profile = dev
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/aws-okta-admin-role
region = eu-west-1
assume_role_ttl = 1h


#[profile development]
# role_arn = arn:aws:iam::xxxxxxxxxxxx:role/okta-admin-role
# region = us-east-1
# source_profile = dev
# session_ttl = 12h


[profile staging]
source_profile = dev
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/aws-okta-admin-role
region = us-east-1
assume_role_ttl = 1h


[profile rndlab]
source_profile = dev
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/aws-okta-admin-role
region = us-east-1
assume_role_ttl = 1h`

**Comment by bil9000** [comment]
I had that same issue. I'm baffled.
