### ISSUE TITLE
Can't add existing cluster

### ISSUE THREAD

**Issue by arisewanggithub** [Azure/vscode-kubernetes-tools#945]
I want to add an existing AKS cluster. but every time after choosing the subscription in the add existing cluster process, the page just shows empty, nothing happens forever.
I've tried re-install visual studio code. Tried re-installing the kubernetes extension. But either helps. There is also no error in the output. What should I do next to fix the issue?
I'm using windows 10.

**Comment by itowlson** [comment]
Could you try:

* Install the AKS extension from the Marketplace (https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-aks-tools).
* In the Kubernetes sidebar, go to the Clouds pane (at the bottom by default).
* You should see an "Azure" entry there (it sometimes takes a few seconds to appear).
* Expand this and click the login option.
* After logging in, you should see your subscriptions (and can use the funnel icon to filter them).
* Find the desired subscription and expand it to see your clusters.
* Right-click the desired cluster and choose **Merge Into Kubeconfig**.

I'm not sure what's going on in your Add Existing Cluster wizard, but my guess is that the Azure CLI is blocking on user input (possibly authentication).  However, we're retiring the wizard in favour of the Clouds pane and the plug-in model, which should be more robust about this sort of thing!  Let us know if you still run into problems using the Clouds pane and AKS extension though!

**Comment by arisewanggithub** [comment]
Wow, this way works. Thanks!
