### ISSUE TITLE
Extension downloads wrong binary on Apple M1

### ISSUE THREAD

**Issue by mateka** [Azure/vscode-kubernetes-tools#950]
Extension downloads wrong minikube binary. After the extension update, I have to manually download minikube binary from GitHub, rename it, make it executable and move it to the proper folder.

**Comment by itowlson** [comment]
Thanks for spotting and letting us know about this.  We need to check where we are assuming `amd64` architecture in our download paths.

**Comment by jleni** [comment]
any updates?

**Comment by drbennett** [comment]
Any updates on this issue?

**Comment by lstocchi** [comment]
We completely forgot about it sorry. Working on it now so we can include it in next release https://github.com/Azure/vscode-kubernetes-tools/pull/1018

**Comment by lstocchi** [comment]
Opened a PR to fix this https://github.com/Azure/vscode-kubernetes-tools/pull/1019 but i don't have a mac close to me to try it. If one of you could give it a try it would be awesome @drbennett @jleni @mateka

**Comment by itowlson** [comment]
Our PR builds don't produce installable packages so here's one if folks are in a position to test.  Download, unzip and use the `Extensions: Install from VSIX...` command in VS Code to install it (you may need to restart VS Code).

[vscode-kubernetes-tools-1.3.5+preview1.zip](https://github.com/Azure/vscode-kubernetes-tools/files/7758400/vscode-kubernetes-tools-1.3.5%2Bpreview1.zip)
