### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by brittblak4** [Azure/vscode-kubernetes-tools#952]
- Issue Type: `Bug`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `1.3.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by itowlson** [comment]
Kia ora @brittblak4, do you have any more information about this issue?  Thanks!

**Comment by lstocchi** [comment]
Closing it as we don't have enough infos about this issue. Please feel free to reopen it if you still face it. Thanks!
