### ISSUE TITLE
Preview Helm Template:  could not resolve template path

### ISSUE THREAD

**Issue by jonsalvas** [Azure/vscode-kubernetes-tools#98]
Under Windows10 and VSCode 1.20.1 I receive the following error when trying to open the template preview:

Failed template call.Error: could not resolve template path: GetFileAttributesEx c:\Dev\XXXXXXX\deploy\helm\helm\templates\deployment.yaml: The system cannot find the path specified.

It seems that he is looking for the "helm" folder twice, although my templates are located in
c:\Dev\XXXXXXX\deploy\helm\templates\

**Comment by itowlson** [comment]
Thanks for reporting this.  I've reproduced it and will work on a fix.
