### ISSUE TITLE
Provide extension recommendation for Camel K

### ISSUE THREAD

**Issue by apupier** [Azure/vscode-kubernetes-tools#985]
The idea is to leverage the new feature of extension recommendation https://github.com/Azure/vscode-kubernetes-tools/pull/780 for Camel

**Comment by apupier** [comment]
3 extensions useful:
- the Camel Extension pack https://marketplace.visualstudio.com/items?itemName=redhat.apache-camel-extension-pack
- Tooling for Apache Camel K https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk
- Language Support for Apache Camel https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel

with current tags not harmonized (might be better to harmonize first):
- Camel Extension Pack
  - Camel
  - Fuse
  - Red Hat Fuse
  - wsdl
- Tooling for Apache Camel K
  - Camel
  - Camel K
  - camelk
  - Camel-K
  - kamel
  - Tool
- Language Support for Apache Camel:
   - Apache Camel Kafka Connector
   - Camel
   - groovy
   - java
   - javascript
   - kotlin
   - Language Server Protocol
   - LSP
   - properties
   - quarkus-properties
   - spring-boot-properties
   - Tool
   - xml
   - yaml
The one in common is `Camel` but this tag is pulling too many unrelated extensions (related to camel case).

proposal: adding a tag `Camel Yaml` on these extensions, then adding it to the recommended list of extensions

**Comment by lstocchi** [comment]
@apupier sounds good to me. Can you please tell me when the new tag is added?

**Comment by apupier** [comment]
> Can you please tell me when the new tag is added?

@lstocchi tag added on the 3 extensions ([another one in progress](https://github.com/apupier/camel-karavan/commit/60a6799b9c15e7b03ca52cf16e2faf126cd77420) but not blocking) I provided a [Pull request](https://github.com/Azure/vscode-kubernetes-tools/pull/1010)
