### ISSUE TITLE
Problem displaying the logs when the lines contains '<'

### ISSUE THREAD

**Issue by arbesulo** [Azure/vscode-kubernetes-tools#988]
When I see the logs from the extension I see this:

```
	from /app/config/application.rb:24:in `'
	from /app/config/application.rb:22:in `
'
```

but the original lines are:

``` 
     from /app/config/application.rb:24:in `<module:ModuleName>'
     from /app/config/application.rb:22:in `<main>'
```

It happens on every line when some class name is enclosed in '<' '>'

**Comment by lstocchi** [comment]
@arbesulo the new version has been released 2 weeks ago. Have you had the chance to verify it? Do you still face this issue? Let us know, thanks!!

**Comment by arbesulo** [comment]
Now it works perfect. Thanks for solving the issue!

**Comment by lstocchi** [comment]
Cool, you're welcome!! Closing it then. If you face any other issue or have some ideas how to improve the extension, let us know please. Thanks!!
