### ISSUE TITLE
Feature: add option to display nodes grouped by a namespace 

### ISSUE THREAD

**Issue by wvolkov** [Azure/vscode-kubernetes-tools#993]
I would like to put under consideration following feature:

At extension panel it could be quite handy to display Nodes siblings according to its namespace belonging, additionally to existing pool order:

**Current View:**
![image](https://user-images.githubusercontent.com/49549154/139525195-5796bc75-992d-4796-8c03-3181daf6ec13.png)

**Suggested grouping by namespace:**
![image](https://user-images.githubusercontent.com/49549154/139525408-55ba42ab-14fd-44d9-8d7a-069bab9423b1.png)

**Comment by gorkem** [comment]
I do not believe Kubernetes Nodes belong to specific namespaces.  Scheduler can schedule workloads from any workspace by default. Do you have a specific toleration or node-selector on your workloads ?

**Comment by wvolkov** [comment]
Maybe I described something wrong, please correct me. 

I consider not Nodes, but its siblings (if my understanding is correct - pods). So in cases, where each pod has assignment to a specific namespace other than default:
![image](https://user-images.githubusercontent.com/49549154/139542485-9036beea-8583-4330-bd83-23d554c1a4e0.png)

It would be great at add a setting to group it at view panel, similarly as it works at Lens app for instance:

![image](https://user-images.githubusercontent.com/49549154/139543189-729c5402-669e-4072-9186-16856229d2a7.png)

**Comment by gorkem** [comment]
A namespace grouped list of pods makes sense. That is what Lens shows. And I think you can get that today but selecting a namespace. The selected namespace is shown with a `*` before its name. Workloads>Pods actually filters to the selected namespaces. 

OTOH I think filtering with namespace that is selected from an unrelated part of the tree does make this unintuitive to use.

**Comment by wvolkov** [comment]
> A namespace grouped list of pods makes sense. That is what Lens shows. And I think you can get that today but selecting a namespace. The selected namespace is shown with a `*` before its name. Workloads>Pods actually filters to the selected namespaces.
> 
> OTOH I think filtering with namespace that is selected from an unrelated part of the tree does make this unintuitive to use.

Thanks for the hint, that approach worked like a charm, pods are being filtered as I purposed, I didn't know that.
![image](https://user-images.githubusercontent.com/49549154/141244481-2cb2be52-84fc-4a8b-b8b5-acbab4bddb87.png)

Closing the issue, thanks everyone for your time and assistance.
